import React,{useEffect,useRef,useState} from 'react';
import {BookOpen,CheckCircle2,GitBranch,Plus,Search,ShieldCheck,X} from 'lucide-react';
type Row=Record<string,any>;
type Props={request:(path:string,body?:unknown)=>Promise<any>;permissions:string[];me:Row};
const initial={kind:'CREATE',code:'',name:'',accountType:'EXPENSE',parentId:null as string|null,postable:true,reason:'',expectedVersion:1,accountId:''};
export function CoaSettings({request,permissions,me}:Props){
 const has=(p:string)=>permissions.includes(p),serial=useRef(0),dialogRef=useRef<HTMLElement|null>(null),busyRef=useRef(false);
 const [view,setView]=useState('catalog'),[q,setQ]=useState(''),[page,setPage]=useState(1),[state,setState]=useState('PENDING'),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
 const [dialog,setDialog]=useState<'proposal'|'review'|null>(null),[form,setForm]=useState(initial),[review,setReview]=useState<Row|null>(null),[decision,setDecision]=useState('APPROVE'),[reviewReason,setReviewReason]=useState('');
 const [topLevel,setTopLevel]=useState(true),[parentQ,setParentQ]=useState(''),[parentPage,setParentPage]=useState(1),[parents,setParents]=useState<Row[]>([]),[parentTotal,setParentTotal]=useState(0),[parentLabel,setParentLabel]=useState(''),[parentError,setParentError]=useState(''),[parentLoading,setParentLoading]=useState(false),[parentIndex,setParentIndex]=useState(0);
 busyRef.current=busy;
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null;
  const frame=requestAnimationFrame(()=>{(dialogRef.current?.querySelector('input,select,textarea,button') as HTMLElement|null)?.focus();});
  const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busyRef.current)setDialog(null);}if(e.key==='Tab'){const items=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')??[]).filter(el=>el.offsetParent!==null);if(items.length&&e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items[items.length-1].focus();}else if(items.length&&!e.shiftKey&&document.activeElement===items[items.length-1]){e.preventDefault();items[0].focus();}}};
  document.addEventListener('keydown',onKey,true);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',onKey,true);if(previous?.isConnected)previous.focus();};
 },[dialog]);
 useEffect(()=>{const generation=++serial.current;let cancelled=false;setRows([]);setTotal(0);setLoading(true);setError('');const timer=setTimeout(async()=>{try{const result=await request((view==='catalog'?'/admin/accounts':'/admin/account-changes')+'?q='+encodeURIComponent(q)+'&page='+page+'&limit=25'+(view==='requests'&&state?'&state='+state:''));if(!cancelled&&generation===serial.current){setRows(result.data);setTotal(result.total);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,view,q,page,state,refresh]);
 useEffect(()=>{if(dialog!=='proposal'||form.kind!=='CREATE'||topLevel)return;let cancelled=false;setParentLoading(true);setParentError('');setParents([]);const timer=setTimeout(async()=>{try{const r=await request('/admin/accounts/parents?accountType='+form.accountType+'&q='+encodeURIComponent(parentQ)+'&page='+parentPage+'&limit=10');if(!cancelled){setParents(r.data);setParentTotal(r.total);setParentIndex(0);}}catch(e){if(!cancelled)setParentError((e as Error).message);}finally{if(!cancelled)setParentLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,dialog,form.kind,form.accountType,topLevel,parentQ,parentPage]);
 function reset(){setError('');setNotice('');setParentQ('');setParentPage(1);setParents([]);setParentLabel('');setTopLevel(true);setReviewReason('');setDecision('APPROVE');}
 function propose(row?:Row){reset();setForm(row?{...initial,kind:'RENAME',accountId:row.id,code:row.code,name:row.name,expectedVersion:row.version}:{...initial});setDialog('proposal');}
 function inspect(row:Row){reset();setReview(row);setDialog('review');}
 function pickParent(row:Row){setForm(prev=>({...prev,parentId:row.id}));setParentLabel(row.code+' · '+row.name);}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{
  if(dialog==='proposal'){
   const body=form.kind==='CREATE'?{kind:form.kind,code:form.code,name:form.name,accountType:form.accountType,parentId:topLevel?null:form.parentId,postable:form.postable,reason:form.reason}:{kind:form.kind,accountId:form.accountId,expectedVersion:form.expectedVersion,name:form.name,reason:form.reason};
   if(form.kind==='CREATE'&&!topLevel&&!form.parentId)throw Error('Select an eligible parent account or explicitly choose top-level.');
   await request('/admin/account-changes',body);setNotice('Proposal submitted. No account or balance has changed; another authorized user must review it.');setView('requests');setState('PENDING');setPage(1);setQ('');
  }else{await request('/admin/account-changes/'+review!.id+'/decide',{decision,reason:reviewReason});setNotice(decision==='APPROVE'?'Account change applied with independent review and an atomic audit. No journal was posted.':'Request rejected. No account was changed.');}
  setDialog(null);setRefresh(n=>n+1);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const label=(row:Row)=>row.code??row.target_code;
 return <div className="coa-settings"><div className="notice"><ShieldCheck size={20}/><p><b>Review before configuration takes effect.</b> Propose a non-control account or a name correction; another authorized user must approve. Codes, classification, parent, currency, active status and historical journals are not editable here.</p></div>
 <section className="panel"><div className="panel-title"><div><h2>Chart of accounts controls</h2><p>Company-scoped · independent review · no opening balances</p></div>{has('accounts:propose')&&<button className="primary" onClick={()=>propose()}><Plus size={16}/>Propose account</button>}</div>
 <div className="coa-toolbar"><div className="coa-views" aria-label="Account configuration view"><button className={view==='catalog'?'primary':'secondary'} onClick={()=>{setView('catalog');setPage(1);setQ('');}}><BookOpen size={15}/>Account catalog</button><button className={view==='requests'?'primary':'secondary'} onClick={()=>{setView('requests');setPage(1);setQ('');}}><GitBranch size={15}/>Change requests</button></div><label className="coa-search"><Search size={16}/><input aria-label="Search account configuration" placeholder="Search code or name…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{view==='requests'&&<label>Request status<select aria-label="Request status" value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="PENDING">Pending review</option><option value="APPLIED">Applied</option><option value="REJECTED">Rejected</option><option value="">All requests</option></select></label>}</div>
 {error&&!dialog&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status"><CheckCircle2 size={18}/><p>{notice}</p></div>}
 <div className="table-wrap" aria-busy={loading}><table><thead><tr><th>Account</th><th>{view==='catalog'?'Classification':'Change'}</th><th>{view==='catalog'?'Posting policy':'Status'}</th><th>Attribution</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong className="mono">{label(r)}</strong><small>{r.name}</small>{view==='catalog'?<small>v{r.version}{r.parent_code?' · Parent '+r.parent_code:' · Top-level'}</small>:r.kind==='RENAME'&&<small>Expected v{r.expected_version} · current v{r.current_version}</small>}</td><td>{view==='catalog'?r.account_type:r.kind}</td><td>{view==='catalog'?<><span className={'badge '+(r.active?'active':'planned')}>{r.control_type?'CONTROL · '+r.control_type:r.postable?'POSTABLE':'HEADING'}</span>{!r.active&&<small>Inactive</small>}</>:<span className={'badge '+(r.state==='PENDING'?'draft':r.state==='APPLIED'?'active':'rejected')}>{r.state}</span>}</td><td><b>{r.creator}</b>{view==='catalog'?<small>{r.editor?'Last applied by '+r.editor:'Original creator retained'}</small>:<small>{r.reviewer?'Reviewed by '+r.reviewer:'Independent review required'}</small>}</td><td>{view==='catalog'&&has('accounts:propose')&&<button className="secondary" onClick={()=>propose(r)}>Propose name change</button>}{view==='requests'&&<button className="secondary" onClick={()=>inspect(r)}>{r.state==='PENDING'&&has('accounts:approve')?'Review request':'View request'}</button>}</td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="empty"><BookOpen/><h3>No matching {view==='catalog'?'accounts':'requests'}</h3><p>Search another code or change the request status.</p></div>}</div>
 <div className="coa-pagination"><span>{loading?'Loading…':`${total} results · page ${page} of ${Math.max(1,Math.ceil(total/25))}`}</span><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></section>
 {dialog&&<div className="modal-backdrop"><section ref={dialogRef} className="modal editor" role="dialog" aria-modal="true" aria-labelledby="coa-dialog-title"><div className="modal-title"><div><span className="eyebrow">CONTROLLED ACCOUNT CONFIGURATION</span><h2 id="coa-dialog-title">{dialog==='proposal'?(form.kind==='CREATE'?'Propose a new account':'Propose a name correction'):'Review account request'}</h2></div><button disabled={busy} aria-label="Close account dialog" onClick={()=>setDialog(null)}><X/></button></div><form onSubmit={save}>
 {dialog==='proposal'?<>{form.kind==='CREATE'?<><div className="form-row"><label>Account code<input value={form.code} minLength={2} maxLength={24} pattern="[A-Z0-9][A-Z0-9_\-]+" onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} required/></label><label>Account classification<select value={form.accountType} onChange={e=>{setForm({...form,accountType:e.target.value,parentId:null});setParentLabel('');setParentPage(1);}}>{['ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE'].map(v=><option key={v}>{v}</option>)}</select></label></div><label className="check-label"><input type="checkbox" checked={form.postable} onChange={e=>setForm({...form,postable:e.target.checked})}/>Postable account (uncheck for a heading)</label><label className="check-label"><input type="checkbox" checked={topLevel} onChange={e=>{setTopLevel(e.target.checked);setForm({...form,parentId:null});setParentLabel('');}}/>Top-level account (no parent)</label>{!topLevel&&<div className="coa-parent"><label>Find parent account<input role="combobox" aria-autocomplete="list" aria-expanded={parents.length>0} aria-controls="coa-parent-options" aria-activedescendant={parents[parentIndex]?'coa-parent-'+parents[parentIndex].id:undefined} value={parentQ} onChange={e=>{setParentQ(e.target.value);setParentPage(1);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setParentIndex(i=>Math.min(i+1,parents.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setParentIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();if(parents[parentIndex])pickParent(parents[parentIndex]);}}}/></label><small>{parentLabel?'Selected: '+parentLabel:'Select an active heading of the same classification.'}</small><div id="coa-parent-options" role="listbox" aria-label="Eligible parent accounts">{parents.map((p,i)=><button id={'coa-parent-'+p.id} className={i===parentIndex?'highlight':''} type="button" role="option" aria-selected={form.parentId===p.id} key={p.id} onClick={()=>pickParent(p)}>{p.code} · {p.name}</button>)}</div>{parentError&&<p role="alert">{parentError}</p>}{parentLoading?<small>Searching…</small>:<small>{parentTotal} eligible matches</small>}<div className="coa-pagination"><button type="button" className="secondary" disabled={parentLoading||parentPage<=1} onClick={()=>setParentPage(p=>p-1)}>Previous parents</button><button type="button" className="secondary" disabled={parentLoading||parentPage*10>=parentTotal} onClick={()=>setParentPage(p=>p+1)}>Next parents</button></div></div>}</>:<div className="notice"><p><b>{form.code} · version {form.expectedVersion}</b><br/>Only the display name may change. Original creator and every posted journal remain intact.</p></div>}
 <label>Proposed account name<input value={form.name} minLength={2} maxLength={120} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Proposal reason<textarea value={form.reason} minLength={5} maxLength={500} onChange={e=>setForm({...form,reason:e.target.value})} required/></label></>:review&&<><div className="coa-review"><span className="badge draft">{review.kind} · {review.state}</span><h3>{label(review)} · {review.name}</h3>{review.kind==='CREATE'?<p>{review.account_type} · {review.postable?'Postable non-control account':'Non-postable heading'}<br/>Parent: {review.parent_code?review.parent_code+' · '+review.parent_name:'Top-level (none)'}<br/>Company functional-currency policy; no opening balance</p>:<p>Current name: {review.current_name}<br/>Expected version {review.expected_version}; current version {review.current_version}</p>}<p><b>Proposed by {review.creator}</b><br/>{new Date(review.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi<br/>{review.reason}</p>{review.reviewed_by&&<p>Reviewed by {review.reviewer}<br/>{new Date(review.reviewed_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi<br/>{review.review_reason}</p>}</div>{review.state==='PENDING'&&has('accounts:approve')&&review.created_by!==me.id?<><label>Review decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="APPROVE">Approve and apply</option><option value="REJECT">Reject without changes</option></select></label><label>Review reason<textarea value={reviewReason} minLength={5} maxLength={500} onChange={e=>setReviewReason(e.target.value)} required/></label></>:<div className="notice"><ShieldCheck size={18}/><p>{review.created_by===me.id?'You cannot review your own request. Another authorized user must decide.':review.state==='PENDING'?'You have read-only access to this request.':'This decision is final. Submit a new proposal for any correction.'}</p></div>}</>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setDialog(null)}>Close</button>{dialog==='proposal'?<button className="primary" disabled={busy||(form.kind==='CREATE'&&!topLevel&&!form.parentId)}>Submit account proposal</button>:review?.state==='PENDING'&&has('accounts:approve')&&review.created_by!==me.id&&<button className="primary" disabled={busy}>Confirm account decision</button>}</div></form></section></div>}
 </div>;
}
