import React,{useEffect,useState} from 'react';
import {Building2,X} from 'lucide-react';
type Row=Record<string,any>;
export function CompanyProfile({request,canManage,onRenamed}:{request:(path:string,body?:unknown)=>Promise<any>;canManage:boolean;onRenamed?:(name:string)=>void}){
 const [company,setCompany]=useState<Row|null>(null),[edit,setEdit]=useState(false),[name,setName]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;request('/admin/company').then(c=>{if(active)setCompany(c);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[request]);
 async function save(e:React.FormEvent){e.preventDefault();if(!company)return;setBusy(true);setError('');try{const r=await request('/admin/company/revise',{name,reason,expectedVersion:company.version});setEdit(false);setCompany(await request('/admin/company'));onRenamed?.(r.name);setNotice('Company display name revised. Accounting identity and existing journals are unchanged.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="notice"><Building2 size={18}/><p>This company's display name can be revised with a reason. Code, tax identity, functional currency, timezone and lifecycle controls are read-only. New-company onboarding is not yet released.</p></div>{notice&&<div className="notice" role="status">{notice}</div>}{error&&!edit&&<div className="error" role="alert">{error}</div>}{company&&<section className="panel"><div className="panel-title"><div><h2>Company profile</h2><p>Version {company.version} · original creator {company.creator}</p></div>{canManage&&<button className="primary" onClick={()=>{setName(company.name);setReason('');setError('');setEdit(true);}}>Revise company name</button>}</div><div className="table-wrap"><table><tbody>{[['Display name',company.name],['Company code',company.code],['Functional currency',company.base_currency],['Business timezone',company.timezone],['Tax PIN',company.tax_pin??'Not configured — not validated for fiscal use'],['Status',company.active?'ACTIVE':'INACTIVE'],['Last editor',company.editor??'—']].map(([label,value])=><tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table></div></section>}{edit&&company&&<div className="modal-backdrop"><section className="modal confirm" role="dialog" aria-modal="true" aria-labelledby="company-title"><div className="modal-title"><h2 id="company-title">Revise company display name</h2><button disabled={busy} aria-label="Close company editor" onClick={()=>setEdit(false)}><X/></button></div><form onSubmit={save}><label>Company display name<input required autoFocus minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Company change reason<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setEdit(false)}>Cancel</button><button className="primary" disabled={busy}>Save company name</button></div></form></section></div>}</>;
}
