import React,{useEffect,useId,useState} from 'react';
type Row=Record<string,any>;
export function ConfigurationPicker({request,path,label,value,onChange,disabled=false}:{request:(p:string)=>Promise<any>;path:string;label:string;value:Row|null;onChange:(r:Row|null)=>void;disabled?:boolean}){
 const id=useId(),[q,setQ]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[index,setIndex]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;setLoading(true);setRows([]);setError('');const timer=setTimeout(async()=>{try{const r=await request(path+(path.includes('?')?'&':'?')+'q='+encodeURIComponent(q)+'&page='+page+'&limit=8');if(!cancelled){setRows(r.data);setTotal(r.total);setIndex(0);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,path,q,page]);
 return <div className="coa-parent config-picker"><label>{label}<input role="combobox" aria-autocomplete="list" aria-expanded={rows.length>0} aria-controls={id} aria-activedescendant={rows[index]?id+'-'+index:undefined} value={q} disabled={disabled} onChange={e=>{setQ(e.target.value);setPage(1);onChange(null);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,rows.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();if(rows[index])onChange(rows[index]);}}}/></label>
 <small>{value?'Selected: '+value.code+' · '+value.name:'No selection'}</small>{value&&<button className="text-button" type="button" disabled={disabled} onClick={()=>onChange(null)}>Clear {label.toLowerCase()}</button>}
 <div id={id} role="listbox" aria-label={'Matches for '+label}>{rows.map((r,i)=><button key={r.id} id={id+'-'+i} type="button" role="option" aria-selected={value?.id===r.id} className={index===i?'highlight':''} disabled={disabled} onClick={()=>onChange(r)}>{r.code} · {r.name}</button>)}</div>
 {error&&<div className="error" role="alert">{error}</div>}<small>{loading?'Searching…':total+' matches'}</small><div className="coa-pagination"><button type="button" className="secondary" disabled={disabled||loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous matches</button><button type="button" className="secondary" disabled={disabled||loading||page*8>=total} onClick={()=>setPage(p=>p+1)}>Next matches</button></div>
 </div>;
}
