import {Customers} from './Customers';
import {StockAdjustments} from './StockAdjustments';
import {Products} from './Products';
import {ProductReferences} from './ProductReferences';
import {TaxSettings} from './TaxSettings';
import {PostingRuleSettings} from './PostingRuleSettings';
import {NumberingSettings} from './NumberingSettings';
import {CoaSettings} from './CoaSettings';
import {CompanyProfile} from './CompanyProfile';
import {WarehouseSettings} from './WarehouseSettings';
import {BranchSettings} from './BranchSettings';
import React,{useEffect,useState} from 'react';
import {Building2,Warehouse,Users,ShieldCheck,GitBranch,Plus,Search,X,LockKeyhole,CheckCircle2} from 'lucide-react';
type Row=Record<string,any>;
type Props={request:(path:string,body?:unknown)=>Promise<any>;permissions:string[];me:Row;company:string;currency?:string;stockTarget?:string|null;onStockCommitted?:()=>void;onCompanyRenamed?:(name:string)=>void};
const initial={name:'',email:'',permissions:[] as string[],roleIds:[] as string[],branchIds:[] as string[],active:true,reason:'',threshold:'0.00',eventType:'MANUAL_JOURNAL',independentCreator:true,independentPoster:true,steps:[{permission:'journals:approve',minimumApprovers:1}]} as Row;
export function ControlCenter({request,permissions,me,company,currency,stockTarget,onStockCommitted,onCompanyRenamed}:Props){
 const has=(p:string)=>permissions.includes(p),tabs=[['Members','users:view',Users],['Roles','roles:view',ShieldCheck],['Approval policies','approvals:view',GitBranch],['Security events','security:view',LockKeyhole],['Branches','organization:view',GitBranch],['Company','organization:view',Building2],['Warehouses','warehouses:view',Warehouse],['Account controls','accounts:configuration:view',Building2],['Numbering','numbering:view',GitBranch],['Posting rules','rules:view',GitBranch],['Tax configuration','taxes:view',ShieldCheck],['Product setup','products:view',Warehouse],['Products','products:view',Warehouse],['Stock adjustments','inventory:view',Warehouse],['Customers','customers:view',Users]] as const;
 const [tab,setTab]=useState(tabs.find(t=>has(t[1]))?.[0]??'Approval policies'),[members,setMembers]=useState<Row[]>([]),[roles,setRoles]=useState<Row[]>([]),[policies,setPolicies]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[config,setConfig]=useState<Row>({permissions:[],delegable:[],branches:[]}),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState('');
 const [dialog,setDialog]=useState<null|'member'|'role'|'policy'|'publish'>(null),[form,setForm]=useState<Row>(initial),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[optionSearch,setOptionSearch]=useState('');
 useEffect(()=>{if(stockTarget&&has('inventory:view'))setTab('Stock adjustments');},[stockTarget]);
 async function load(){setBusy(true);setError('');try{if(has('users:view')){const r=await request('/admin/users?q='+encodeURIComponent(search)+'&page='+page);setMembers(r.data);setTotal(r.total);}if(has('roles:view')){setRoles(await request('/admin/roles'));setConfig(await request('/admin/permissions'));}if(has('approvals:view'))setPolicies(await request('/admin/approval-policies'));if(has('security:view'))setEvents(await request('/admin/security-events'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t);},[company,request,search,page]);
 function open(type:typeof dialog,row?:Row){setForm({...initial,branchIds:[],...(row??{}),existingBranchIds:row?.branchIds??[],name:row?.display_name??row?.name??'',reason:''});setOptionSearch('');setError('');setDialog(type);}
 function toggle(field:string,id:string){const values=form[field] as string[];setForm({...form,[field]:values.includes(id)?values.filter(v=>v!==id):[...values,id]});}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
  if(dialog==='member'){if(form.id)await request('/admin/users/'+form.id+'/access',{active:form.active,roleIds:form.roleIds,branchIds:form.branchIds,expectedVersion:form.version,reason:form.reason});else await request('/admin/users',{email:form.email,name:form.name,roleIds:form.roleIds,branchIds:form.branchIds,reason:form.reason});}
  if(dialog==='role')await request('/admin/roles'+(form.id?'/'+form.id+'/revise':''),{name:form.name,permissions:form.permissions,reason:form.reason,...(form.id?{expectedVersion:form.version}:{})});
  if(dialog==='policy')await request('/admin/approval-policies',{eventType:form.eventType,threshold:form.threshold,independentCreator:form.independentCreator,independentPoster:form.independentPoster,steps:form.steps,reason:form.reason});
  if(dialog==='publish')await request('/admin/approval-policies/'+form.id+'/publish',{reason:form.reason});
  setDialog(null);setNotice('Change committed with your user identity and an audit record.');await load();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="control-center"><div className="integrity-banner"><span className="integrity-icon"><ShieldCheck size={25}/></span><div><b>Access is explicit. Approval is independent.</b><p>Company-scoped administration · No posting powers are implied by an administrative role.</p></div></div><div className="control-tabs">{tabs.filter(t=>has(t[1])).map(([name,,Icon])=><button className={tab===name?'selected':''} key={name} onClick={()=>{setTab(name);setSearch('');setPage(1);}}><Icon size={16}/>{name}</button>)}</div>{error&&!dialog&&<div className="error">{error}</div>}{notice&&<div className="notice" role="status"><CheckCircle2 size={17}/>{notice}</div>}
 {tab==='Customers'&&<Customers request={request} permissions={permissions} me={me} currency={currency}/>}
 {tab==='Stock adjustments'&&<StockAdjustments request={request} permissions={permissions} me={me} currency={currency} sourceTarget={stockTarget} onCommitted={onStockCommitted}/>}
 {tab==='Products'&&<Products request={request} permissions={permissions} me={me}/>}
 {tab==='Product setup'&&<ProductReferences request={request} permissions={permissions}/>}
 {tab==='Tax configuration'&&<TaxSettings request={request} permissions={permissions} me={me}/>}
 {tab==='Posting rules'&&<PostingRuleSettings request={request} permissions={permissions} me={me}/>}
 {tab==='Company'&&<CompanyProfile request={request} canManage={has('organization:profile:manage')} onRenamed={onCompanyRenamed}/>}
 {tab==='Warehouses'&&<WarehouseSettings request={request} canManage={has('warehouses:manage')}/>}
 {tab==='Branches'&&<BranchSettings request={request} canManage={has('organization:manage')}/>}
 {tab==='Members'&&<section className="panel"><div className="panel-title"><div className="searchbox"><Search size={16}/><input aria-label="Search members" placeholder="Search name or email…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div>{has('users:manage')&&<button className="primary" onClick={()=>open('member')}><Plus size={15}/>Add member</button>}</div><div className="table-wrap"><table><thead><tr><th>Company member</th><th>Roles</th><th>Access</th><th>Revision</th><th/></tr></thead><tbody>{members.map(u=><tr key={u.id}><td><b>{u.display_name}</b><small>{u.email}</small>{u.super_admin&&<span className="badge active">SUPER ADMIN · ALL PERMISSIONS</span>}</td><td>{u.roleIds.map((id:string)=>roles.find(r=>r.id===id)?.name??'Assigned role').join(', ')}</td><td><span className={'badge '+(u.active?'active':'draft')}>{u.active?'ACTIVE':'SUSPENDED'}</span></td><td>v{u.version}</td><td>{has('users:manage')&&<button className="secondary" disabled={u.id===me.id||u.super_admin} onClick={()=>open('member',u)}>{u.super_admin?'Protected super admin':u.id===me.id?'Own access protected':'Manage access'}</button>}</td></tr>)}</tbody></table></div><div className="pagination"><span>{total} members · page {page}</span><div><button disabled={page===1||busy} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page*25>=total||busy} onClick={()=>setPage(page+1)}>Next</button></div></div></section>}
 {tab==='Roles'&&<><div className="notice"><LockKeyhole size={18}/><p>Permissions you may delegate are explicitly granted by the security owner. Editing your own role is prohibited. Changes apply immediately; historical activity is retained.</p></div><section className="panel"><div className="panel-title"><div><h2>Configurable roles</h2><p>First 100 roles · {config.delegable.length} delegable permissions for your user</p></div>{has('roles:manage')&&<button className="primary" onClick={()=>open('role')}><Plus size={15}/>Create role</button>}</div><div className="table-wrap"><table><thead><tr><th>Role</th><th>Granted permissions</th><th>Version</th><th/></tr></thead><tbody>{roles.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td><div className="permission-chips">{r.permissions.map((p:string)=><span key={p}>{p}</span>)}</div></td><td>v{r.version}</td><td>{has('roles:manage')&&<button className="secondary" onClick={()=>open('role',r)}>Revise role</button>}</td></tr>)}</tbody></table></div></section></>}
 {tab==='Approval policies'&&<><div className="notice"><GitBranch size={18}/><p>The highest published threshold at or below the journal debit or submitted stock value applies. A submitted source keeps its policy snapshot even if a newer version is published. Without a matching policy, the company-baseline independent approval applies.</p></div><section className="panel"><div className="panel-title"><div><h2>Versioned approval policies</h2><p>Draft → independent publication → immutable submitted snapshots</p></div>{has('approvals:manage')&&<button className="primary" onClick={()=>open('policy')}><Plus size={15}/>Draft policy</button>}</div>{!policies.length?<div className="empty"><GitBranch/><h3>No custom policies yet</h3><p>Company-baseline approval remains enforced. This is not an approval bypass.</p></div>:policies.map(p=><div className="policy-card" key={p.id}><div className="policy-top"><div><b>{p.event_type.replaceAll('_',' ')}</b><p>{p.currency??currency??'—'} {p.threshold_base} and above · version {p.version}</p></div><span className={'badge '+(p.active?'active':p.published_by?'planned':'draft')}>{p.active?'ACTIVE':p.published_by?'SUPERSEDED':'DRAFT'}</span></div><div className="policy-steps">{p.steps.map((st:Row)=><span key={st.number}><b>{st.number}</b>{st.permission} × {st.minimumApprovers}</span>)}</div><div className="policy-bottom"><small>Created by {p.creator} · {p.publisher?'Published by '+p.publisher:'Independent publisher required'}</small>{!p.published_by&&has('approvals:publish')&&<button className="primary" disabled={p.created_by===me.id} onClick={()=>open('publish',p)}>Publish policy</button>}</div><small className="muted">Creator exclusion: {p.independent_creator?'required':'not required'} · Poster exclusion: {p.independent_poster?'all approvers and creator':'not required'}</small></div>)}</section></>}
 {tab==='Numbering'&&has('numbering:view')&&<NumberingSettings key={company} request={request} permissions={permissions} me={me}/>}
 {tab==='Account controls'&&has('accounts:configuration:view')&&<CoaSettings key={company} request={request} permissions={permissions} me={me}/>}
 {tab==='Security events'&&<section className="panel"><div className="panel-title"><div><h2>Company security events</h2><p>Latest 50 scoped events. Global login/password events are retained separately and are not exposed across companies.</p></div></div><div className="table-wrap"><table><thead><tr><th>Date / time</th><th>Actor</th><th>Action</th><th>Outcome</th><th>Request</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})}</td><td>{e.actor}</td><td>{e.action}</td><td><span className="badge draft">{e.outcome}</span></td><td className="mono">{e.request_id.slice(0,8)}</td></tr>)}</tbody></table>{!events.length&&<div className="empty"><ShieldCheck/><h3>No scoped security events yet</h3><p>Successful administration is recorded in the audit trail.</p></div>}</div></section>}
 {dialog&&<div className="modal-backdrop"><section className="modal editor" role="dialog" aria-modal="true" aria-labelledby="control-dialog-title"><div className="modal-title"><div><span className="eyebrow">ATTRIBUTED CONTROL CHANGE</span><h2 id="control-dialog-title">{dialog==='member'?(form.id?'Manage member access':'Add company member'):dialog==='role'?(form.id?'Revise role':'Create role'):dialog==='policy'?'Draft approval policy':'Publish approval policy'}</h2></div><button onClick={()=>setDialog(null)} aria-label="Close control dialog"><X/></button></div><form onSubmit={save}>
 {dialog==='member'&&<>{!form.id?<div className="form-row"><label>Member name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required minLength={2}/></label><label>Member email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label></div>:<div className="notice"><Users size={17}/><p>{form.email}<br/>Version {form.version}. Deactivation only affects this company; global identity and historical attribution remain.</p></div>}<label className="check-label"><input type="checkbox" checked={form.active} disabled={!form.id} onChange={e=>setForm({...form,active:e.target.checked})}/>Active company membership</label><h3>Roles</h3><div className="check-grid">{roles.map(r=><label className="check-label" key={r.id}><input type="checkbox" checked={form.roleIds.includes(r.id)} onChange={()=>toggle('roleIds',r.id)}/>{r.name}</label>)}</div><h3>Branch access</h3><div className="check-grid">{config.branches.map((b:Row)=><label className="check-label" key={b.id}><input type="checkbox" checked={form.branchIds.includes(b.id)} disabled={!b.active&&!form.existingBranchIds.includes(b.id)} onChange={()=>toggle('branchIds',b.id)}/>{b.name}{!b.active?' (inactive; retained access only)':''}</label>)}</div>{!form.id&&<div className="notice"><p>No initial password is exposed. The user establishes credentials through the configured password-reset delivery channel.</p></div>}</>}
 {dialog==='role'&&<><label>Role name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} minLength={3} required/></label><label>Find permissions<input placeholder="Search permission code…" value={optionSearch} onChange={e=>setOptionSearch(e.target.value)}/></label><div className="permission-options">{config.permissions.filter((p:Row)=>p.code.includes(optionSearch)).map((p:Row)=><label className="check-label" key={p.code}><input type="checkbox" checked={form.permissions.includes(p.code)} disabled={!config.delegable.includes(p.code)} onChange={()=>toggle('permissions',p.code)}/><span>{p.code}<small>{p.description}{!config.delegable.includes(p.code)?' · not delegated':''}</small></span></label>)}</div></>}
 {dialog==='policy'&&<><div className="form-row"><label>Source type<select value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value,steps:form.steps.map((st:Row)=>({...st,permission:['journals:approve','inventory:approve'].includes(st.permission)?(e.target.value.startsWith('STOCK_')?'inventory:approve':'journals:approve'):st.permission}))})}><option value="MANUAL_JOURNAL">Manual journal</option><option value="JOURNAL_REVERSAL">Journal reversal</option><option value="STOCK_GAIN">Stock gain</option><option value="STOCK_LOSS">Stock loss</option><option value="STOCK_REVERSAL">Stock reversal</option></select></label><label>{form.eventType.startsWith('STOCK_')?'Minimum stock value':'Minimum debit total'} ({currency??'functional currency'})<input inputMode="decimal" value={form.threshold} pattern="[0-9]+(\.[0-9]{1,2})?" onChange={e=>setForm({...form,threshold:e.target.value})} required/></label></div><label className="check-label"><input type="checkbox" checked={form.independentCreator} onChange={e=>setForm({...form,independentCreator:e.target.checked})}/>Creator cannot approve</label><label className="check-label"><input type="checkbox" checked={form.independentPoster} onChange={e=>setForm({...form,independentPoster:e.target.checked})}/>Poster must differ from creator and every approver</label><h3>Ordered approval steps</h3>{form.steps.map((st:Row,i:number)=><div className="form-row" key={i}><label>Step {i+1} permission<input list="workflow-permissions" value={st.permission} onChange={e=>setForm({...form,steps:form.steps.map((x:Row,n:number)=>n===i?{...x,permission:e.target.value}:x)})} required/></label><label>Distinct approvers<input type="number" min={1} max={5} value={st.minimumApprovers} onChange={e=>setForm({...form,steps:form.steps.map((x:Row,n:number)=>n===i?{...x,minimumApprovers:Number(e.target.value)}:x)})} required/></label></div>)}<datalist id="workflow-permissions">{config.permissions.map((p:Row)=><option value={p.code} key={p.code}/>)}</datalist><button className="text-button add-line" type="button" disabled={form.steps.length>=5} onClick={()=>setForm({...form,steps:[...form.steps,{permission:form.eventType.startsWith('STOCK_')?'inventory:approve':'journals:approve',minimumApprovers:1}]})}><Plus size={14}/>Add approval step</button></>}
 {dialog==='publish'&&<div className="notice"><ShieldCheck size={18}/><p>Publish version {form.version} for {form.event_type}, threshold KES {form.threshold_base}. This supersedes the active version at the same threshold, without changing existing submissions.</p></div>}
 <label>Reason for change<textarea minLength={5} maxLength={500} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/></label>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="secondary" type="button" onClick={()=>setDialog(null)}>Cancel</button><button className="primary" disabled={busy}>{dialog==='publish'?'Confirm publication':'Save control change'}</button></div></form></section></div>}
 </div>;
}
export function MySessions({request,onRevoked}:{request:Props['request'];onRevoked:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[password,setPassword]=useState(''),[current,setCurrent]=useState(''),[pending,setPending]=useState<Row|null>(null);
 const load=()=>request('/auth/sessions').then(setRows).catch(e=>setError(e.message));useEffect(()=>{load();},[request]);
 async function revoke(){if(!pending)return;setBusy(true);setError('');try{const r=await request('/auth/sessions/'+pending.id+'/revoke',{});setPending(null);if(r.currentRevoked)onRevoked();else await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function change(e:React.FormEvent){e.preventDefault();setBusy(true);try{await request('/auth/password/change',{currentPassword:current,newPassword:password});onRevoked();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="notice"><LockKeyhole size={19}/><p>Only your own sessions are shown. Revocation is enforced server-side. Changing your password revokes every session, including this one.</p></div>{error&&<div className="error">{error}</div>}<section className="panel"><div className="panel-title"><h2>Your sessions</h2><button className="secondary" onClick={()=>setPending({id:'all'})}>Revoke all sessions</button></div><div className="table-wrap"><table><thead><tr><th>Session</th><th>Last seen</th><th>Expires</th><th/></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>{s.current?'This device':s.revoked_at?'Revoked session':'Other session'}</b><small>{s.device}</small></td><td>{new Date(s.last_seen_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})}</td><td>{new Date(s.expires_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})}</td><td><button className="secondary" disabled={!!s.revoked_at} onClick={()=>setPending(s)}>Revoke session</button></td></tr>)}</tbody></table></div></section><section className="panel password-panel"><h2>Change your password</h2><p className="muted">Use a long, unique passphrase of 14–128 characters. You will need to sign in again.</p><form onSubmit={change}><div className="form-row"><label>Current password<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" minLength={14} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/></label></div><button className="primary" disabled={busy}>Change password and revoke sessions</button></form></section>{pending&&<div className="modal-backdrop"><section className="modal confirm" role="dialog" aria-modal="true"><h2>Revoke {pending.id==='all'?'all sessions':'this session'}?</h2><p>{pending.id==='all'||pending.current?'You will be signed out immediately.':'The selected device will lose access immediately.'}</p><div className="modal-actions"><button className="secondary" onClick={()=>setPending(null)}>Cancel</button><button className="primary" disabled={busy} onClick={revoke}>Confirm revocation</button></div></section></div>}</>;
}
