import React,{useEffect,useRef,useState} from 'react';
import {CheckCircle2,Hash,Plus,Search,ShieldCheck,X} from 'lucide-react';
type Row=Record<string,any>;
type Props={request:(path:string,body?:unknown)=>Promise<any>;permissions:string[];me:Row};
const fresh=()=>({branchId:'',documentType:'',year:Number(new Intl.DateTimeFormat('en',{timeZone:'Africa/Nairobi',year:'numeric'}).format(new Date())),prefix:'',padding:6,reason:''});
export function NumberingSettings({request,permissions,me}:Props){
 const has=(p:string)=>permissions.includes(p),dialogRef=useRef<HTMLElement|null>(null),busyRef=useRef(false);
 const [view,setView]=useState('catalog'),[q,setQ]=useState(''),[page,setPage]=useState(1),[state,setState]=useState('PENDING'),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[types,setTypes]=useState<Row[]>([]);
 const [dialog,setDialog]=useState<'proposal'|'review'|null>(null),[form,setForm]=useState(fresh),[current,setCurrent]=useState<Row|null>(null),[lookupLoading,setLookupLoading]=useState(false),[review,setReview]=useState<Row|null>(null),[decision,setDecision]=useState('APPROVE'),[reviewReason,setReviewReason]=useState('');
 const [branchQ,setBranchQ]=useState(''),[branchPage,setBranchPage]=useState(1),[branches,setBranches]=useState<Row[]>([]),[branchTotal,setBranchTotal]=useState(0),[branchLabel,setBranchLabel]=useState(''),[branchLoading,setBranchLoading]=useState(false),[branchIndex,setBranchIndex]=useState(0);
 const lookupKey=`${form.branchId}|${form.documentType}|${form.year}`,effective=current?.lookupKey===lookupKey?current:null;
 const canReview=review?.state==='PENDING'&&has('numbering:approve')&&review.created_by!==me.id;
 busyRef.current=busy;
 useEffect(()=>{let cancelled=false;request('/admin/numbering-policies/types').then(r=>{if(!cancelled)setTypes(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[request]);
 useEffect(()=>{let cancelled=false;setLoading(true);setRows([]);setTotal(0);const timer=setTimeout(async()=>{try{const r=await request((view==='catalog'?'/admin/numbering-policies':'/admin/numbering-policy-changes')+'?q='+encodeURIComponent(q)+'&page='+page+'&limit=25'+(view==='requests'&&state?'&state='+state:''));if(!cancelled){setRows(r.data);setTotal(r.total);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,view,q,page,state,refresh]);
 useEffect(()=>{if(dialog!=='proposal')return;let cancelled=false;setBranchLoading(true);const timer=setTimeout(async()=>{try{const r=await request('/admin/numbering-policies/branches?q='+encodeURIComponent(branchQ)+'&page='+branchPage+'&limit=10');if(!cancelled){setBranches(r.data);setBranchTotal(r.total);setBranchIndex(0);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setBranchLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,dialog,branchQ,branchPage]);
 useEffect(()=>{setCurrent(null);if(dialog!=='proposal'||!form.branchId||!form.documentType||form.year<1||form.year>9999){setLookupLoading(false);return;}let cancelled=false;setLookupLoading(true);const timer=setTimeout(async()=>{try{const r=await request('/admin/numbering-policies/effective?branchId='+form.branchId+'&documentType='+encodeURIComponent(form.documentType)+'&year='+form.year);if(!cancelled){setCurrent({...r,lookupKey});setForm(prev=>`${prev.branchId}|${prev.documentType}|${prev.year}`===lookupKey?{...prev,prefix:r.prefix,padding:r.padding}:prev);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLookupLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,dialog,lookupKey,form.branchId,form.documentType,form.year]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null;const frame=requestAnimationFrame(()=>{((dialogRef.current?.querySelector('input,select,textarea')??dialogRef.current?.querySelector('button')) as HTMLElement|null)?.focus();});const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busyRef.current)setDialog(null);}if(e.key==='Tab'){const items=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')??[]).filter(el=>el.offsetParent!==null);if(items.length&&e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items[items.length-1].focus();}else if(items.length&&!e.shiftKey&&document.activeElement===items[items.length-1]){e.preventDefault();items[0].focus();}}};document.addEventListener('keydown',onKey,true);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',onKey,true);if(previous?.isConnected)previous.focus();else document.getElementById('numbering-title')?.focus();};},[dialog]);
 function propose(row?:Row){setError('');setNotice('');setCurrent(null);setBranchPage(1);setBranchQ(row?.branch_code??'');setBranchLabel(row?row.branch_code+' · '+row.branch_name:'');setBranches([]);setForm({...fresh(),documentType:row?.document_type??types[0]?.document_type??'',...(row?{branchId:row.branch_id,year:row.calendar_year}:{})});setDialog('proposal');}
 function inspect(row:Row){setError('');setNotice('');setReview(row);setReviewReason('');setDecision(row.current_version!==row.expected_version?'REJECT':'APPROVE');setDialog('review');}
 function pickBranch(row:Row){setForm(prev=>({...prev,branchId:row.id}));setBranchLabel(row.code+' · '+row.name);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{
  if(dialog==='proposal'){if(!effective||effective.locked||!effective.branch.active)throw Error('Select an active branch and an unused numbering key, then wait for its current format.');await request('/admin/numbering-policy-changes',{...form,expectedVersion:effective.version});setNotice('Proposal saved without changing a format or counter. Another authorized user must review it.');setView('requests');setState('PENDING');setQ(form.prefix);setPage(1);}
  else{await request('/admin/numbering-policy-changes/'+review!.id+'/decide',{decision,reason:reviewReason});setNotice(decision==='APPROVE'?'Format applied with independent review and an atomic audit. No counter or balance was changed.':'Request rejected. The existing format and counters are unchanged.');}
  setDialog(null);setRefresh(n=>n+1);
 }catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const switchView=(next:string)=>{setView(next);setPage(1);setQ('');setError('');};
 return <div className="coa-settings"><div className="notice"><ShieldCheck size={20}/><p><b>Numbers are issued by the transaction, never by the browser.</b> Configure an unused branch / document type / calendar year. Once its sequence is initialized, the format is locked—even if a draft is cancelled. Counters and historical numbers cannot be edited.</p></div>
 <section className="panel"><div className="panel-title"><div><h2 id="numbering-title" tabIndex={-1}>Document numbering controls</h2><p>Inherited defaults · independent review · immutable issued numbers</p></div>{has('numbering:propose')&&<button className="primary" disabled={!types.length} onClick={()=>propose()}><Plus size={16}/>Propose numbering format</button>}</div>
 <div className="coa-toolbar"><div className="coa-views"><button className={view==='catalog'?'primary':'secondary'} onClick={()=>switchView('catalog')}>Published formats</button><button className={view==='requests'?'primary':'secondary'} onClick={()=>switchView('requests')}>Numbering requests</button></div><label className="coa-search"><Search size={16}/><input aria-label="Search numbering configuration" placeholder="Branch, prefix, year or document type…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{view==='requests'&&<label>Request status<select aria-label="Numbering request status" value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="PENDING">Pending review</option><option value="APPLIED">Applied</option><option value="REJECTED">Rejected</option><option value="">All requests</option></select></label>}</div>
 {error&&!dialog&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status"><CheckCircle2 size={18}/><p>{notice}</p></div>}
 <div className="table-wrap" aria-busy={loading}><table><thead><tr><th>Format</th><th>Branch / year</th><th>Status</th><th>Attribution</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong className="mono">{r.prefix}</strong><small>{r.document_type.replaceAll('_',' ')} · {r.padding} digits</small><small>{view==='catalog'?'v'+r.version:'Expected v'+r.expected_version+' · current v'+r.current_version}</small></td><td><b>{r.branch_code} · {r.calendar_year}</b><small>{r.branch_name}</small></td><td><span className={'badge '+(view==='catalog'?(r.locked?'planned':'active'):r.state==='PENDING'?'draft':r.state==='APPLIED'?'active':'rejected')}>{view==='catalog'?(r.locked?'LOCKED':'UNUSED'):r.state}</span></td><td><b>{r.creator}</b><small>{r.reviewer?'Reviewed by '+r.reviewer:'Independent review required'}</small></td><td>{view==='catalog'&&has('numbering:propose')&&<button className="secondary" disabled={r.locked||!r.branch_active} onClick={()=>propose(r)}>Revise numbering format</button>}{view==='requests'&&<button className="secondary" onClick={()=>inspect(r)}>{r.state==='PENDING'&&has('numbering:approve')?'Review numbering request':'View numbering request'}</button>}</td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="empty"><Hash/><h3>No matching {view==='catalog'?'overrides':'requests'}</h3><p>{view==='catalog'?'Keys without an override inherit the registered format. Proposals do not change those defaults.':'Change the search or request status.'}</p></div>}</div>
 <div className="coa-pagination"><span>{loading?'Loading…':`${total} results · page ${page} of ${Math.max(1,Math.ceil(total/25))}`}</span><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></section>
 {dialog&&<div className="modal-backdrop"><section ref={dialogRef} className="modal editor" role="dialog" aria-modal="true" aria-labelledby="numbering-dialog-title"><div className="modal-title"><div><span className="eyebrow">CONTROLLED DOCUMENT CONFIGURATION</span><h2 id="numbering-dialog-title">{dialog==='proposal'?'Propose numbering format':'Review numbering request'}</h2></div><button aria-label="Close numbering dialog" disabled={busy} onClick={()=>setDialog(null)}><X/></button></div><form onSubmit={save}>
 {dialog==='proposal'?<><div className="coa-parent"><label>Find numbering branch<input role="combobox" aria-autocomplete="list" aria-expanded={branches.length>0} aria-controls="numbering-branches" aria-activedescendant={branches[branchIndex]?'numbering-branch-'+branches[branchIndex].id:undefined} disabled={busy} value={branchQ} onChange={e=>{setBranchQ(e.target.value);setBranchPage(1);setForm({...form,branchId:''});setBranchLabel('');}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setBranchIndex(i=>Math.min(i+1,Math.max(0,branches.length-1)));}if(e.key==='ArrowUp'){e.preventDefault();setBranchIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();if(branches[branchIndex])pickBranch(branches[branchIndex]);}}}/></label><small>{branchLabel?'Selected: '+branchLabel:'Select an active branch in this company.'}</small><div id="numbering-branches" role="listbox" aria-label="Eligible numbering branches">{branches.map((b,i)=><button id={'numbering-branch-'+b.id} className={i===branchIndex?'highlight':''} role="option" type="button" aria-selected={form.branchId===b.id} disabled={busy} key={b.id} onClick={()=>pickBranch(b)}>{b.code} · {b.name}</button>)}</div><small>{branchLoading?'Searching…':branchTotal+' eligible matches'}</small><div className="coa-pagination"><button className="secondary" type="button" disabled={busy||branchLoading||branchPage<=1} onClick={()=>setBranchPage(p=>p-1)}>Previous branches</button><button className="secondary" type="button" disabled={busy||branchLoading||branchPage*10>=branchTotal} onClick={()=>setBranchPage(p=>p+1)}>Next branches</button></div></div>
 <div className="form-row"><label>Numbering document type<select disabled={busy} value={form.documentType} onChange={e=>{setForm({...form,documentType:e.target.value});setError('');}} required>{types.map(t=><option key={t.document_type} value={t.document_type}>{t.document_type.replaceAll('_',' ')}</option>)}</select></label><label>Numbering calendar year<input type="number" min={1} max={9999} step={1} disabled={busy} value={form.year} onChange={e=>{setForm({...form,year:Number(e.target.value)});setError('');}} required/></label></div>
 {lookupLoading&&<p role="status">Loading effective format…</p>}{effective&&<div className="notice" role="status"><p>Effective format loaded: <b>{effective.prefix} · {effective.padding} digits</b><br/>{effective.inherited?'Inherited registry default':'Published override v'+effective.version}{effective.locked?' · LOCKED: this key has already been initialized.':' · Unused key; changes require independent review.'}</p></div>}
 <div className="form-row"><label>Numbering prefix<input disabled={busy||!effective||effective.locked} value={form.prefix} minLength={2} maxLength={16} onChange={e=>setForm({...form,prefix:e.target.value.toUpperCase()})} required/></label><label>Minimum counter digits<input type="number" min={4} max={12} step={1} disabled={busy||!effective||effective.locked} value={form.padding} onChange={e=>setForm({...form,padding:Number(e.target.value)})} required/></label></div><p className="muted">Example only: {form.prefix}-{form.year}-{'1'.padStart(Math.max(4,Math.min(12,form.padding||6)),'0')} · no number is reserved by this proposal.</p><label>Numbering proposal reason<textarea disabled={busy} value={form.reason} minLength={5} maxLength={500} onChange={e=>setForm({...form,reason:e.target.value})} required/></label></>:review&&<><div className="coa-review"><span className="badge draft">{review.state}</span><h3>{review.prefix} · {review.padding} digits</h3><p>{review.branch_code} · {review.branch_name} · {review.calendar_year}<br/>{review.document_type.replaceAll('_',' ')}<br/>Expected version {review.expected_version}; current version {review.current_version}</p><p><b>Proposed by {review.creator}</b><br/>{new Date(review.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi<br/>{review.reason}</p>{review.reviewed_by&&<p>Reviewed by {review.reviewer}<br/>{new Date(review.reviewed_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi<br/>{review.review_reason}</p>}</div>{canReview?<><label>Numbering review decision<select disabled={busy} value={decision} onChange={e=>setDecision(e.target.value)}><option value="APPROVE">Approve and apply</option><option value="REJECT">Reject without changes</option></select></label><label>Numbering review reason<textarea disabled={busy} value={reviewReason} minLength={5} maxLength={500} onChange={e=>setReviewReason(e.target.value)} required/></label></>:<div className="notice"><ShieldCheck size={18}/><p>{review.created_by===me.id?'You cannot review your own request. Another authorized user must decide.':review.state==='PENDING'?'You have read-only access to this request.':'This decision is final; propose a new version for any correction.'}</p></div>}</>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setDialog(null)}>Close</button>{dialog==='proposal'?<button className="primary" disabled={busy||!effective||effective.locked||!effective.branch.active}>Submit numbering proposal</button>:canReview&&<button className="primary" disabled={busy}>Confirm numbering decision</button>}</div></form></section></div>}
 </div>;
}
