import React,{useEffect,useRef,useState} from 'react';
import {Plus,Package,Search,X} from 'lucide-react';
import {ConfigurationPicker} from './ConfigurationPicker';
import {todayInNairobi} from './view-format';
type Row=Record<string,any>;
type Props={request:(path:string,body?:unknown)=>Promise<any>;permissions:string[];me:Row};
const initial=()=>({sku:'',productCode:'',name:'',description:'',itemType:'STOCK',purchasePrice:'',sellingPrice:'',priceMode:'EXCLUSIVE',validFrom:todayInNairobi(),validTo:'',barcodes:'',reason:''});
export function Products({request,permissions,me}:Props){
 const canPropose=permissions.includes('products:propose'),canApprove=permissions.includes('products:approve'),canCost=permissions.includes('products:cost:view');
 const [view,setView]=useState('catalog'),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[state,setState]=useState('PENDING'),[loading,setLoading]=useState(false),[reload,setReload]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[scan,setScan]=useState('');
 const [dialog,setDialog]=useState<null|'create'|'review'|'detail'>(null),[row,setRow]=useState<Row|null>(null),[form,setForm]=useState(initial),[category,setCategory]=useState<Row|null>(null),[brand,setBrand]=useState<Row|null>(null),[unit,setUnit]=useState<Row|null>(null),[taxCategory,setTaxCategory]=useState<Row|null>(null),[tax,setTax]=useState<Row|null>(null),[taxes,setTaxes]=useState<Row[]>([]),[decision,setDecision]=useState('APPROVE'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 const [preview,setPreview]=useState({date:todayInNairobi(),quantity:'1',discount:'0'}),[result,setResult]=useState<Row|null>(null),modal=useRef<HTMLElement|null>(null),busyRef=useRef(false);busyRef.current=busy;
 const taxable=taxCategory&&['TAXABLE','ZERO_RATED'].includes(taxCategory.classification),reviewable=dialog==='review'&&row?.state==='PENDING'&&row.created_by!==me.id&&canApprove;
 useEffect(()=>{let stopped=false;setLoading(true);setRows([]);setError('');const timer=setTimeout(async()=>{try{const r=await request((view==='catalog'?'/admin/products':'/admin/product-changes')+'?q='+encodeURIComponent(q)+'&page='+page+'&limit=25'+(view==='requests'&&state?'&state='+state:''));if(!stopped){setRows(r.data);setTotal(r.total);}}catch(e){if(!stopped)setError((e as Error).message);}finally{if(!stopped)setLoading(false);}},180);return()=>{stopped=true;clearTimeout(timer);};},[request,view,q,page,state,reload]);
 useEffect(()=>{setResult(null);setError('');},[preview]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null,frame=requestAnimationFrame(()=>modal.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus());const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busyRef.current){setDialog(null);setError('');setResult(null);}}if(e.key==='Tab'){const a=Array.from(modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')??[]).filter(x=>x.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0]?.focus();}}};document.addEventListener('keydown',key,true);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus();else document.getElementById('products-title')?.focus();};},[dialog]);
 function open(kind:'create'|'review'|'detail',r:Row|null=null){setDialog(kind);setRow(r);setForm(initial());setCategory(null);setBrand(null);setUnit(null);setTaxCategory(null);setTax(null);setTaxes([]);setReason('');setDecision('APPROVE');setError('');setNotice('');setResult(null);setPreview({date:todayInNairobi(),quantity:'1',discount:'0'});}
 const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 async function save(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{
  if(dialog==='create'){if(!category||!unit||!taxCategory)throw Error('Select a governed category/base unit and reviewed tax category.');await request('/admin/product-changes',{sku:form.sku,productCode:form.productCode,name:form.name,description:form.description||null,itemType:form.itemType,categoryId:category.id,brandId:brand?.id??null,uomId:unit.id,purchasePrice:form.purchasePrice,sellingPrice:form.sellingPrice,priceMode:form.priceMode,taxCategoryId:taxCategory.id,validFrom:form.validFrom,validTo:form.validTo,taxIds:taxes.map(t=>t.id),barcodes:form.barcodes.split(/\r?\n/).map(b=>b.trim()).filter(Boolean),reason:form.reason});setView('requests');setState('PENDING');setQ(form.sku);setPage(1);setNotice('Proposal saved. No product exists until independent approval; no stock or financial entry was created.');}
  else{if(!reviewable)throw Error('Independent review authority is required.');await request('/admin/product-changes/'+row!.id+'/decide',{decision,reason});setNotice(decision==='APPROVE'?'Product, barcodes and dated tax profile registered atomically. No inventory or journal was posted.':'Product proposal rejected without publication.');}
  setDialog(null);setReload(x=>x+1);
 }catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 async function lookup(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{const r=await request('/admin/products/lookup?barcode='+encodeURIComponent(scan));open('detail',r);}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 async function calculate(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setResult(null);try{setResult(await request('/admin/products/'+row!.id+'/tax-preview',preview));}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const details=(r:Row)=><div className="coa-review"><h3>{r.name}</h3><p>SKU <b>{r.sku}</b> · code {r.product_code} · {r.item_type}</p><p>{r.description}</p><p>Category: {r.category_name}<br/>Brand: {r.brand_name??'None'}<br/>Base unit: {r.uom_code}</p><p>Purchase reference price: <b>{r.purchase_price??'Restricted'}</b><br/>Selling reference price: <b>{r.selling_price}</b> {r.currency}<br/>{r.price_mode} · initial immutable commercial prices, not stock valuation</p><p>Tax category: {r.tax_profile?.category_name??r.tax_category_name} · {r.tax_profile?.classification??r.classification}<br/>Profile: {r.tax_profile?.valid_from??r.valid_from} → {r.tax_profile?.valid_to??r.valid_to}<br/>Taxes: {(r.tax_profile?.tax_names??r.tax_names??[]).join(', ')||'None'}</p><p>Base-unit barcodes:<br/>{r.barcodes?.map((b:any)=>typeof b==='string'?b:b.barcode).join(' · ')||'None'}</p><p>Created by {r.creator}<br/>{new Date(r.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi</p>{r.reviewer&&<p>Reviewed by {r.reviewer}<br/>{r.review_reason}</p>}{r.reason&&<p>Proposal reason: {r.reason}</p>}</div>;
 return <div className="posting-settings"><div className="notice"><Package size={22}/><p><b>Real products, reviewed registration.</b> Publish SKU identity, exact initial prices, base-unit barcodes and a dated tax profile together. Stock balances are never editable here. Stock posting, tracking, alternate units and product/price/profile amendments remain unavailable.</p></div><section className="panel"><div className="panel-title"><div><h2 id="products-title" tabIndex={-1}>Product catalog</h2><p>Immutable registration · exact prices · governed references</p></div>{canPropose&&<button className="primary" onClick={()=>open('create')}><Plus size={16}/>Propose product</button>}</div><div className="coa-toolbar"><div className="coa-views"><button className={view==='catalog'?'primary':'secondary'} onClick={()=>{setView('catalog');setQ('');setPage(1);}}>Published products</button><button className={view==='requests'?'primary':'secondary'} onClick={()=>{setView('requests');setQ('');setPage(1);}}>Product requests</button></div><label className="coa-search"><Search size={16}/><input aria-label="Search products" placeholder="SKU, code, name or barcode…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{view==='requests'&&<label>Product request status<select value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="PENDING">Pending</option><option value="APPLIED">Applied</option><option value="REJECTED">Rejected</option><option value="">All requests</option></select></label>}</div>
 {view==='catalog'&&<form className="product-scan" onSubmit={lookup}><label>Exact barcode lookup<input required maxLength={128} value={scan} disabled={busy} onChange={e=>setScan(e.target.value)} placeholder="Scan or type; leading zeros are retained"/></label><button className="secondary" disabled={busy}>Find barcode</button></form>}
 {error&&!dialog&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}<div className="table-wrap" aria-busy={loading}><table><thead><tr><th>Product / identity</th><th>Commercial price</th><th>Tax profile / status</th><th>Attribution</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-product={view==='catalog'?r.id:undefined} data-product-request={view==='requests'?r.id:undefined}><td><b>{r.name}</b><small>{r.sku} · {r.product_code}</small><small>{r.item_type} · {r.uom_code} · {r.category_name}</small></td><td><b>{r.selling_price} {r.currency}</b><small>{r.price_mode}</small><small>Purchase: {r.purchase_price??'Restricted'}</small></td><td><span className={'badge '+(r.state==='PENDING'?'draft':r.state==='REJECTED'?'rejected':'active')}>{r.state??'REGISTERED'}</span><small>{r.tax_profile?.classification??r.classification}</small><small>{r.tax_profile?.valid_from??r.valid_from} → {r.tax_profile?.valid_to??r.valid_to}</small></td><td><b>{r.creator}</b><small>{r.reviewer?'Reviewed by '+r.reviewer:'Independent review required'}</small></td><td><button className="secondary" onClick={()=>open(view==='catalog'?'detail':'review',r)}>{view==='catalog'?'View product':'Review product request'}</button></td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="empty"><Package/><h3>No matching products</h3><p>Use Product setup and Tax configuration first, then propose an independently reviewed registration.</p></div>}</div><div className="coa-pagination"><span>{loading?'Loading…':total+' results · page '+page+' of '+Math.max(1,Math.ceil(total/25))}</span><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></section>
 {dialog&&<div className="modal-backdrop"><section ref={modal} className="modal editor" role="dialog" aria-modal="true" aria-labelledby="product-dialog-title"><div className="modal-title"><div><span className="eyebrow">CONTROLLED PRODUCT REGISTRATION</span><h2 id="product-dialog-title">{dialog==='create'?'Propose product':dialog==='review'?'Review product request':'Registered product'}</h2></div><button type="button" aria-label="Close product dialog" disabled={busy} onClick={()=>{setDialog(null);setError('');setResult(null);}}><X/></button></div>
 {dialog==='detail'&&row?<><div>{details(row)}</div><form onSubmit={calculate}><h3>Server-price tax preview</h3><p className="muted">Uses the registered selling price and one dated profile. Informational only: not a sale or reservation.</p><div className="form-row">{[['date','Product preview date'],['quantity','Product preview quantity'],['discount','Product preview discount']].map(([key,label])=><label key={key}>{label}<input type={key==='date'?'date':'text'} inputMode={key==='date'?undefined:'decimal'} required value={preview[key as keyof typeof preview]} disabled={busy} onChange={e=>setPreview(p=>({...p,[key]:e.target.value}))}/></label>)}</div><button className="primary" disabled={busy}>Preview product tax</button>{result&&<div className="tax-preview" data-testid="product-tax-result" role="status"><b>{result.calculation.snapshot.input.currency} · {result.calculation.snapshot.priceMode}</b><div className="tax-totals"><p>Net<strong>{result.calculation.net}</strong></p><p>Tax<strong>{result.calculation.tax}</strong></p><p>Gross<strong>{result.calculation.gross}</strong></p></div><small>Dated profile {result.profileId} · No stock or journal effect</small></div>}{error&&<div className="error" role="alert">{error}</div>}</form></>:<form onSubmit={save}>
 {dialog==='create'?<><div className="form-row">{[['sku','SKU'],['productCode','Product code'],['name','Product name']].map(([key,label])=><label key={key}>{label}<input required maxLength={key==='name'?160:64} pattern={key==='name'?undefined:'[A-Z0-9][A-Z0-9._\\x2F\\x2D]{0,63}'} value={form[key as keyof typeof form]} disabled={busy} onChange={e=>update(key,e.target.value)}/></label>)}</div><small>SKU and product codes use uppercase ASCII identities. Barcodes below are case-sensitive text.</small><label>Description<textarea maxLength={1000} value={form.description} disabled={busy} onChange={e=>update('description',e.target.value)}/></label><label>Item type<select value={form.itemType} disabled={busy} onChange={e=>update('itemType',e.target.value)}><option value="STOCK">Stock item</option><option value="SERVICE">Service</option><option value="NON_STOCK">Non-stock item</option></select></label>
 <ConfigurationPicker request={request} path="/admin/product-references?kind=CATEGORY" label="Find product category" value={category} disabled={busy} onChange={setCategory}/><ConfigurationPicker request={request} path="/admin/product-references?kind=UNIT" label="Find base unit" value={unit} disabled={busy} onChange={setUnit}/><ConfigurationPicker request={request} path="/admin/product-references?kind=BRAND" label="Find product brand" value={brand} disabled={busy} onChange={setBrand}/>
 <div className="form-row"><label>Purchase reference price<input inputMode="decimal" required value={form.purchasePrice} disabled={busy} onChange={e=>update('purchasePrice',e.target.value)}/></label><label>Selling reference price<input inputMode="decimal" required value={form.sellingPrice} disabled={busy} onChange={e=>update('sellingPrice',e.target.value)}/></label><label>Product price mode<select value={form.priceMode} disabled={busy||!!(taxCategory&&!taxable)} onChange={e=>update('priceMode',e.target.value)}><option value="EXCLUSIVE">Price excludes tax</option><option value="INCLUSIVE">Price includes tax</option></select></label></div><p className="muted">Exact decimal strings, up to six places, in company functional currency. Initial reference prices are immutable; they do not set inventory valuation or enable sales.</p>
 <ConfigurationPicker request={request} path="/admin/tax-configuration?kind=CATEGORY" label="Find product tax category" value={taxCategory} disabled={busy} onChange={r=>{setTaxCategory(r);setTaxes([]);setTax(null);if(r&&['EXEMPT','NON_TAXABLE'].includes(r.classification))update('priceMode','EXCLUSIVE');}}/>
 {taxable&&<><ConfigurationPicker request={request} path="/admin/tax-configuration?kind=TAX" label="Find assigned tax" value={tax} disabled={busy} onChange={setTax}/><button type="button" className="secondary" disabled={busy||!tax||taxes.length>=10||taxes.some(t=>t.id===tax.id)} onClick={()=>{if(tax)setTaxes(a=>[...a,tax]);setTax(null);}}>Add assigned tax</button>{taxes.map(t=><p key={t.id}>{t.code} · {t.name} <button type="button" className="text-button" disabled={busy} onClick={()=>setTaxes(a=>a.filter(x=>x.id!==t.id))}>Remove {t.code}</button></p>)}</>}
 <div className="form-row"><label>Tax profile from<input type="date" required disabled={busy} value={form.validFrom} onChange={e=>update('validFrom',e.target.value)}/></label><label>Tax profile to<input type="date" required min={form.validFrom} disabled={busy} value={form.validTo} onChange={e=>update('validTo',e.target.value)}/></label></div><p className="muted">Inclusive dates. Every assigned tax must have reviewed compatible schedules covering the entire interval. Only same-base taxes are supported. Profile amendments are not enabled yet.</p><label>Base-unit barcodes<textarea maxLength={2580} value={form.barcodes} disabled={busy} onChange={e=>update('barcodes',e.target.value)}/><small>Optional, one per line, maximum 20. Leading zeros retained. No spaces/control characters or alternate-unit bindings.</small></label><label>Product proposal reason<textarea required minLength={5} maxLength={500} value={form.reason} disabled={busy} onChange={e=>update('reason',e.target.value)}/></label></>:row&&<>{details(row)}{reviewable?<><label>Product review decision<select value={decision} disabled={busy} onChange={e=>setDecision(e.target.value)}><option value="APPROVE">Approve registration</option><option value="REJECT">Reject without publication</option></select></label>{!canCost&&<div className="notice">Purchase-cost visibility is required for approval. You may reject this request without publishing it.</div>}<label>Product review reason<textarea required minLength={5} maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label></>:<div className="notice">{row.created_by===me.id?'You cannot review your own request. Another authorized user must decide.':row.state==='PENDING'?'Read-only request access.':'The decision and published initial values are immutable.'}</div>}</>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setDialog(null);setError('');setResult(null);}}>Close</button>{(dialog==='create'||reviewable)&&<button className="primary" disabled={busy||(dialog==='create'&&(!category||!unit||!taxCategory||!!(taxable&&!taxes.length)))||(dialog==='review'&&decision==='APPROVE'&&!canCost)}>{busy?'Saving…':dialog==='create'?'Submit product proposal':'Confirm product decision'}</button>}</div></form>}
 </section></div>}
 </div>;
}
