import React,{useEffect,useRef,useState} from 'react';
import {Plus,Layers3,X,Search} from 'lucide-react';
import {ConfigurationPicker} from './ConfigurationPicker';
type Row=Record<string,any>;
export function ProductReferences({request,permissions}:{request:(path:string,body?:unknown)=>Promise<any>;permissions:string[]}){
 const canCreate=permissions.includes('products:manage'),[kind,setKind]=useState('UNIT'),[q,setQ]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[reload,setReload]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState(false),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({kind:'UNIT',code:'',name:'',quantityScale:'0',reason:''}),[parent,setParent]=useState<Row|null>(null),modal=useRef<HTMLElement|null>(null),busyRef=useRef(false);busyRef.current=busy;
 useEffect(()=>{let stop=false;setRows([]);setLoading(true);setError('');const timer=setTimeout(async()=>{try{const r=await request('/admin/product-references?kind='+kind+'&q='+encodeURIComponent(q)+'&page='+page+'&limit=25');if(!stop){setRows(r.data);setTotal(r.total);}}catch(e){if(!stop)setError((e as Error).message);}finally{if(!stop)setLoading(false);}},180);return()=>{stop=true;clearTimeout(timer);};},[request,kind,q,page,reload]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null,frame=requestAnimationFrame(()=>modal.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus());const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busyRef.current)setDialog(false);}if(e.key==='Tab'){const a=Array.from(modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')??[]).filter(x=>x.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0]?.focus();}}};document.addEventListener('keydown',key,true);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus();else document.getElementById('product-reference-title')?.focus();};},[dialog]);
 function open(){setForm({kind,code:'',name:'',quantityScale:'0',reason:''});setParent(null);setError('');setNotice('');setDialog(true);}
 async function save(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{await request('/admin/product-references',{kind:form.kind,name:form.name,reason:form.reason,...(form.kind==='BRAND'?{}:{code:form.code}),...(form.kind==='UNIT'?{quantityScale:Number(form.quantityScale)}:form.kind==='CATEGORY'?{parentId:parent?.id??null}:{})});setDialog(false);setKind(form.kind);setQ(form.name);setPage(1);setReload(x=>x+1);setNotice('Reference created with your identity and exact audit. No product, stock, tax or journal was created.');}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const update=(name:string,value:string)=>setForm(f=>({...f,[name]:value}));
 return <div className="posting-settings"><div className="notice"><Layers3 size={22}/><p><b>Prepare product structure, not stock balances.</b> Units, category hierarchy and brands are real, company-scoped reference records. Their precision and relationships are immutable. Use Products for reviewed SKU registration, initial prices and base-unit barcodes. Stock movements and reference lifecycle changes remain unavailable.</p></div><section className="panel"><div className="panel-title"><div><h2 id="product-reference-title" tabIndex={-1}>Product reference masters</h2><p>Units · categories · brands · attributable creation</p></div>{canCreate&&<button className="primary" onClick={open}><Plus size={16}/>New product reference</button>}</div><div className="coa-toolbar"><div className="coa-views">{[['UNIT','Units'],['CATEGORY','Categories'],['BRAND','Brands']].map(([v,label])=><button key={v} className={kind===v?'primary':'secondary'} aria-pressed={kind===v} onClick={()=>{setKind(v);setQ('');setPage(1);setNotice('');}}>{label}</button>)}</div><label className="coa-search"><Search size={16}/><input aria-label="Search product references" placeholder="Code or name…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label></div>
 {error&&!dialog&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}<div className="table-wrap" aria-busy={loading}><table><thead><tr><th>Reference</th><th>Definition</th><th>Created by</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-product-reference={r.id}><td><b>{r.name}</b>{kind!=='BRAND'&&<small>{r.code}</small>}</td><td>{kind==='UNIT'?<>{r.quantity_scale} decimal places<small>Fixed quantity precision</small></>:kind==='CATEGORY'?<>{r.parent_name??'Root category'}<small>Immutable hierarchy · maximum 20 levels</small></>:<>Brand identity<small>Company-scoped name</small></>}</td><td><b>{r.creator}</b><small>{new Date(r.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi</small></td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="empty"><Layers3/><h3>No matching product references</h3><p>Create the units, categories and brands your products will use.</p></div>}</div><div className="coa-pagination"><span>{loading?'Loading…':total+' results · page '+page+' of '+Math.max(1,Math.ceil(total/25))}</span><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></section>
 {dialog&&<div className="modal-backdrop"><section ref={modal} className="modal editor" role="dialog" aria-modal="true" aria-labelledby="product-ref-dialog"><div className="modal-title"><div><span className="eyebrow">PRODUCT CONFIGURATION</span><h2 id="product-ref-dialog">New product reference</h2></div><button type="button" aria-label="Close product reference dialog" disabled={busy} onClick={()=>setDialog(false)}><X/></button></div><form onSubmit={save}><label>Reference kind<select value={form.kind} disabled={busy} onChange={e=>{update('kind',e.target.value);setParent(null);}}><option value="UNIT">Unit of measure</option><option value="CATEGORY">Product category</option><option value="BRAND">Brand</option></select></label><div className="form-row">{form.kind!=='BRAND'&&<label>Reference code<input pattern="[A-Z][A-Z0-9_-]{0,31}" required maxLength={32} disabled={busy} value={form.code} onChange={e=>update('code',e.target.value)}/></label>}<label>Reference name<input minLength={2} maxLength={120} required disabled={busy} value={form.name} onChange={e=>update('name',e.target.value)}/></label></div>{form.kind==='UNIT'&&<label>Quantity decimal places<select disabled={busy} value={form.quantityScale} onChange={e=>update('quantityScale',e.target.value)}>{[0,1,2,3,4,5,6].map(x=><option key={x} value={x}>{x===0?'0 · Whole units':x+' decimal places'}</option>)}</select><small>This precision cannot be changed after creation; do not use it to enter stock quantities.</small></label>}{form.kind==='CATEGORY'&&<><ConfigurationPicker request={request} path="/admin/product-references?kind=CATEGORY" label="Find parent category" value={parent} disabled={busy} onChange={setParent}/><small>{parent?'Child of '+parent.name:'No parent selected: creates a root category.'}</small></>}<label>Reference creation reason<textarea minLength={5} maxLength={500} required disabled={busy} value={form.reason} onChange={e=>update('reason',e.target.value)}/></label><div className="notice">Creates immutable metadata with an audit record. No stock or financial effect. Corrections/lifecycle changes require a later controlled workflow.</div>{error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setDialog(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create product reference'}</button></div></form></section></div>}
 </div>;
}
