import React,{useEffect,useRef,useState} from 'react';
import {Plus,ShieldCheck,X,Search} from 'lucide-react';
import {ConfigurationPicker} from './ConfigurationPicker';
import {todayInNairobi} from './view-format';
type Row=Record<string,any>;
type Props={request:(path:string,body?:unknown)=>Promise<any>;permissions:string[];me:Row};
const initial=()=>({kind:'TAX',code:'',name:'',taxType:'VAT',classification:'TAXABLE',validFrom:todayInNairobi(),validTo:'',rate:'',inclusive:false,recoverableFraction:'',basis:'',reason:''});
export function TaxSettings({request,permissions,me}:Props){
 const canPropose=permissions.includes('taxes:propose'),canApprove=permissions.includes('taxes:approve');
 const [view,setView]=useState('TAX'),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[state,setState]=useState('PENDING'),[reload,setReload]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [dialog,setDialog]=useState<null|'create'|'review'>(null),[row,setRow]=useState<Row|null>(null),[form,setForm]=useState(initial),[tax,setTax]=useState<Row|null>(null),[category,setCategory]=useState<Row|null>(null),[input,setInput]=useState<Row|null>(null),[output,setOutput]=useState<Row|null>(null),[reason,setReason]=useState(''),[decision,setDecision]=useState('APPROVE'),[busy,setBusy]=useState(false);
 const modal=useRef<HTMLElement|null>(null),busyRef=useRef(false);busyRef.current=busy;
 const [previewCategory,setPreviewCategory]=useState<Row|null>(null),[previewTax,setPreviewTax]=useState<Row|null>(null),[previewTaxes,setPreviewTaxes]=useState<Row[]>([]),[preview,setPreview]=useState({date:todayInNairobi(),quantity:'1',unitPrice:'',discount:'0'}),[result,setResult]=useState<Row|null>(null);
 const reviewable=dialog==='review'&&row?.state==='PENDING'&&row.created_by!==me.id&&canApprove;
 const update=(name:string,value:any)=>setForm(f=>({...f,[name]:value}));
 useEffect(()=>{if(view==='preview')return;let cancelled=false;setLoading(true);setRows([]);setError('');const timer=setTimeout(async()=>{try{const path=view==='requests'?'/admin/tax-changes?':'/admin/tax-configuration?kind='+view+'&';const r=await request(path+'q='+encodeURIComponent(q)+'&page='+page+'&limit=25'+(view==='requests'&&state?'&state='+state:''));if(!cancelled){setRows(r.data);setTotal(r.total);}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[request,view,q,page,state,reload]);
 useEffect(()=>{setResult(null);setError('');},[previewCategory,previewTaxes,preview]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null,frame=requestAnimationFrame(()=>modal.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus());const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busyRef.current)setDialog(null);}if(e.key==='Tab'){const a=Array.from(modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')??[]).filter(x=>x.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0]?.focus();}}};document.addEventListener('keydown',key,true);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus();else document.getElementById('tax-title')?.focus();};},[dialog]);
 function switchView(v:string){setView(v);setQ('');setPage(1);setError('');setNotice('');}
 function open(kind:'create'|'review',r:Row|null=null){setDialog(kind);setRow(r);setForm(initial());setTax(null);setCategory(null);setInput(null);setOutput(null);setReason('');setDecision('APPROVE');setError('');setNotice('');}
 async function save(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{
  if(dialog==='create'){
   const common={kind:form.kind,basis:form.basis,reason:form.reason};let body:Row;
   if(form.kind==='RATE'){if(!tax||!category||!input||!output)throw Error('Choose reviewed masters and both eligible tax accounts.');body={...common,taxId:tax.id,categoryId:category.id,inputAccountId:input.id,outputAccountId:output.id,validFrom:form.validFrom,validTo:form.validTo,rate:form.rate,inclusive:form.inclusive,recoverableFraction:form.recoverableFraction};}
   else body={...common,code:form.code,name:form.name,...(form.kind==='TAX'?{taxType:form.taxType}:{classification:form.classification})};
   await request('/admin/tax-changes',body);setView('requests');setState('PENDING');setQ(form.reason);setPage(1);setNotice('Proposal saved. Independent review is required; no financial effect.');
  }else{if(!reviewable)throw Error('Independent review authority is required.');await request('/admin/tax-changes/'+row!.id+'/decide',{decision,reason});setNotice(decision==='APPROVE'?'Reviewed configuration published. No transaction or tax return was posted.':'Request rejected without publishing configuration.');}
  setDialog(null);setReload(x=>x+1);
 }catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 async function calculate(e:React.FormEvent){e.preventDefault();if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setResult(null);try{if(!previewCategory)throw Error('Choose a reviewed category.');setResult(await request('/admin/tax-preview',{...preview,categoryId:previewCategory.id,taxIds:previewTaxes.map(t=>t.id)}));}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const details=(r:Row)=><>{r.kind==='RATE'||r.tax_id?<><b>{r.tax_code??r.tax_id} / {r.category_code??r.category_id}</b><small>{r.valid_from} → {r.valid_to} · inclusive ends</small><small>Factor {r.rate} · {r.inclusive?'Price inclusive':'Price exclusive'} · recoverable {r.recoverable_fraction}</small><small>Input {r.input_code??r.input_account_id} {r.input_name}<br/>Output {r.output_code??r.output_account_id} {r.output_name}</small></>:<><b>{r.code} · {r.name}</b><small>{r.tax_type??r.classification}</small></>}</>;
 return <div className="posting-settings"><div className="notice"><ShieldCheck size={22}/><p><b>Reviewed configuration, not a tax return.</b> No statutory schedule is activated automatically. Rates require explicit finite dates and independent review. Published values are immutable; retirement/amendment and operational tax posting are not yet enabled. Documentary basis is retained, not independently certified by this application.</p></div>
 <section className="panel"><div className="panel-title"><div><h2 id="tax-title" tabIndex={-1}>Tax configuration controls</h2><p>Classified categories · exact factors · effective schedules · immutable review history</p></div>{canPropose&&<button className="primary" onClick={()=>open('create')}><Plus size={16}/>Propose tax configuration</button>}</div>
 <div className="control-tabs">{[['TAX','Tax definitions'],['CATEGORY','Tax categories'],['RATE','Rate schedules'],['requests','Tax requests'],['preview','Calculation preview']].map(([v,label])=><button key={v} className={view===v?'selected':''} aria-pressed={view===v} onClick={()=>switchView(v)}>{label}</button>)}</div>
 {view!=='preview'&&<div className="coa-toolbar"><label className="coa-search"><Search size={16}/><input aria-label="Search tax configuration" placeholder="Code, name or request reason…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{view==='requests'&&<label>Tax request status<select value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="PENDING">Pending review</option><option value="APPLIED">Applied</option><option value="REJECTED">Rejected</option><option value="">All requests</option></select></label>}</div>}
 {error&&!dialog&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {view==='preview'?<form className="posting-lookup" onSubmit={calculate}>
 <ConfigurationPicker request={request} path="/admin/tax-configuration?kind=CATEGORY" label="Find preview category" value={previewCategory} disabled={busy} onChange={r=>{setPreviewCategory(r);setPreviewTaxes([]);setPreviewTax(null);}}/>
 <p className="muted">Choose every tax to preview explicitly. All selected taxes use the same net base; compound and fixed-unit taxes are unsupported. Exempt/non-taxable categories require no taxes. Product assignment and operational authority are not implied.</p>
 <ConfigurationPicker request={request} path="/admin/tax-configuration?kind=TAX" label="Find preview tax" value={previewTax} disabled={busy} onChange={setPreviewTax}/><button type="button" className="secondary" disabled={busy||!previewTax||previewTaxes.length>=10||previewTaxes.some(t=>t.id===previewTax.id)} onClick={()=>{if(previewTax)setPreviewTaxes(t=>[...t,previewTax]);setPreviewTax(null);}}>Add preview tax</button>
 <div>{previewTaxes.map(t=><p key={t.id}>{t.code} · {t.name} <button type="button" className="text-button" disabled={busy} onClick={()=>setPreviewTaxes(a=>a.filter(x=>x.id!==t.id))}>Remove {t.code}</button></p>)}</div>
 <div className="form-row">{[['date','Business date'],['quantity','Quantity'],['unitPrice','Unit price'],['discount','Discount']].map(([key,label])=><label key={key}>{label}<input type={key==='date'?'date':'text'} inputMode={key==='date'?undefined:'decimal'} value={preview[key as keyof typeof preview]} required disabled={busy} onChange={e=>setPreview(p=>({...p,[key]:e.target.value}))}/></label>)}</div><button className="primary" disabled={busy||!previewCategory}>Calculate tax preview</button>
 {result&&<div className="tax-preview" role="status"><h3>Informational calculation · {result.calculation.snapshot.input.currency}</h3><div className="tax-totals"><p>Net<strong>{result.calculation.net}</strong></p><p>Tax<strong data-testid="tax-preview-total">{result.calculation.tax}</strong></p><p>Gross<strong data-testid="tax-preview-gross">{result.calculation.gross}</strong></p></div>{result.calculation.components.map((r:Row)=><p key={r.rateId}>Rate {r.rateId}<br/>Recoverable {r.recoverable} · Nonrecoverable {r.nonrecoverable}</p>)}<small>{result.calculation.snapshot.input.classification} · {result.calculation.snapshot.priceMode} · No posted tax, journal or stock effect.</small></div>}
 </form>:<><div className="table-wrap" aria-busy={loading}><table><thead><tr><th>Definition / schedule</th><th>Basis / state</th><th>Attribution</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-tax-request={view==='requests'?r.id:undefined} data-tax-record={view!=='requests'?r.id:undefined}><td>{details(r)}</td><td><span className={'badge '+(r.state==='PENDING'?'draft':r.state==='REJECTED'?'rejected':'active')}>{r.state??'PUBLISHED'}</span><small>{r.basis}</small>{r.reason&&<small>{r.reason}</small>}</td><td><b>{r.creator}</b><small>{r.reviewer?'Reviewed by '+r.reviewer:'Independent review required'}</small></td><td>{view==='requests'&&<button className="secondary" onClick={()=>open('review',r)}>{canApprove&&r.state==='PENDING'?'Review tax request':'View tax request'}</button>}</td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="empty"><ShieldCheck/><h3>No matching tax configuration</h3><p>Propose reviewed masters first, then explicit finite schedules. No active rates are supplied by default.</p></div>}</div><div className="coa-pagination"><span>{loading?'Loading…':total+' results · page '+page+' of '+Math.max(1,Math.ceil(total/25))}</span><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></>}
 </section>
 {dialog&&<div className="modal-backdrop"><section ref={modal} className="modal editor" role="dialog" aria-modal="true" aria-labelledby="tax-dialog-title"><div className="modal-title"><div><span className="eyebrow">CONTROLLED TAX CONFIGURATION</span><h2 id="tax-dialog-title">{dialog==='create'?'Propose tax configuration':'Review tax request'}</h2></div><button type="button" disabled={busy} aria-label="Close tax dialog" onClick={()=>setDialog(null)}><X/></button></div><form onSubmit={save}>
 {dialog==='create'?<><label>Configuration kind<select value={form.kind} disabled={busy} onChange={e=>update('kind',e.target.value)}><option value="TAX">Tax definition</option><option value="CATEGORY">Tax category</option><option value="RATE">Effective rate schedule</option></select></label>
 {form.kind!=='RATE'?<><div className="form-row"><label>Configuration code<input pattern="[A-Z][A-Z0-9_]{1,31}" required maxLength={32} value={form.code} disabled={busy} onChange={e=>update('code',e.target.value)}/></label><label>Configuration name<input minLength={2} maxLength={120} required value={form.name} disabled={busy} onChange={e=>update('name',e.target.value)}/></label></div>{form.kind==='TAX'?<label>Tax type<select value={form.taxType} disabled={busy} onChange={e=>update('taxType',e.target.value)}>{['VAT','EXCISE','LEVY','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label>:<label>Category classification<select value={form.classification} disabled={busy} onChange={e=>update('classification',e.target.value)}>{['TAXABLE','ZERO_RATED','EXEMPT','NON_TAXABLE'].map(x=><option key={x}>{x}</option>)}</select></label>}</>:<>
 <ConfigurationPicker request={request} path="/admin/tax-configuration?kind=TAX" label="Find tax definition" value={tax} disabled={busy} onChange={setTax}/><ConfigurationPicker request={request} path="/admin/tax-configuration?kind=CATEGORY" label="Find tax category" value={category} disabled={busy} onChange={setCategory}/>
 <div className="form-row"><label>Effective from<input type="date" required value={form.validFrom} disabled={busy} onChange={e=>update('validFrom',e.target.value)}/></label><label>Effective to<input type="date" required min={form.validFrom} value={form.validTo} disabled={busy} onChange={e=>update('validTo',e.target.value)}/></label></div><p className="muted">End dates are inclusive. Overlaps are refused. Published schedules cannot yet be shortened or amended; choose the documented finite coverage deliberately.</p>
 <div className="form-row"><label>Rate factor<input inputMode="decimal" required value={form.rate} disabled={busy} onChange={e=>update('rate',e.target.value)}/><small>Exact fractional factor. 1 means 100%; no statutory default.</small></label><label>Recoverable fraction<input inputMode="decimal" required value={form.recoverableFraction} disabled={busy} onChange={e=>update('recoverableFraction',e.target.value)}/><small>Between 0 and 1. Operational eligibility still requires supporting documents.</small></label><label>Price mode<select value={form.inclusive?'INCLUSIVE':'EXCLUSIVE'} disabled={busy} onChange={e=>update('inclusive',e.target.value==='INCLUSIVE')}><option value="EXCLUSIVE">Price excludes tax</option><option value="INCLUSIVE">Price includes tax</option></select></label></div>
 <ConfigurationPicker request={request} path="/admin/tax-accounts?direction=INPUT" label="Find input tax account" value={input} disabled={busy} onChange={setInput}/><ConfigurationPicker request={request} path="/admin/tax-accounts?direction=OUTPUT" label="Find output tax account" value={output} disabled={busy} onChange={setOutput}/></>}
 <label>Documentary basis<textarea minLength={5} maxLength={1000} required value={form.basis} disabled={busy} onChange={e=>update('basis',e.target.value)}/></label><label>Tax proposal reason<textarea minLength={5} maxLength={500} required value={form.reason} disabled={busy} onChange={e=>update('reason',e.target.value)}/></label></>:row&&<><div className="coa-review">{details(row)}<p><b>Basis:</b> {row.basis}</p><p><b>Proposed by {row.creator}</b><br/>{row.reason}<br/>{new Date(row.created_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · Africa/Nairobi</p>{row.reviewed_at&&<p>Reviewed by {row.reviewer}<br/>{row.review_reason}</p>}</div>{reviewable?<><label>Tax review decision<select value={decision} disabled={busy} onChange={e=>setDecision(e.target.value)}><option value="APPROVE">Approve and publish</option><option value="REJECT">Reject without publication</option></select></label><label>Tax review reason<textarea minLength={5} maxLength={500} required value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label></>:<div className="notice">{row.created_by===me.id?'You cannot review your own request. Another authorized user must decide.':row.state==='PENDING'?'Read-only access to this request.':'This decision is immutable.'}</div>}</>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setDialog(null)}>Close</button>{(dialog==='create'||reviewable)&&<button className="primary" disabled={busy||(dialog==='create'&&form.kind==='RATE'&&(!tax||!category||!input||!output))}>{busy?'Saving…':dialog==='create'?'Submit tax proposal':'Confirm tax decision'}</button>}</div>
 </form></section></div>}
 </div>;
}
