import {CustomerAmendmentService} from './customer-amendments';
import {Inject,Injectable,Controller,Get,Post,Req,Body,Param} from '@nestjs/common';
import {Request} from 'express';
import {z} from 'zod';
import {PoolClient} from 'pg';
import {AuthService} from './auth';
import {Db,Context,BusinessError} from './db';
import {CommandService} from './commands';
const uuid=z.string().uuid(),reason=z.string().trim().min(5).max(500),optional=(min:number,max:number)=>z.string().trim().min(min).max(max).nullable().default(null);
const proposal=z.object({number:z.string().regex(/^[A-Z][A-Z0-9_-]{0,31}$/),name:z.string().trim().min(2).max(160),phone:optional(3,40),email:z.string().trim().email().max(254).nullable().default(null),address:optional(2,1000),taxPin:z.string().regex(/^[A-Z][0-9]{9}[A-Z]$/).nullable().default(null),customerType:z.enum(['REGISTERED','WALK_IN']),creditLimit:z.string().regex(/^(0|[1-9]\d{0,15})(\.\d{1,2})?$/),paymentTermsDays:z.number().int().min(0).max(3650),controlAccountId:uuid.nullable(),taxCategoryId:uuid.nullable().default(null),reason}).strict().superRefine((v,c)=>{if(v.customerType==='WALK_IN'&&(v.controlAccountId!==null||!/^0(?:\.0{1,2})?$/.test(v.creditLimit)||v.paymentTermsDays!==0||v.phone||v.email||v.address||v.taxPin))c.addIssue({code:'custom',message:'Walk-in requires zero credit/terms, no AR binding and no personal identity.'});if(v.customerType==='REGISTERED'&&!v.controlAccountId)c.addIssue({code:'custom',message:'Registered customer requires an explicit AR-control binding.'});});
const paging=z.object({q:z.string().max(100).default(''),page:z.coerce.number().int().min(1).max(10000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict();
@Injectable()
export class CustomerService{
 constructor(@Inject(Db) private db:Db,@Inject(CommandService) private commands:CommandService){}
 async list(ctx:Context,query:unknown,changes=false){const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const table=changes?'customer_change_requests':'customers',where=`r.company_id=$1 ${changes?'':'AND r.publication_request_id IS NOT NULL'} AND (r.number ILIKE $2 OR r.name ILIKE $2)`,args=[ctx.companyId,'%'+v.q+'%'];return {data:(await c.query(`SELECT r.*,r.credit_limit::text,u.display_name AS creator FROM ${table} r JOIN users u ON u.id=r.created_by WHERE ${where} ORDER BY r.created_at DESC,r.id LIMIT $3 OFFSET $4`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM ${table} r WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};});}
 async detail(ctx:Context,id:string){uuid.parse(id);return this.db.transaction(ctx,async c=>{const r=(await c.query(`SELECT c.*,c.credit_limit::text,u.display_name AS creator,ap.display_name AS approver,a.control_account_id,ac.code AS account_code,ac.name AS account_name FROM customers c JOIN users u ON u.id=c.created_by JOIN users ap ON ap.id=c.approved_by LEFT JOIN customer_accounts a ON a.customer_id=c.id LEFT JOIN accounts ac ON ac.id=a.control_account_id WHERE c.company_id=$1 AND c.id=$2 AND c.publication_request_id IS NOT NULL`,[ctx.companyId,id])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','Customer is not available in this company.',404);return r;});}
 async options(ctx:Context,query:unknown,tax=false){const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const table=tax?'tax_categories':'accounts',where=`a.company_id=$1 AND ${tax?'a.publication_request_id IS NOT NULL':"a.active AND a.postable AND a.account_type='ASSET' AND a.control_type='AR' AND NOT EXISTS(SELECT 1 FROM accounts ch WHERE ch.company_id=a.company_id AND ch.parent_id=a.id)"} AND (a.code ILIKE $2 OR a.name ILIKE $2)`,args=[ctx.companyId,'%'+v.q+'%'];return {data:(await c.query(`SELECT a.id,a.code,a.name FROM ${table} a WHERE ${where} ORDER BY a.code,a.id LIMIT $3 OFFSET $4`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM ${table} a WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};});}
 async audit(c:PoolClient,ctx:Context,id:string,action:string,why:string,before:string|null){await c.query(`INSERT INTO audit_logs(company_id,actor_id,action,module,entity_type,entity_id,request_id,session_id,ip,device,new_values,reason) VALUES($1,$2,$3,'CORE','CUSTOMER_CONFIGURATION',$4,$5,$6,$7,$8,jsonb_build_object('before',$9::jsonb,'after',customer_request_snapshot($4),'published',customer_publication_snapshot($4)),$10)`,[ctx.companyId,ctx.userId,action,id,ctx.requestId,ctx.sessionId,ctx.ip,ctx.device,before,why]);}
 async propose(ctx:Context,key:string|undefined,body:unknown){const v=proposal.parse(body);return this.commands.run(ctx,key,'customer.propose',v,async c=>{const currency=(await c.query('SELECT base_currency FROM companies WHERE id=$1',[ctx.companyId])).rows[0].base_currency;
  const r=(await c.query(`INSERT INTO customer_change_requests(company_id,created_by,number,name,phone,email,address,tax_pin,customer_type,credit_limit,payment_terms_days,currency,control_account_id,tax_category_id,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id,state`,[ctx.companyId,ctx.userId,v.number,v.name,v.phone,v.email,v.address,v.taxPin,v.customerType,v.creditLimit,v.paymentTermsDays,currency,v.controlAccountId,v.taxCategoryId,v.reason])).rows[0];await c.query('SELECT assert_customer_request($1)',[r.id]);await this.audit(c,ctx,r.id,'CUSTOMER_CHANGE_PROPOSE',v.reason,null);return r;
 },true);}
 async decide(ctx:Context,key:string|undefined,id:string,body:unknown){uuid.parse(id);const v=z.object({decision:z.enum(['APPROVE','REJECT']),reason}).strict().parse(body);return this.commands.run(ctx,key,'customer.decide.'+id,v,async c=>{
  const r=(await c.query('SELECT r.*,customer_request_snapshot(r.id)::text AS before FROM customer_change_requests r WHERE company_id=$1 AND id=$2 FOR UPDATE',[ctx.companyId,id])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','Customer request unavailable.',404);if(r.state!=='PENDING')throw new BusinessError('STATE_CONFLICT','Customer request already decided.',409);if(r.created_by===ctx.userId)throw new BusinessError('INDEPENDENT_REVIEW','Another authorized person must decide.',403);
  const state=v.decision==='APPROVE'?'APPLIED':'REJECTED';await c.query('UPDATE customer_change_requests SET state=$2,reviewed_by=$3,reviewed_at=now(),review_reason=$4 WHERE id=$1',[id,state,ctx.userId,v.reason]);
  if(state==='APPLIED'){
   await c.query(`INSERT INTO customers(id,company_id,created_by,number,name,phone,email,address,tax_pin,payment_terms_days,currency,customer_type,credit_limit,tax_category_id,publication_request_id,approved_by,approved_at,version) SELECT new_customer_id,company_id,created_by,number,name,phone,email,address,tax_pin,payment_terms_days,currency,customer_type,credit_limit,tax_category_id,id,reviewed_by,reviewed_at,1 FROM customer_change_requests WHERE id=$1`,[id]);
   await c.query(`INSERT INTO customer_accounts(id,company_id,created_by,customer_id,control_account_id) SELECT new_account_id,company_id,created_by,new_customer_id,control_account_id FROM customer_change_requests WHERE id=$1 AND customer_type='REGISTERED'`,[id]);
  }
  await this.audit(c,ctx,id,'CUSTOMER_CHANGE_'+v.decision,v.reason,r.before);return {id,state,customerId:state==='APPLIED'?r.new_customer_id:null};
 },true);}
}
@Controller('api/v1/customers')
export class CustomerController{
 constructor(@Inject(CustomerAmendmentService) private amendments:CustomerAmendmentService,@Inject(AuthService) private auth:AuthService,@Inject(CustomerService) private customers:CustomerService){}
 @Get() list(@Req() req:Request){return this.auth.context(req,'customers:view').then(c=>this.customers.list(c,req.query));}
 @Get('changes') changes(@Req() req:Request){return this.auth.context(req,'customers:view').then(c=>this.customers.list(c,req.query,true));}
 @Get('accounts') accounts(@Req() req:Request){return this.auth.context(req,'customers:view').then(c=>this.customers.options(c,req.query));}
 @Get('tax-categories') taxes(@Req() req:Request){return this.auth.context(req,'customers:view').then(c=>this.customers.options(c,req.query,true));}
 @Get(':id/amendments') history(@Req() req:Request,@Param('id') id:string){return this.auth.context(req,'customers:view').then(c=>this.amendments.list(c,id,req.query));}
 @Post(':id/amendments') amend(@Req() req:Request,@Param('id') id:string,@Body() body:unknown){return this.auth.context(req,'customers:amend:propose',true).then(c=>this.amendments.propose(c,req.header('Idempotency-Key'),id,body));}
 @Post('amendments/:id/decide') reviewAmendment(@Req() req:Request,@Param('id') id:string,@Body() body:unknown){return this.auth.context(req,'customers:amend:approve',true).then(c=>this.amendments.decide(c,req.header('Idempotency-Key'),id,body));}
 @Get(':id') detail(@Req() req:Request,@Param('id') id:string){return this.auth.context(req,'customers:view').then(c=>this.customers.detail(c,id));}
 @Post('changes') propose(@Req() req:Request,@Body() body:unknown){return this.auth.context(req,'customers:propose',true).then(c=>this.customers.propose(c,req.header('Idempotency-Key'),body));}
 @Post('changes/:id/decide') decide(@Req() req:Request,@Param('id') id:string,@Body() body:unknown){return this.auth.context(req,'customers:approve',true).then(c=>this.customers.decide(c,req.header('Idempotency-Key'),id,body));}
}
