import {reverseValuedMovement} from './inventory-reversal';
import {Inject,Injectable} from '@nestjs/common';
import {z} from 'zod';
import Decimal from 'decimal.js';
import {PoolClient} from 'pg';
import {Db,Context,BusinessError,event} from './db';
import {CommandService} from './commands';
import {AccountingService} from './accounting';
import {WorkflowService} from './workflow';
import {PostingRuleConfigurationService} from './posting-rule-configuration';
import {materializePostingLines} from './posting-line-materializer';
import {valueInventoryMovement} from './inventory-valuation';
import {allocateDocumentNumber} from './numbering';
const uuid=z.string().uuid(),reason=z.string().trim().min(5).max(500),quantity=z.string().regex(/^(0|[1-9]\d{0,13})(\.\d{1,6})?$/).refine(v=>new Decimal(v).gt(0)),value=z.string().regex(/^(0|[1-9]\d{0,15})(\.\d{1,2})?$/).refine(v=>new Decimal(v).gt(0));
const date=z.string().regex(/^(?!0000)\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=Date.parse(v+'T00:00:00Z');return Number.isFinite(d)&&new Date(d).toISOString().slice(0,10)===v;});
const fields={warehouseId:uuid,productId:uuid,quantity,date,reason};
const draft=z.discriminatedUnion('kind',[z.object({...fields,kind:z.literal('STOCK_GAIN'),value}).strict(),z.object({...fields,kind:z.literal('STOCK_LOSS')}).strict()]);
const transition=z.object({expectedRevision:z.number().int().positive(),reason}).strict(),paging=z.object({q:z.string().max(100).default(''),page:z.coerce.number().int().min(1).max(10000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict();
@Injectable()
export class InventoryAdjustmentService{
 constructor(@Inject(Db) private db:Db,@Inject(CommandService) private commands:CommandService,@Inject(AccountingService) private accounting:AccountingService,@Inject(WorkflowService) private workflow:WorkflowService,@Inject(PostingRuleConfigurationService) private rules:PostingRuleConfigurationService){}
 access(ctx:Context){if(!ctx.permissions.includes('inventory:cost:view'))throw new BusinessError('STOCK_COST_ACCESS','Valued stock workflows require inventory:cost:view.',403);}
 async audit(c:PoolClient,ctx:Context,id:string,action:string,why:string){await c.query(`INSERT INTO audit_logs(company_id,actor_id,action,module,entity_type,entity_id,source_id,request_id,session_id,ip,device,new_values,reason) SELECT $1,$2,$3,'CORE','INVENTORY_SOURCE',$4,$4,$5,$6,$7,$8,stock_source_snapshot($4),$9`,[ctx.companyId,ctx.userId,action,id,ctx.requestId,ctx.sessionId,ctx.ip,ctx.device,why]);}
 async list(ctx:Context,query:unknown){this.access(ctx);const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const args=[ctx.companyId,ctx.branches,'%'+v.q+'%'],where="s.company_id=$1 AND s.branch_id=ANY($2::uuid[]) AND (s.document_number ILIKE $3 OR s.description ILIKE $3 OR p.sku ILIKE $3 OR p.name ILIKE $3)";return {data:(await c.query(`SELECT s.id,s.document_number,s.document_type,s.business_date,s.status,s.revision,s.created_by,s.approved_by,s.posted_by,s.description,s.currency,p.name,p.sku,w.name AS warehouse_name,l.quantity::text,l.gain_value::text,u.display_name AS creator FROM source_documents s JOIN inventory_adjustment_lines l ON l.source_id=s.id JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=l.warehouse_id JOIN users u ON u.id=s.created_by WHERE ${where} ORDER BY s.created_at DESC,s.id LIMIT $4 OFFSET $5`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM source_documents s JOIN inventory_adjustment_lines l ON l.source_id=s.id JOIN products p ON p.id=l.product_id WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};});}
 async detail(ctx:Context,id:string){this.access(ctx);uuid.parse(id);return this.db.transaction(ctx,async c=>{const r=(await c.query(`SELECT stock_source_snapshot(s.id) AS document,p.name,p.sku,w.name AS warehouse_name,u.display_name AS creator,a.display_name AS approver,po.display_name AS poster FROM source_documents s JOIN inventory_adjustment_lines l ON l.source_id=s.id JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=l.warehouse_id JOIN users u ON u.id=s.created_by LEFT JOIN users a ON a.id=s.approved_by LEFT JOIN users po ON po.id=s.posted_by WHERE s.company_id=$1 AND s.id=$2 AND s.branch_id=ANY($3::uuid[])`,[ctx.companyId,id,ctx.branches])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','Stock source not found.',404);return {...r,approvals:(await c.query('SELECT revision,step_no,decision,created_by FROM approval_decisions WHERE company_id=$1 AND source_id=$2 ORDER BY created_at,id',[ctx.companyId,id])).rows,journalLines:(await c.query('SELECT l.debit::text,l.credit::text,l.description,a.code,a.name FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_id JOIN accounts a ON a.id=l.account_id WHERE l.company_id=$1 AND j.source_id=$2 ORDER BY l.line_no',[ctx.companyId,id])).rows,journal:(await c.query('SELECT id,number,status FROM journal_entries WHERE company_id=$1 AND source_id=$2',[ctx.companyId,id])).rows[0]??null,movements:(await c.query('SELECT id,quantity::text,base_value::text,unit_cost::text,pool_version::text FROM inventory_movements WHERE company_id=$1 AND source_id=$2',[ctx.companyId,id])).rows,events:(await c.query('SELECT e.action,e.revision,e.created_at,u.display_name AS actor,e.reason FROM document_events e JOIN users u ON u.id=e.actor_id WHERE e.company_id=$1 AND e.source_id=$2 ORDER BY e.created_at,e.id',[ctx.companyId,id])).rows};});}
 async productOptions(ctx:Context,query:unknown){this.access(ctx);const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const a=[ctx.companyId,'%'+v.q+'%'],w="p.company_id=$1 AND p.publication_request_id IS NOT NULL AND p.active AND p.item_type='STOCK' AND NOT p.serialized AND NOT p.batch_controlled AND NOT p.expiry_controlled AND (p.sku ILIKE $2 OR p.name ILIKE $2)";return {data:(await c.query(`SELECT p.id,p.sku AS code,p.name,u.code AS unit,u.quantity_scale FROM products p JOIN units_of_measure u ON u.id=p.uom_id WHERE ${w} ORDER BY p.name,p.id LIMIT $3 OFFSET $4`,[...a,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM products p WHERE ${w}`,a)).rows[0].n,page:v.page,limit:v.limit};});}
 async warehouseOptions(ctx:Context,query:unknown){this.access(ctx);const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const a=[ctx.companyId,ctx.branches,'%'+v.q+'%'],w="company_id=$1 AND branch_id=ANY($2::uuid[]) AND active AND location_type='SELLABLE' AND (code ILIKE $3 OR name ILIKE $3)";return {data:(await c.query(`SELECT id,code,name,branch_id FROM warehouses WHERE ${w} ORDER BY name,id LIMIT $4 OFFSET $5`,[...a,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM warehouses WHERE ${w}`,a)).rows[0].n,page:v.page,limit:v.limit};});}
 async balances(ctx:Context,query:unknown){this.access(ctx);const v=paging.parse(query);return this.db.transaction(ctx,async c=>{const args=[ctx.companyId,ctx.branches,'%'+v.q+'%'],from='inventory_balances b JOIN warehouses w ON w.company_id=b.company_id AND w.id=b.warehouse_id JOIN products p ON p.company_id=b.company_id AND p.id=b.product_id',where='b.company_id=$1 AND w.branch_id=ANY($2::uuid[]) AND (p.name ILIKE $3 OR p.sku ILIKE $3 OR w.name ILIKE $3)';return {data:(await c.query(`SELECT b.id,b.warehouse_id,b.product_id,p.name,p.sku,w.name AS warehouse_name,b.quantity::text,b.base_value::text,b.version::text,b.last_valued_date FROM ${from} WHERE ${where} ORDER BY p.name,w.name,b.id LIMIT $4 OFFSET $5`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM ${from} WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};});}
 async create(ctx:Context,key:string|undefined,body:unknown){const v=draft.parse(body);return this.commands.run(ctx,key,'stock.create',v,async c=>{this.access(ctx);const w=(await c.query("SELECT branch_id FROM warehouses WHERE company_id=$1 AND id=$2 AND active AND location_type='SELLABLE'",[ctx.companyId,v.warehouseId])).rows[0];if(!w||!ctx.branches.includes(w.branch_id))throw new BusinessError('STOCK_SCOPE','Choose an active assigned sellable warehouse.',403);
  const currency=(await c.query('SELECT base_currency FROM companies WHERE id=$1',[ctx.companyId])).rows[0].base_currency,number=await allocateDocumentNumber(c,ctx,w.branch_id,v.kind,v.date);
  const s=(await c.query(`INSERT INTO source_documents(company_id,branch_id,document_type,document_number,business_date,currency,description,created_by,initiated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id,status,revision,document_number`,[ctx.companyId,w.branch_id,v.kind,number,v.date,currency,v.reason,ctx.userId])).rows[0];
  await c.query('INSERT INTO inventory_adjustment_lines(company_id,source_id,warehouse_id,product_id,quantity,gain_value,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[ctx.companyId,s.id,v.warehouseId,v.productId,v.quantity,v.kind==='STOCK_GAIN'?v.value:null,ctx.userId]);await c.query('SELECT stock_identity($1)',[s.id]);await event(c,ctx,s.id,'CREATE',null,'DRAFT',1,v.reason);await this.audit(c,ctx,s.id,'CREATE',v.reason);return s;
 });}
 async reverse(ctx:Context,key:string|undefined,id:string,body:unknown){uuid.parse(id);const v=z.object({date,reason}).strict().parse(body);return this.commands.run(ctx,key,'stock.reverse.'+id,v,async c=>{this.access(ctx);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,92))',[ctx.companyId+id]);const original=(await c.query("SELECT s.*,m.id AS movement_id,m.warehouse_id,m.product_id,abs(m.quantity)::text AS quantity FROM source_documents s JOIN inventory_movements m ON m.source_id=s.id WHERE s.company_id=$1 AND s.id=$2 AND s.status='POSTED'",[ctx.companyId,id])).rows[0];if(!original)throw new BusinessError('NOT_FOUND','Original posted stock source unavailable.',404);this.accounting.scope(ctx,original.branch_id);if(original.original_document_id)throw new BusinessError('REVERSAL_CHAIN','Reversing a reversal is not enabled.');if((await c.query("SELECT 1 FROM source_documents WHERE company_id=$1 AND original_document_id=$2 AND document_type='STOCK_REVERSAL' AND status<>'CANCELLED'",[ctx.companyId,id])).rowCount)throw new BusinessError('ALREADY_REVERSED','An active full reversal request already exists.',409);
   const number=await allocateDocumentNumber(c,ctx,original.branch_id,'STOCK_REVERSAL',v.date),s=(await c.query("INSERT INTO source_documents(company_id,branch_id,document_type,document_number,business_date,currency,description,created_by,initiated_by,original_document_id,reversal_reason) VALUES($1,$2,'STOCK_REVERSAL',$3,$4,$5,$6,$7,$7,$8,$6) RETURNING id,document_number,status,revision",[ctx.companyId,original.branch_id,number,v.date,original.currency,v.reason,ctx.userId,id])).rows[0];await c.query('INSERT INTO inventory_adjustment_lines(company_id,source_id,warehouse_id,product_id,quantity,original_movement_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[ctx.companyId,s.id,original.warehouse_id,original.product_id,original.quantity,original.movement_id,ctx.userId]);await c.query('SELECT stock_identity($1)',[s.id]);await event(c,ctx,s.id,'CREATE',null,'DRAFT',1,v.reason);await this.audit(c,ctx,s.id,'CREATE',v.reason);return s;
 });}
 async pool(c:PoolClient,s:any,l:any){await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,91))',[s.company_id+l.warehouse_id+l.product_id]);const b=(await c.query('SELECT quantity::text,base_value::text,version::text,last_valued_date FROM inventory_balances WHERE company_id=$1 AND warehouse_id=$2 AND product_id=$3',[s.company_id,l.warehouse_id,l.product_id])).rows[0]??{quantity:'0.000000',base_value:'0.00',version:'0',last_valued_date:null};if(b.last_valued_date&&s.business_date<b.last_valued_date)throw new BusinessError('STOCK_DATE_ORDER','Date precedes the latest valued movement; backdated recalculation is not enabled.');return b;}
 async mapping(c:PoolClient,ctx:Context,s:any,l:any,amount:string){if(s.document_type==='STOCK_REVERSAL'){
   const original=(await c.query('SELECT j.id AS journal_id,v.rule_id FROM inventory_movements m JOIN journal_entries j ON j.id=m.journal_id JOIN inventory_valuations v ON v.id=m.valuation_id WHERE m.company_id=$1 AND m.id=$2 AND m.source_id=$3',[ctx.companyId,l.original_movement_id,s.original_document_id])).rows[0];if(!original)throw new BusinessError('ORIGINAL_MOVEMENT','Original posted movement unavailable.');await c.query('SELECT stock_check_rule($1,$2)',[s.id,original.rule_id]);const lines=(await c.query('SELECT account_id AS "accountId",credit::text AS debit,debit::text AS credit,description FROM journal_lines WHERE company_id=$1 AND journal_id=$2 ORDER BY line_no',[ctx.companyId,original.journal_id])).rows;return {ruleId:original.rule_id,reversalOf:original.journal_id,lines};
  }
  const result=await this.rules.effectiveConfigured(c,ctx,{eventType:s.document_type,date:s.business_date,branchId:s.branch_id,warehouseId:l.warehouse_id});if(!result.match)throw new BusinessError(result.code!,result.message!);const selection=result.selection!;
  const legs=(await c.query(`SELECT c.leg_code AS "legCode",c.side,c.amount_key AS "amountKey",(SELECT jsonb_agg(jsonb_build_object('accountType',account_type,'controlType',control_type)) FROM posting_event_leg_eligibility e WHERE e.event_type=c.event_type AND e.contract_version=c.contract_version AND e.leg_code=c.leg_code) AS eligible FROM posting_event_leg_contracts c WHERE event_type=$1 AND contract_version=$2 ORDER BY leg_code`,[s.document_type,selection.rule.contractVersion])).rows;
  const accounts=(await c.query(`SELECT id,company_id AS "companyId",code,name,account_type AS "accountType",control_type AS "controlType",currency,active,postable FROM accounts WHERE company_id=$1 AND id=ANY($2::uuid[])`,[ctx.companyId,selection.rule.legs.map(l=>l.accountId)])).rows;
  try{return {ruleId:selection.rule.id,reversalOf:null,...materializePostingLines({selection,contract:{eventType:s.document_type,version:selection.rule.contractVersion,legs},accounts,amounts:{stockValue:amount},currency:s.currency,functionalCurrency:s.currency})};}catch(e){throw new BusinessError('STOCK_ACCOUNT_POLICY',(e as Error).message);}
 }
 async act(ctx:Context,key:string|undefined,id:string,action:'submit'|'approve'|'reject'|'post'|'refresh'|'cancel',body:unknown){uuid.parse(id);const v=transition.parse(body);return this.commands.run(ctx,key,'stock.'+action+'.'+id,v,async c=>{this.access(ctx);const s=(await c.query("SELECT * FROM source_documents WHERE company_id=$1 AND id=$2 AND document_type IN ('STOCK_GAIN','STOCK_LOSS','STOCK_REVERSAL') FOR UPDATE",[ctx.companyId,id])).rows[0];if(!s)throw new BusinessError('NOT_FOUND','Stock source not found.',404);this.accounting.scope(ctx,s.branch_id);if(s.revision!==v.expectedRevision)throw new BusinessError('REVISION_CONFLICT','Source revision changed.',409);if(['POSTED','CANCELLED'].includes(s.status))throw new BusinessError('STATE_CONFLICT','Posted/cancelled sources are immutable.',409);await c.query('SELECT stock_identity($1)',[id]);const l=(await c.query('SELECT l.*,u.quantity_scale FROM inventory_adjustment_lines l JOIN products p ON p.id=l.product_id JOIN units_of_measure u ON u.id=p.uom_id WHERE l.source_id=$1',[id])).rows[0];let next=s.status,journalId:string|null=null,revision=s.revision;
  if(action==='submit'){
   if(s.status!=='DRAFT')throw new BusinessError('STATE_CONFLICT','Submission requires a draft.',409);if(s.created_by!==ctx.userId)throw new BusinessError('CREATOR_ONLY','Only the creator may submit.',403);const b=await this.pool(c,s,l);let calc;try{if(s.document_type==='STOCK_REVERSAL'){const original=(await c.query('SELECT id,quantity::text,base_value::text AS "baseValue" FROM inventory_movements WHERE company_id=$1 AND id=$2',[ctx.companyId,l.original_movement_id])).rows[0];calc=reverseValuedMovement({balance:{quantity:b.quantity,baseValue:b.base_value},original,quantityScale:l.quantity_scale});}else calc=valueInventoryMovement({operation:s.document_type==='STOCK_GAIN'?'RECEIVE':'ISSUE',currency:s.currency,scale:2,quantityScale:l.quantity_scale,balance:{quantity:b.quantity,baseValue:b.base_value},quantity:l.quantity,...(s.document_type==='STOCK_GAIN'?{baseValue:l.gain_value}:{})});}catch(e){throw new BusinessError('STOCK_VALUATION',(e as Error).message);}
   const amount=new Decimal(calc.movement.baseValue).abs().toFixed(2);if(amount==='0.00')throw new BusinessError('STOCK_ZERO_VALUE','Zero-cent movement posting is not yet supported; no fake journal will be created.');const mapped=await this.mapping(c,ctx,s,l,amount);
   await c.query(`INSERT INTO inventory_valuations(company_id,source_id,revision,pool_version,before_quantity,before_value,quantity_delta,value_delta,after_quantity,after_value,unit_cost,rule_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[ctx.companyId,id,s.revision,b.version,b.quantity,b.base_value,calc.movement.quantity,calc.movement.baseValue,calc.balance.quantity,calc.balance.baseValue,calc.movement.unitCost,mapped.ruleId,ctx.userId]);
   const snapshot=await this.workflow.snapshot(c,ctx,s,amount,'inventory:approve');next='PENDING_APPROVAL';await c.query('UPDATE source_documents SET status=$2,approval_snapshot=$3,updated_by=$4,updated_at=now() WHERE id=$1',[id,next,JSON.stringify(snapshot),ctx.userId]);
  }else if(action==='approve'||action==='reject'){
   if(s.status!=='PENDING_APPROVAL')throw new BusinessError('STATE_CONFLICT','Review requires a pending source.',409);const complete=await this.workflow.decide(c,ctx,s,action==='approve'?'APPROVE':'REJECT',v.reason);next=action==='reject'?'REJECTED':complete?'APPROVED':'PENDING_APPROVAL';await c.query("UPDATE source_documents SET status=$2,approved_by=CASE WHEN $2='APPROVED' THEN $3 ELSE approved_by END,approved_at=CASE WHEN $2='APPROVED' THEN now() ELSE approved_at END,updated_by=$3,updated_at=now() WHERE id=$1",[id,next,ctx.userId]);
  }else if(action==='refresh'){
   if(s.created_by!==ctx.userId)throw new BusinessError('CREATOR_ONLY','Only the creator may refresh valuation.',403);next='DRAFT';revision++;await c.query("UPDATE source_documents SET status='DRAFT',revision=revision+1,approval_snapshot=NULL,approved_by=NULL,approved_at=NULL,updated_by=$2,updated_at=now() WHERE id=$1",[id,ctx.userId]);
  }else if(action==='cancel'){
   next='CANCELLED';await c.query("UPDATE source_documents SET status='CANCELLED',cancelled_by=$2,cancelled_at=now(),updated_by=$2,updated_at=now() WHERE id=$1",[id,ctx.userId]);
  }else{
   if(s.status!=='APPROVED')throw new BusinessError('STATE_CONFLICT','Posting requires completed approval.',409);await this.workflow.checkPoster(c,ctx,s);const b=await this.pool(c,s,l),valuation=(await c.query('SELECT * FROM inventory_valuations WHERE company_id=$1 AND source_id=$2 AND revision=$3',[ctx.companyId,id,s.revision])).rows[0];if(!valuation||valuation.pool_version!==b.version||valuation.before_quantity!==b.quantity||valuation.before_value!==b.base_value)throw new BusinessError('STALE_STOCK','Stock changed after submission. Creator must refresh, resubmit and obtain new approval.',409);
   const mapped=await this.mapping(c,ctx,s,l,new Decimal(valuation.value_delta).abs().toFixed(2));if(mapped.ruleId!==valuation.rule_id||(s.document_type!=='STOCK_REVERSAL'&&(await c.query('SELECT stock_rule_snapshot($1)=$2::jsonb same',[mapped.ruleId,JSON.stringify(valuation.rule_snapshot)])).rows[0].same!==true))throw new BusinessError('STALE_STOCK_RULE','The reviewed mapping changed. Refresh and obtain new approval.',409);
   const val=(await c.query("SELECT stock_source_snapshot($1)->'valuation' AS v",[id])).rows[0].v;journalId=await this.accounting.postPrepared(c,ctx,s,mapped.lines.map(x=>({accountId:x.accountId,debit:x.debit,credit:x.credit,description:x.description})),{valuationId:valuation.id,valuation:val},mapped.reversalOf);
   await c.query('INSERT INTO journal_posting_rule_applications(company_id,journal_id,rule_set_id) VALUES($1,$2,$3)',[ctx.companyId,journalId,mapped.ruleId]);await c.query(`INSERT INTO inventory_movements(company_id,created_by,movement_type,source_line_id,occurred_at,quantity,base_value,unit_cost,approved_by,source_id,warehouse_id,product_id,journal_id,valuation_id,pool_version,original_movement_id) SELECT $1,$2,'STOCK_ADJUSTMENT',$3,$4::date::timestamp AT TIME ZONE 'Africa/Nairobi',quantity_delta,value_delta,unit_cost,$5,$6,$7,$8,$9,id,pool_version+1,$11 FROM inventory_valuations WHERE id=$10`,[ctx.companyId,ctx.userId,l.id,s.business_date,s.approved_by,id,l.warehouse_id,l.product_id,journalId,valuation.id,l.original_movement_id]);next='POSTED';await c.query("UPDATE source_documents SET status='POSTED',posted_by=$2,posted_at=now(),updated_by=$2,updated_at=now() WHERE id=$1",[id,ctx.userId]);
  }
  await event(c,ctx,id,action.toUpperCase(),s.status,next,revision,v.reason);await this.audit(c,ctx,id,action.toUpperCase(),v.reason);return {id,status:next,revision,journalId};
 });}
 async reconciliation(ctx:Context){this.access(ctx);return this.db.transaction(ctx,async c=>{
  // One statement = one MVCC snapshot across both checks, even during concurrent posting.
  const exceptions=(await c.query(`WITH m AS(SELECT company_id,warehouse_id,product_id,sum(quantity) q,sum(base_value) v,count(*) n FROM inventory_movements WHERE company_id=$1 GROUP BY company_id,warehouse_id,product_id),pools AS(SELECT coalesce(b.product_id,m.product_id) product_id,coalesce(b.warehouse_id,m.warehouse_id) warehouse_id,b.quantity::text,b.base_value::text,coalesce(m.q,0)::text AS movement_quantity,coalesce(m.v,0)::text AS movement_value FROM inventory_balances b FULL JOIN m ON m.company_id=b.company_id AND m.warehouse_id=b.warehouse_id AND m.product_id=b.product_id JOIN warehouses w ON w.id=coalesce(b.warehouse_id,m.warehouse_id) WHERE coalesce(b.company_id,m.company_id)=$1 AND w.branch_id=ANY($2::uuid[]) AND (b.id IS NULL OR b.quantity<>coalesce(m.q,0) OR b.base_value<>coalesce(m.v,0) OR b.version<>coalesce(m.n,0))),expected AS(SELECT s.branch_id,rl.account_id,sum(m.base_value) amount FROM inventory_movements m JOIN source_documents s ON s.id=m.source_id JOIN inventory_valuations v ON v.id=m.valuation_id JOIN accounting_rule_legs rl ON rl.rule_set_id=v.rule_id AND rl.leg_code='INVENTORY' WHERE m.company_id=$1 AND s.branch_id=ANY($2::uuid[]) GROUP BY s.branch_id,rl.account_id),actual AS(SELECT j.branch_id,l.account_id,sum(l.base_debit-l.base_credit) amount FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_id JOIN accounts a ON a.id=l.account_id WHERE l.company_id=$1 AND j.branch_id=ANY($2::uuid[]) AND a.control_type='INVENTORY' GROUP BY j.branch_id,l.account_id),gl AS(SELECT coalesce(e.branch_id,a.branch_id) branch_id,coalesce(e.account_id,a.account_id) account_id,coalesce(e.amount,0)::text AS movement_value,coalesce(a.amount,0)::text AS ledger_value FROM expected e FULL JOIN actual a USING(branch_id,account_id) WHERE coalesce(e.amount,0)<>coalesce(a.amount,0)) SELECT 'PROJECTION' AS kind,to_jsonb(p) AS detail FROM pools p UNION ALL SELECT 'INVENTORY_GL',to_jsonb(g) FROM gl g`,[ctx.companyId,ctx.branches])).rows.map(r=>({kind:r.kind,...r.detail}));
  return {status:exceptions.length?'FAIL':'PASS',exceptions,scope:'Assigned branches: stock movement/projection and inventory-control GL; not AR/AP/tax or complete operational reconciliation.'};
 });}
}
