import {Inject,Injectable} from '@nestjs/common';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {PoolClient} from 'pg';
import {Db,Context,BusinessError,audit} from './db';
import {CommandService} from './commands';
import {resolvePostingRule,PostingRuleResolutionError} from './posting-rule-resolver';
const uuid=z.string().uuid(),reason=z.string().trim().min(5).max(500),version=z.number().int().positive().max(2147483647);
const date=z.string().regex(/^(?!0000)\d{4}-\d{2}-\d{2}$/).refine(s=>{const n=Date.parse(s+'T00:00:00Z');return Number.isFinite(n)&&new Date(n).toISOString().slice(0,10)===s;},'Invalid Gregorian date');
const event=z.string().regex(/^[A-Z][A-Z0-9_]{1,63}$/),paging=z.object({q:z.string().max(100).default(''),page:z.coerce.number().int().min(1).max(10000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict();
const create=z.object({kind:z.literal('CREATE'),eventType:event,contractVersion:version,validFrom:date,validTo:date.nullable(),priority:z.number().int().min(-2147483648).max(2147483647),branchId:uuid.nullable().default(null),warehouseId:uuid.nullable().default(null),legs:z.array(z.object({legCode:z.string().regex(/^[A-Z][A-Z0-9_]{1,47}$/),accountId:uuid}).strict()).min(2).max(100),reason}).strict().superRefine((v,c)=>{if(v.validTo&&v.validTo<v.validFrom)c.addIssue({code:'custom',message:'End precedes start'});if(v.warehouseId&&!v.branchId)c.addIssue({code:'custom',message:'Warehouse requires its branch'});if(new Set(v.legs.map(l=>l.legCode)).size!==v.legs.length)c.addIssue({code:'custom',message:'Duplicate symbolic leg'});});
const retire=z.object({kind:z.literal('RETIRE'),ruleId:uuid,expectedVersion:z.number().int().min(0).max(2147483646),effectiveThrough:date,reason}).strict();
const proposal=z.union([create,retire]);
export const ruleProjection=`SELECT r.*,to_jsonb(r)->>'approved_at' AS approved_at_exact,posting_rule_end(r.company_id,r.id) AS effective_to,coalesce((SELECT max(version) FROM accounting_rule_retirements WHERE company_id=r.company_id AND rule_set_id=r.id),0) AS retirement_version,u.display_name AS creator,v.display_name AS reviewer,b.name AS branch_name,w.name AS warehouse_name,(SELECT coalesce(jsonb_agg(to_jsonb(l)||jsonb_build_object('account_code',a.code,'account_name',a.name) ORDER BY l.leg_code),'[]'::jsonb) FROM accounting_rule_legs l JOIN accounts a ON a.company_id=l.company_id AND a.id=l.account_id WHERE l.company_id=r.company_id AND l.rule_set_id=r.id) AS legs,coalesce((SELECT jsonb_agg(to_jsonb(t) ORDER BY version) FROM accounting_rule_retirements t WHERE t.company_id=r.company_id AND t.rule_set_id=r.id),'[]'::jsonb) AS retirements FROM accounting_rule_sets r JOIN users u ON u.id=r.created_by JOIN users v ON v.id=r.approved_by LEFT JOIN branches b ON b.id=r.branch_id LEFT JOIN warehouses w ON w.id=r.warehouse_id`;
@Injectable()
export class PostingRuleConfigurationService{
 constructor(@Inject(Db) private db:Db,@Inject(CommandService) private commands:CommandService){}
 async contracts(ctx:Context){return this.db.transaction(ctx,async c=>(await c.query(`SELECT c.*, (SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('eligible',(SELECT jsonb_agg(jsonb_build_object('accountType',e.account_type,'controlType',e.control_type) ORDER BY account_type,control_type) FROM posting_event_leg_eligibility e WHERE e.event_type=l.event_type AND e.contract_version=l.contract_version AND e.leg_code=l.leg_code)) ORDER BY leg_code) FROM posting_event_leg_contracts l WHERE l.event_type=c.event_type AND l.contract_version=c.contract_version) AS legs FROM posting_event_contracts c WHERE sealed_at IS NOT NULL ORDER BY event_type,contract_version`)).rows);}
 async accounts(ctx:Context,query:unknown){const v=paging.extend({eventType:event,contractVersion:z.coerce.number().int().positive(),legCode:z.string().max(48)}).strict().parse(query);return this.db.transaction(ctx,async c=>{
  const args=[ctx.companyId,v.eventType,v.contractVersion,v.legCode,'%'+v.q+'%'];const where=`a.company_id=$1 AND a.active AND a.postable AND (a.currency IS NULL OR a.currency=co.base_currency) AND (a.code ILIKE $5 OR a.name ILIKE $5) AND EXISTS(SELECT 1 FROM posting_event_leg_eligibility e WHERE e.event_type=$2 AND e.contract_version=$3 AND e.leg_code=$4 AND e.account_type=a.account_type AND e.control_type IS NOT DISTINCT FROM a.control_type)`;
  return {data:(await c.query(`SELECT a.id,a.code,a.name,a.account_type,a.control_type,a.currency FROM accounts a JOIN companies co ON co.id=a.company_id WHERE ${where} ORDER BY a.code,a.id LIMIT $6 OFFSET $7`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM accounts a JOIN companies co ON co.id=a.company_id WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async scopes(ctx:Context,query:unknown){const v=paging.extend({kind:z.enum(['BRANCH','WAREHOUSE']),branchId:uuid.optional()}).strict().parse(query);return this.db.transaction(ctx,async c=>{
  const table=v.kind==='BRANCH'?'branches':'warehouses',args:any[]=[ctx.companyId,'%'+v.q+'%'];let where='company_id=$1 AND active AND (code ILIKE $2 OR name ILIKE $2)';if(v.kind==='WAREHOUSE'){if(!v.branchId)throw new BusinessError('RULE_SCOPE','Choose a branch before selecting a warehouse.');args.push(v.branchId);where+=' AND branch_id=$3';}
  return {data:(await c.query(`SELECT id,code,name FROM ${table} WHERE ${where} ORDER BY code,id LIMIT $${args.length+1} OFFSET $${args.length+2}`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM ${table} WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async catalog(ctx:Context,query:unknown){const v=paging.parse(query);return this.db.transaction(ctx,async c=>{
  const args=[ctx.companyId,'%'+v.q+'%'],where='r.company_id=$1 AND r.publication_request_id IS NOT NULL AND (r.event_type ILIKE $2 OR r.version::text ILIKE $2)';return {data:(await c.query(`${ruleProjection} WHERE ${where} ORDER BY r.event_type,r.version DESC,r.id LIMIT $3 OFFSET $4`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM accounting_rule_sets r WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async changes(ctx:Context,query:unknown){const v=paging.extend({state:z.enum(['PENDING','APPLIED','REJECTED']).optional()}).strict().parse(query);return this.db.transaction(ctx,async c=>{
  const args=[ctx.companyId,'%'+v.q+'%',v.state??null],where="r.company_id=$1 AND (coalesce(r.event_type,'RETIRE') ILIKE $2 OR r.reason ILIKE $2) AND ($3::text IS NULL OR r.state=$3)";
  const data=(await c.query(`SELECT posting_request_snapshot(r.id)||jsonb_build_object('creator',u.display_name,'reviewer',v.display_name,'branch_name',(SELECT name FROM branches WHERE id=r.branch_id),'warehouse_name',(SELECT name FROM warehouses WHERE id=r.warehouse_id),'legs',coalesce((SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('account_code',a.code,'account_name',a.name) ORDER BY l.leg_code) FROM posting_rule_change_legs l JOIN accounts a ON a.company_id=l.company_id AND a.id=l.account_id WHERE l.request_id=r.id),'[]'::jsonb)) AS item FROM posting_rule_change_requests r JOIN users u ON u.id=r.created_by LEFT JOIN users v ON v.id=r.reviewed_by WHERE ${where} ORDER BY r.created_at DESC,r.id LIMIT $4 OFFSET $5`,[...args,v.limit,(v.page-1)*v.limit])).rows.map(r=>r.item);
  return {data,total:(await c.query(`SELECT count(*)::int n FROM posting_rule_change_requests r WHERE ${where}`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async effective(ctx:Context,query:unknown){return this.db.transaction(ctx,c=>this.effectiveConfigured(c,ctx,query));}
 async effectiveConfigured(c:PoolClient,ctx:Context,query:unknown){const v=z.object({eventType:event,date,branchId:uuid,warehouseId:uuid.optional()}).strict().parse(query);
  if(!(await c.query('SELECT 1 FROM branches WHERE company_id=$1 AND id=$2 AND active',[ctx.companyId,v.branchId])).rowCount)throw new BusinessError('RULE_SCOPE','Choose an active branch in this company.');
  if(v.warehouseId&&!(await c.query('SELECT 1 FROM warehouses WHERE company_id=$1 AND branch_id=$2 AND id=$3 AND active',[ctx.companyId,v.branchId,v.warehouseId])).rowCount)throw new BusinessError('RULE_SCOPE','Warehouse does not belong to the selected active branch.');
  const rows=(await c.query(`${ruleProjection} WHERE r.company_id=$1 AND r.event_type=$2 AND r.publication_request_id IS NOT NULL AND r.active AND r.valid_from<=$3 AND (posting_rule_end(r.company_id,r.id) IS NULL OR posting_rule_end(r.company_id,r.id)>=$3) ORDER BY r.id LIMIT 10001`,[ctx.companyId,v.eventType,v.date])).rows;
  if(rows.length>10000)throw new BusinessError('RULE_CANDIDATE_LIMIT','Too many candidate mappings; narrow configuration before posting.');
  const rules=rows.map(r=>({id:r.id,companyId:r.company_id,eventType:r.event_type,version:r.version,contractVersion:r.contract_version,validFrom:r.valid_from,validTo:r.effective_to,priority:r.priority,active:r.active,createdBy:r.created_by,approvedBy:r.approved_by,approvedAt:r.approved_at_exact,branchId:r.branch_id,warehouseId:r.warehouse_id,productId:r.product_id,categoryId:r.category_id,taxCategoryId:r.tax_category_id,paymentMethodId:r.payment_method_id,legs:r.legs.map((l:any)=>({legCode:l.leg_code,side:l.side,amountKey:l.amount_key,accountId:l.account_id}))}));
  try{const selection=resolvePostingRule({...v,companyId:ctx.companyId},rules),selected=rows.find(r=>r.id===selection.rule.id);return {match:true,selection,retirements:selected.retirements,configurationOnly:true};}catch(e){if(e instanceof PostingRuleResolutionError)return {match:false,code:e.code,message:e.message,configurationOnly:true};throw e;}
 }
 async validate(c:PoolClient,id:string){try{await c.query('SELECT assert_posting_request($1)',[id]);}catch(e:any){const messages:Record<string,string>={RULE_SCOPE:'Choose active, matching company/branch/warehouse records.',RULE_ACCOUNTS:'Map every contract leg to an active, postable, correctly denominated eligible account.',RULE_OVERLAP:'An equally ranked published rule overlaps this scope and period.',RULE_CONTRACT:'Choose a registered sealed event contract.',RULE_TARGET:'Select a published rule in this company.',RULE_VERSION:'Retirement version changed. Reject the stale request and propose again.',RULE_RETIREMENT_DATE:'Retirement must shorten coverage, cannot precede today or its start, and cannot invalidate posted applications.'};if(e.code==='23514'&&messages[e.message])throw new BusinessError(e.message,messages[e.message],e.message==='RULE_VERSION'?409:422);throw e;}}
 async propose(ctx:Context,key:string|undefined,body:unknown){const v=proposal.parse(body);return this.commands.run(ctx,key,'rules.propose',v,async c=>{
  let id:string;
  if(v.kind==='CREATE'){
   id=(await c.query(`INSERT INTO posting_rule_change_requests(company_id,kind,event_type,contract_version,valid_from,valid_to,priority,branch_id,warehouse_id,new_rule_id,reason,created_by) VALUES($1,'CREATE',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[ctx.companyId,v.eventType,v.contractVersion,v.validFrom,v.validTo,v.priority,v.branchId,v.warehouseId,randomUUID(),v.reason,ctx.userId])).rows[0].id;
   for(const l of [...v.legs].sort((a,b)=>a.legCode.localeCompare(b.legCode)))await c.query('INSERT INTO posting_rule_change_legs(company_id,request_id,leg_code,account_id) VALUES($1,$2,$3,$4)',[ctx.companyId,id,l.legCode,l.accountId]);
  }else id=(await c.query(`INSERT INTO posting_rule_change_requests(company_id,kind,target_id,expected_version,effective_through,reason,created_by) VALUES($1,'RETIRE',$2,$3,$4,$5,$6) RETURNING id`,[ctx.companyId,v.ruleId,v.expectedVersion,v.effectiveThrough,v.reason,ctx.userId])).rows[0].id;
  await this.validate(c,id);const after=(await c.query('SELECT posting_request_snapshot($1) AS snapshot',[id])).rows[0].snapshot;
  await audit(c,ctx,'RULE_CHANGE_PROPOSE',null,{before:null,after,ruleAfter:null,retirementAfter:null},v.reason,'POSTING_RULE_CONFIGURATION',id);return {id,state:'PENDING'};
 },true);}
 async decide(ctx:Context,key:string|undefined,id:string,body:unknown){uuid.parse(id);const v=z.object({decision:z.enum(['APPROVE','REJECT']),reason}).strict().parse(body);return this.commands.run(ctx,key,'rules.decide.'+id,v,async c=>{
  await c.query('SELECT id FROM posting_rule_change_requests WHERE company_id=$1 AND id=$2 FOR UPDATE',[ctx.companyId,id]);const before=(await c.query('SELECT posting_request_snapshot($1) AS snapshot',[id])).rows[0].snapshot;
  if(!before)throw new BusinessError('NOT_FOUND','Posting-rule request not found.',404);if(before.state!=='PENDING')throw new BusinessError('STATE_CONFLICT','This request was already reviewed.',409);if(before.created_by===ctx.userId)throw new BusinessError('INDEPENDENT_REVIEW','Another authorized user must review your request.',403);
  const apply=v.decision==='APPROVE';if(apply)await this.validate(c,id);
  await c.query('UPDATE posting_rule_change_requests SET state=$2,reviewed_by=$3,reviewed_at=now(),review_reason=$4 WHERE id=$1',[id,apply?'APPLIED':'REJECTED',ctx.userId,v.reason]);
  let ruleAfter=null,retirementAfter=null;
  if(apply&&before.kind==='CREATE'){
   await c.query(`INSERT INTO accounting_rule_sets(id,company_id,created_by,event_type,version,valid_from,valid_to,priority,approved_by,approved_at,active,branch_id,warehouse_id,contract_version,publication_request_id) SELECT $1,$2,$3,$4,coalesce(max(version),0)+1,$5,$6,$7,$8,now(),true,$9,$10,$11,$12 FROM accounting_rule_sets WHERE company_id=$2 AND event_type=$4`,[before.new_rule_id,ctx.companyId,before.created_by,before.event_type,before.valid_from,before.valid_to,before.priority,ctx.userId,before.branch_id,before.warehouse_id,before.contract_version,id]);
   await c.query(`INSERT INTO accounting_rule_legs(company_id,created_by,leg_code,side,amount_key,rule_set_id,account_id) SELECT l.company_id,$2,l.leg_code,c.side,c.amount_key,$3,l.account_id FROM posting_rule_change_legs l JOIN posting_event_leg_contracts c ON c.event_type=$4 AND c.contract_version=$5 AND c.leg_code=l.leg_code WHERE l.request_id=$1 ORDER BY l.leg_code`,[id,before.created_by,before.new_rule_id,before.event_type,before.contract_version]);
   ruleAfter=(await c.query('SELECT posting_rule_snapshot($1) AS snapshot',[before.new_rule_id])).rows[0].snapshot;
  }else if(apply)retirementAfter=(await c.query('INSERT INTO accounting_rule_retirements(company_id,rule_set_id,version,effective_through,request_id,created_by,reviewed_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING to_jsonb(accounting_rule_retirements) AS snapshot',[ctx.companyId,before.target_id,before.expected_version+1,before.effective_through,id,before.created_by,ctx.userId])).rows[0].snapshot;
  const after=(await c.query('SELECT posting_request_snapshot($1) AS snapshot',[id])).rows[0].snapshot;await audit(c,ctx,'RULE_CHANGE_'+v.decision,null,{before,after,ruleAfter,retirementAfter},v.reason,'POSTING_RULE_CONFIGURATION',id);
  return {id,state:after.state,ruleId:ruleAfter?.id??(apply?before.target_id:null),version:ruleAfter?.version??retirementAfter?.version??null};
 },true);}
}
