import {Inject,Injectable} from '@nestjs/common';
import {z} from 'zod';
import Decimal from 'decimal.js';
import {PoolClient} from 'pg';
import {Db,Context,BusinessError} from './db';
import {CommandService} from './commands';
import {TaxConfigurationService} from './tax-configuration';
const uuid=z.string().uuid(),reason=z.string().trim().min(5).max(500),identity=z.string().regex(/^[A-Z0-9][A-Z0-9._/-]{0,63}$/),price=z.string().regex(/^(0|[1-9]\d{0,13})(\.\d{1,6})?$/),barcode=z.string().min(1).max(128).regex(/^[!-~]+$/);
const date=z.string().regex(/^(?!0000)\d{4}-\d{2}-\d{2}$/).refine(s=>{const n=Date.parse(s+'T00:00:00Z');return Number.isFinite(n)&&new Date(n).toISOString().slice(0,10)===s;},'Invalid Gregorian date');
const proposal=z.object({sku:identity,productCode:identity,name:z.string().trim().min(2).max(160),description:z.string().trim().max(1000).nullable().default(null),itemType:z.enum(['STOCK','SERVICE','NON_STOCK']),categoryId:uuid,brandId:uuid.nullable().default(null),uomId:uuid,purchasePrice:price,sellingPrice:price,priceMode:z.enum(['INCLUSIVE','EXCLUSIVE']),taxCategoryId:uuid,validFrom:date,validTo:date,taxIds:z.array(uuid).max(10).refine(a=>new Set(a).size===a.length),barcodes:z.array(barcode).max(20).refine(a=>new Set(a).size===a.length),reason}).strict().refine(v=>v.validTo>=v.validFrom,'End must not precede start');
const paging=z.object({q:z.string().max(100).default(''),page:z.coerce.number().int().min(1).max(10000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict();
const projection=`SELECT p.*,CASE WHEN $2::boolean THEN p.purchase_price::text ELSE NULL END AS purchase_price,p.selling_price::text AS selling_price,c.name AS category_name,b.name AS brand_name,u.code AS uom_code,u.quantity_scale,cr.display_name AS creator,rv.display_name AS reviewer,
 coalesce((SELECT jsonb_agg(jsonb_build_object('barcode',bc.barcode,'uom_id',bc.uom_id) ORDER BY bc.barcode) FROM product_barcodes bc WHERE bc.company_id=p.company_id AND bc.product_id=p.id),'[]'::jsonb) AS barcodes,
 (SELECT to_jsonb(f)||jsonb_build_object('classification',tc.classification,'category_name',tc.name,'tax_ids',coalesce((SELECT jsonb_agg(t.tax_id ORDER BY t.tax_id) FROM product_taxes t WHERE t.company_id=f.company_id AND t.profile_id=f.id),'[]'::jsonb),'tax_names',coalesce((SELECT jsonb_agg(tx.name ORDER BY tx.id) FROM product_taxes t JOIN taxes tx ON tx.company_id=t.company_id AND tx.id=t.tax_id WHERE t.company_id=f.company_id AND t.profile_id=f.id),'[]'::jsonb)) FROM product_tax_profiles f JOIN tax_categories tc ON tc.company_id=f.company_id AND tc.id=f.tax_category_id WHERE f.company_id=p.company_id AND f.request_id=p.publication_request_id) AS tax_profile
 FROM products p JOIN product_categories c ON c.company_id=p.company_id AND c.id=p.category_id JOIN units_of_measure u ON u.company_id=p.company_id AND u.id=p.uom_id LEFT JOIN brands b ON b.company_id=p.company_id AND b.id=p.brand_id JOIN users cr ON cr.id=p.created_by JOIN users rv ON rv.id=p.approved_by`;
@Injectable()
export class ProductConfigurationService{
 constructor(@Inject(Db) private db:Db,@Inject(CommandService) private commands:CommandService,@Inject(TaxConfigurationService) private taxes:TaxConfigurationService){}
 canCost(ctx:Context){return ctx.permissions.includes('products:cost:view');}
 async catalog(ctx:Context,query:unknown){const v=paging.parse(query);return this.db.transaction(ctx,async c=>{
  const where="p.company_id=$1 AND p.publication_request_id IS NOT NULL AND (p.sku ILIKE $3 OR p.product_code ILIKE $3 OR p.name ILIKE $3 OR EXISTS(SELECT 1 FROM product_barcodes b WHERE b.company_id=p.company_id AND b.product_id=p.id AND b.barcode ILIKE $3))",args=[ctx.companyId,this.canCost(ctx),'%'+v.q+'%'];
  return {data:(await c.query(projection+` WHERE ${where} ORDER BY p.name,p.id LIMIT $4 OFFSET $5`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM products p WHERE ${where} AND $2::boolean IS NOT NULL`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async detail(ctx:Context,id:string){uuid.parse(id);return this.db.transaction(ctx,async c=>{const r=(await c.query(projection+' WHERE p.company_id=$1 AND p.publication_request_id IS NOT NULL AND p.id=$3',[ctx.companyId,this.canCost(ctx),id])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','Product not found.',404);return r;});}
 async lookup(ctx:Context,query:unknown){const v=z.object({barcode}).strict().parse(query);return this.db.transaction(ctx,async c=>{const r=(await c.query(projection+' WHERE p.company_id=$1 AND p.publication_request_id IS NOT NULL AND p.active AND EXISTS(SELECT 1 FROM product_barcodes b WHERE b.company_id=p.company_id AND b.product_id=p.id AND b.barcode=$3)',[ctx.companyId,this.canCost(ctx),v.barcode])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','No governed product matches this exact barcode.',404);return r;});}
 async changes(ctx:Context,query:unknown){const v=paging.extend({state:z.enum(['PENDING','APPLIED','REJECTED']).optional()}).strict().parse(query);return this.db.transaction(ctx,async c=>{
  const args=[ctx.companyId,this.canCost(ctx),'%'+v.q+'%',v.state??null],where="r.company_id=$1 AND (r.sku ILIKE $3 OR r.name ILIKE $3 OR r.reason ILIKE $3) AND ($4::text IS NULL OR r.state=$4)";
  return {data:(await c.query(`SELECT r.*,CASE WHEN $2::boolean THEN r.purchase_price::text ELSE NULL END AS purchase_price,r.selling_price::text AS selling_price,u.display_name AS creator,v.display_name AS reviewer,c.name AS category_name,b.name AS brand_name,um.code AS uom_code,tc.name AS tax_category_name,tc.classification,
   coalesce((SELECT jsonb_agg(barcode ORDER BY barcode) FROM product_request_barcodes WHERE request_id=r.id),'[]'::jsonb) AS barcodes,coalesce((SELECT jsonb_agg(tx.name ORDER BY tx.id) FROM product_request_taxes rt JOIN taxes tx ON tx.id=rt.tax_id WHERE rt.request_id=r.id),'[]'::jsonb) AS tax_names
   FROM product_change_requests r JOIN users u ON u.id=r.created_by LEFT JOIN users v ON v.id=r.reviewed_by JOIN product_categories c ON c.id=r.category_id LEFT JOIN brands b ON b.id=r.brand_id JOIN units_of_measure um ON um.id=r.uom_id JOIN tax_categories tc ON tc.id=r.tax_category_id WHERE ${where} ORDER BY r.created_at DESC,r.id LIMIT $5 OFFSET $6`,[...args,v.limit,(v.page-1)*v.limit])).rows,total:(await c.query(`SELECT count(*)::int n FROM product_change_requests r WHERE ${where} AND $2::boolean IS NOT NULL`,args)).rows[0].n,page:v.page,limit:v.limit};
 });}
 async validate(c:PoolClient,id:string){try{await c.query('SELECT assert_product_request($1)',[id]);}catch(e:any){const errors:Record<string,string>={PRODUCT_REFERENCES:'Choose governed same-company unit, category and optional brand.',PRODUCT_IDENTITY:'SKU, product code or barcode is already assigned.',PRODUCT_TAX_PROFILE:'Choose a reviewed category and a compatible explicit tax set; exempt/non-taxable requires no taxes and exclusive mode.',PRODUCT_TAX_COVERAGE:'Reviewed tax schedules must cover the entire profile interval in the selected price mode.',TAX_ACCOUNTS:'A configured tax account is no longer eligible.',TAX_CLASSIFICATION:'A selected tax or category is no longer eligible.'};if(e.code==='23514'&&errors[e.message])throw new BusinessError(e.message,errors[e.message]);throw e;}}
 // SQL builds the complete audit JSON. Prices never pass through JavaScript Number.
 async recordAudit(c:PoolClient,ctx:Context,id:string,action:string,before:string|null,why:string){await c.query(`INSERT INTO audit_logs(company_id,actor_id,action,module,entity_type,entity_id,request_id,session_id,ip,device,new_values,reason) SELECT $1,$2,$3,'CORE','PRODUCT_CONFIGURATION',$4,$5,$6,$7,$8,jsonb_build_object('before',coalesce($9::jsonb,'null'::jsonb),'after',product_request_snapshot($4),'published',coalesce(product_publication_snapshot($4),'null'::jsonb)),$10`,[ctx.companyId,ctx.userId,action,id,ctx.requestId,ctx.sessionId,ctx.ip,ctx.device,before,why]);}
 async propose(ctx:Context,key:string|undefined,body:unknown){const v=proposal.parse(body);return this.commands.run(ctx,key,'products.propose',v,async c=>{
  const id=(await c.query(`INSERT INTO product_change_requests(company_id,sku,product_code,name,description,item_type,category_id,brand_id,uom_id,tax_category_id,currency,purchase_price,selling_price,price_mode,valid_from,valid_to,reason,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,base_currency,$11,$12,$13,$14,$15,$16,$17 FROM companies WHERE id=$1 RETURNING id`,[ctx.companyId,v.sku,v.productCode,v.name,v.description,v.itemType,v.categoryId,v.brandId,v.uomId,v.taxCategoryId,v.purchasePrice,v.sellingPrice,v.priceMode,v.validFrom,v.validTo,v.reason,ctx.userId])).rows[0].id;
  for(const b of [...v.barcodes].sort())await c.query('INSERT INTO product_request_barcodes(company_id,request_id,barcode) VALUES($1,$2,$3)',[ctx.companyId,id,b]);
  for(const t of [...v.taxIds].sort())await c.query('INSERT INTO product_request_taxes(company_id,request_id,tax_id) VALUES($1,$2,$3)',[ctx.companyId,id,t]);
  await this.validate(c,id);await this.recordAudit(c,ctx,id,'PRODUCT_CHANGE_PROPOSE',null,v.reason);return {id,state:'PENDING'};
 },true);}
 async decide(ctx:Context,key:string|undefined,id:string,body:unknown){uuid.parse(id);const v=z.object({decision:z.enum(['APPROVE','REJECT']),reason}).strict().parse(body);return this.commands.run(ctx,key,'products.decide.'+id,v,async c=>{
  const r=(await c.query('SELECT r.*,product_request_snapshot(r.id)::text AS before_text FROM product_change_requests r WHERE company_id=$1 AND id=$2 FOR UPDATE',[ctx.companyId,id])).rows[0];if(!r)throw new BusinessError('NOT_FOUND','Product request not found.',404);if(r.state!=='PENDING')throw new BusinessError('STATE_CONFLICT','Request already reviewed.',409);if(r.created_by===ctx.userId)throw new BusinessError('INDEPENDENT_REVIEW','Another authorized user must review this request.',403);
  const apply=v.decision==='APPROVE';if(apply){if(!this.canCost(ctx))throw new BusinessError('PRODUCT_COST_REVIEW','Purchase-cost visibility is required to approve initial prices.',403);await this.validate(c,id);}
  await c.query('UPDATE product_change_requests SET state=$2,reviewed_by=$3,reviewed_at=now(),review_reason=$4 WHERE id=$1',[id,apply?'APPLIED':'REJECTED',ctx.userId,v.reason]);
  if(apply){await c.query(`INSERT INTO products(id,company_id,created_by,sku,product_code,name,description,item_type,category_id,brand_id,uom_id,tax_category_id,purchase_price,selling_price,price_mode,currency,publication_request_id,approved_by,approved_at) SELECT new_product_id,company_id,created_by,sku,product_code,name,description,item_type,category_id,brand_id,uom_id,tax_category_id,purchase_price,selling_price,price_mode,currency,id,reviewed_by,reviewed_at FROM product_change_requests WHERE id=$1`,[id]);
   await c.query(`INSERT INTO product_tax_profiles(id,company_id,product_id,tax_category_id,valid_from,valid_to,request_id,created_by,approved_by,approved_at) SELECT new_profile_id,company_id,new_product_id,tax_category_id,valid_from,valid_to,id,created_by,reviewed_by,reviewed_at FROM product_change_requests WHERE id=$1`,[id]);
   await c.query(`INSERT INTO product_barcodes(company_id,created_by,barcode,product_id,uom_id) SELECT r.company_id,r.created_by,b.barcode,r.new_product_id,r.uom_id FROM product_change_requests r JOIN product_request_barcodes b ON b.request_id=r.id WHERE r.id=$1 ORDER BY b.barcode`,[id]);
   await c.query(`INSERT INTO product_taxes(company_id,created_by,valid_from,valid_to,product_id,tax_id,profile_id) SELECT r.company_id,r.created_by,r.valid_from,r.valid_to,r.new_product_id,t.tax_id,r.new_profile_id FROM product_change_requests r JOIN product_request_taxes t ON t.request_id=r.id WHERE r.id=$1 ORDER BY t.tax_id`,[id]);}
  await this.recordAudit(c,ctx,id,'PRODUCT_CHANGE_'+v.decision,r.before_text,v.reason);return {id,state:apply?'APPLIED':'REJECTED',productId:apply?r.new_product_id:null};
 },true);}
 async preview(ctx:Context,id:string,body:unknown){uuid.parse(id);const v=z.object({date,quantity:z.string().regex(/^(0|[1-9]\d{0,13})(\.\d{1,6})?$/),discount:z.string().max(30).default('0')}).strict().parse(body);return this.db.transaction(ctx,async c=>{
  await c.query('SELECT pg_advisory_xact_lock_shared(hashtextextended($1,77))',[ctx.companyId]);
  const p=(await c.query('SELECT p.selling_price::text AS price,p.price_mode,p.currency,u.quantity_scale FROM products p JOIN units_of_measure u ON u.company_id=p.company_id AND u.id=p.uom_id WHERE p.company_id=$1 AND p.id=$2 AND p.publication_request_id IS NOT NULL AND p.active',[ctx.companyId,id])).rows[0];if(!p)throw new BusinessError('NOT_FOUND','Product not found.',404);
  if(new Decimal(v.quantity).lte(0)||new Decimal(v.quantity).decimalPlaces()>p.quantity_scale)throw new BusinessError('PRODUCT_QUANTITY','Quantity must be positive and fit the base-unit precision.');
  const profiles=(await c.query('SELECT * FROM product_tax_profiles WHERE company_id=$1 AND product_id=$2 AND valid_from<=$3 AND valid_to>=$3',[ctx.companyId,id,v.date])).rows;if(profiles.length!==1)throw new BusinessError('PRODUCT_TAX_PROFILE','Exactly one dated product tax profile is required.');
  const f=profiles[0],taxIds=(await c.query('SELECT tax_id FROM product_taxes WHERE company_id=$1 AND profile_id=$2 ORDER BY tax_id',[ctx.companyId,f.id])).rows.map(r=>r.tax_id);
  const result=await this.taxes.calculateConfigured(c,ctx,{categoryId:f.tax_category_id,taxIds,date:v.date,quantity:v.quantity,unitPrice:p.price,discount:v.discount});
  if(result.calculation.snapshot.priceMode!==p.price_mode||result.calculation.snapshot.input.currency!==p.currency)throw new BusinessError('PRODUCT_PRICE_MODE','Current configured tax price mode/currency differs from the registered product.');
  return {...result,productId:id,profileId:f.id};
 });}
}
