"""Generate reviewable target DDL. Domain services/guards are phased separately."""
from pathlib import Path
out=['-- Target domain baseline. Structure is not proof of implemented workflows.\nBEGIN;']
names=[]
def table(name, fields='', refs=None, constraints=None, source=False):
    names.append(name)
    cols=['id uuid PRIMARY KEY DEFAULT gen_random_uuid()', 'company_id uuid NOT NULL REFERENCES companies(id)', 'created_by uuid NOT NULL REFERENCES users(id)', 'created_at timestamptz NOT NULL DEFAULT now()', 'UNIQUE(company_id,id)']
    if source:
        cols += ['source_id uuid NOT NULL', 'UNIQUE(company_id,source_id)', 'FOREIGN KEY(company_id,source_id) REFERENCES source_documents(company_id,id)']
    if fields: cols += [fields]
    for col,target,nullable in (refs or []):
        cols += [f'{col} uuid'+('' if nullable else ' NOT NULL'), f'FOREIGN KEY(company_id,{col}) REFERENCES {target}(company_id,id)']
    cols += constraints or []
    out.append(f'CREATE TABLE {name}(\n '+',\n '.join(cols)+'\n);')

table('pos_terminals',"code text NOT NULL, name text NOT NULL, active boolean NOT NULL DEFAULT true", [('branch_id','branches',False),('warehouse_id','warehouses',False)],['UNIQUE(company_id,code)'])
table('cashier_sessions',"cashier_id uuid NOT NULL REFERENCES users(id), status text NOT NULL CHECK(status IN ('OPEN','ACTIVE','RECONCILIATION','CLOSED')), opened_at timestamptz NOT NULL, closed_at timestamptz, reconciled_by uuid REFERENCES users(id), approved_by uuid REFERENCES users(id), expected_cash money_amount, actual_cash money_amount, variance_reason text",[('terminal_id','pos_terminals',False),('branch_id','branches',False)],source=True)
out.append("CREATE UNIQUE INDEX one_terminal_session ON cashier_sessions(company_id,terminal_id) WHERE status<>'CLOSED';")
table('tax_categories',"code text NOT NULL, name text NOT NULL, classification text NOT NULL CHECK(classification IN ('TAXABLE','ZERO_RATED','EXEMPT','NON_TAXABLE'))",constraints=['UNIQUE(company_id,code)'])
table('taxes',"code text NOT NULL, name text NOT NULL, tax_type text NOT NULL, active boolean NOT NULL DEFAULT true",constraints=['UNIQUE(company_id,code)'])
table('tax_rates',"valid_from date NOT NULL, valid_to date NOT NULL, rate rate_amount NOT NULL CHECK(rate>=0), inclusive boolean NOT NULL, recoverable_fraction rate_amount NOT NULL CHECK(recoverable_fraction BETWEEN 0 AND 1), priority integer NOT NULL DEFAULT 0, CHECK(valid_to>=valid_from)",[('tax_id','taxes',False),('category_id','tax_categories',False),('input_account_id','accounts',True),('output_account_id','accounts',True)],['EXCLUDE USING gist(company_id WITH =, tax_id WITH =, category_id WITH =, daterange(valid_from,valid_to,\'[]\') WITH &&)'])
partner="number text NOT NULL, name text NOT NULL, phone text, email text, address text, tax_pin text, payment_terms_days integer NOT NULL DEFAULT 0 CHECK(payment_terms_days>=0), currency char(3) NOT NULL REFERENCES currencies(code), active boolean NOT NULL DEFAULT true"
table('customers',partner+", customer_type text NOT NULL, credit_limit money_amount NOT NULL DEFAULT 0 CHECK(credit_limit>=0), credit_hold boolean NOT NULL DEFAULT false",[('tax_category_id','tax_categories',True)],['UNIQUE(company_id,number)'])
table('suppliers',partner+", credit_terms text",[('tax_category_id','tax_categories',True)],['UNIQUE(company_id,number)'])
table('customer_accounts','', [('customer_id','customers',False),('control_account_id','accounts',False)], ['UNIQUE(company_id,customer_id)'])
table('supplier_accounts','', [('supplier_id','suppliers',False),('control_account_id','accounts',False)], ['UNIQUE(company_id,supplier_id)'])
table('product_categories',"code text NOT NULL, name text NOT NULL",constraints=['UNIQUE(company_id,code)'])
out.append('ALTER TABLE product_categories ADD parent_id uuid, ADD FOREIGN KEY(company_id,parent_id) REFERENCES product_categories(company_id,id);')
table('brands',"name text NOT NULL",constraints=['UNIQUE(company_id,name)'])
table('units_of_measure',"code text NOT NULL, name text NOT NULL, quantity_scale smallint NOT NULL CHECK(quantity_scale BETWEEN 0 AND 6)",constraints=['UNIQUE(company_id,code)'])
table('products',"sku text NOT NULL, product_code text NOT NULL, name text NOT NULL, description text, item_type text NOT NULL CHECK(item_type IN ('STOCK','SERVICE','NON_STOCK')), serialized boolean NOT NULL DEFAULT false, batch_controlled boolean NOT NULL DEFAULT false, expiry_controlled boolean NOT NULL DEFAULT false, purchase_price unit_amount NOT NULL DEFAULT 0 CHECK(purchase_price>=0), selling_price unit_amount NOT NULL DEFAULT 0 CHECK(selling_price>=0), reorder_level quantity_amount NOT NULL DEFAULT 0, min_stock quantity_amount NOT NULL DEFAULT 0, max_stock quantity_amount, active boolean NOT NULL DEFAULT true, CHECK(NOT expiry_controlled OR batch_controlled)",[('category_id','product_categories',False),('brand_id','brands',True),('uom_id','units_of_measure',False),('supplier_id','suppliers',True),('tax_category_id','tax_categories',False)],['UNIQUE(company_id,sku)','UNIQUE(company_id,product_code)'])
table('product_uom_conversions','factor quantity_amount NOT NULL CHECK(factor>0)', [('product_id','products',False),('uom_id','units_of_measure',False)],['UNIQUE(company_id,product_id,uom_id)'])
table('product_barcodes','barcode text NOT NULL', [('product_id','products',False),('uom_id','units_of_measure',False)],['UNIQUE(company_id,barcode)'])
table('price_lists','name text NOT NULL, currency char(3) NOT NULL REFERENCES currencies(code)',constraints=['UNIQUE(company_id,name)'])
table('product_prices','price unit_amount NOT NULL CHECK(price>=0), min_quantity quantity_amount NOT NULL DEFAULT 1 CHECK(min_quantity>0), valid_from date NOT NULL, valid_to date, inclusive boolean NOT NULL', [('product_id','products',False),('price_list_id','price_lists',False)])
table('product_taxes','valid_from date NOT NULL, valid_to date', [('product_id','products',False),('tax_id','taxes',False)])
table('inventory_lots','batch_number text NOT NULL, expiry_date date', [('product_id','products',False)],['UNIQUE(company_id,product_id,batch_number)'])
table('inventory_serials','serial_number text NOT NULL', [('product_id','products',False)],['UNIQUE(company_id,product_id,serial_number)'])
table('inventory_movements',"movement_type text NOT NULL CHECK(movement_type IN ('PURCHASE_RECEIPT','SALE','SALES_RETURN','SUPPLIER_RETURN','TRANSFER_OUT','TRANSFER_IN','STOCK_ADJUSTMENT','STOCK_COUNT','DAMAGE','EXPIRY','OPENING_BALANCE','VALUE_ADJUSTMENT')), source_line_id uuid NOT NULL, occurred_at timestamptz NOT NULL, quantity quantity_amount NOT NULL, base_value money_amount NOT NULL, unit_cost unit_amount NOT NULL CHECK(unit_cost>=0), approved_by uuid REFERENCES users(id), CHECK(quantity<>0 OR (movement_type='VALUE_ADJUSTMENT' AND base_value<>0))",[('source_id','source_documents',False),('warehouse_id','warehouses',False),('product_id','products',False),('lot_id','inventory_lots',True),('serial_id','inventory_serials',True),('journal_id','journal_entries',False)],['UNIQUE(company_id,source_id,source_line_id,movement_type,warehouse_id)'])
out.append('ALTER TABLE inventory_movements ADD original_movement_id uuid, ADD FOREIGN KEY(company_id,original_movement_id) REFERENCES inventory_movements(company_id,id);')
table('inventory_balances','quantity quantity_amount NOT NULL DEFAULT 0 CHECK(quantity>=0), base_value money_amount NOT NULL DEFAULT 0 CHECK(base_value>=0), version bigint NOT NULL DEFAULT 0, CHECK(quantity<>0 OR base_value=0)', [('warehouse_id','warehouses',False),('product_id','products',False)],['UNIQUE(company_id,warehouse_id,product_id)'])
table('stock_reservations',"quantity quantity_amount NOT NULL CHECK(quantity>0), expires_at timestamptz NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','CONSUMED','RELEASED','EXPIRED'))",[('source_id','source_documents',False),('warehouse_id','warehouses',False),('product_id','products',False)])
table('valuation_policies',"method text NOT NULL CHECK(method IN ('WEIGHTED_AVERAGE','FIFO')), effective_from date NOT NULL, active boolean NOT NULL DEFAULT false",[('warehouse_id','warehouses',False)])
table('cost_layers','received_quantity quantity_amount NOT NULL CHECK(received_quantity>0), unit_cost unit_amount NOT NULL CHECK(unit_cost>=0)', [('receipt_movement_id','inventory_movements',False)])
table('cost_layer_allocations','quantity quantity_amount NOT NULL CHECK(quantity>0), base_value money_amount NOT NULL CHECK(base_value>=0)', [('layer_id','cost_layers',False),('issue_movement_id','inventory_movements',False)])
table('stock_counts','cutoff_at timestamptz NOT NULL, count_scope jsonb NOT NULL, blind boolean NOT NULL DEFAULT true', [('warehouse_id','warehouses',False)],source=True)
table('stock_count_lines','system_quantity quantity_amount NOT NULL, counted_quantity quantity_amount CHECK(counted_quantity>=0), counted_by uuid REFERENCES users(id), counted_at timestamptz, variance_value money_amount', [('count_id','stock_counts',False),('product_id','products',False),('lot_id','inventory_lots',True)])
table('stock_transfers','dispatched_by uuid REFERENCES users(id), dispatched_at timestamptz, received_by uuid REFERENCES users(id), received_at timestamptz', [('from_warehouse_id','warehouses',False),('to_warehouse_id','warehouses',False),('transit_warehouse_id','warehouses',False)],['CHECK(from_warehouse_id<>to_warehouse_id)'],source=True)
table('stock_transfer_lines','requested_quantity quantity_amount NOT NULL CHECK(requested_quantity>0)', [('transfer_id','stock_transfers',False),('product_id','products',False)])
table('stock_transfer_receipts','quantity quantity_amount NOT NULL CHECK(quantity>0), discrepancy_reason text', [('transfer_line_id','stock_transfer_lines',False),('movement_id','inventory_movements',False)],source=True)
line="line_no integer NOT NULL CHECK(line_no>0), quantity quantity_amount NOT NULL CHECK(quantity>0), unit_price unit_amount NOT NULL CHECK(unit_price>=0), discount money_amount NOT NULL DEFAULT 0 CHECK(discount>=0), net money_amount NOT NULL CHECK(net>=0), tax money_amount NOT NULL CHECK(tax>=0), gross money_amount NOT NULL CHECK(gross>=0), tax_snapshot jsonb NOT NULL, CHECK(net+tax=gross)"
for head,detail,fk in [('quotations','quotation_lines','quotation_id'),('sales_orders','sales_order_lines','order_id')]:
    table(head,'valid_until date, payment_terms_snapshot jsonb NOT NULL', [('customer_id','customers',True)],source=True)
    table(detail,line,[ (fk,head,False),('product_id','products',False),('uom_id','units_of_measure',False)],[f'UNIQUE(company_id,{fk},line_no)'])
table('pos_carts',"version integer NOT NULL DEFAULT 1, state text NOT NULL CHECK(state IN ('ACTIVE','HELD','CHECKOUT_PENDING','CONVERTED','CANCELLED')), cart_snapshot jsonb NOT NULL, expires_at timestamptz",[('customer_id','customers',True),('session_id','cashier_sessions',False)],source=True)
table('sales',"sale_type text NOT NULL CHECK(sale_type IN ('CASH','CREDIT','MIXED')), due_date date, net money_amount NOT NULL, tax money_amount NOT NULL, gross money_amount NOT NULL, CHECK(net+tax=gross), CHECK(sale_type<>'CREDIT' OR customer_id IS NOT NULL)",[('customer_id','customers',True),('warehouse_id','warehouses',False),('terminal_id','pos_terminals',True),('cashier_session_id','cashier_sessions',True),('sales_order_id','sales_orders',True)],source=True)
table('sale_lines',line+', cogs money_amount NOT NULL CHECK(cogs>=0)', [('sale_id','sales',False),('product_id','products',False),('uom_id','units_of_measure',False)],['UNIQUE(company_id,sale_id,line_no)'])
table('sales_returns','reason text NOT NULL, disposition text NOT NULL', [('original_sale_id','sales',False),('customer_id','customers',True)],source=True)
table('sales_return_lines','quantity quantity_amount NOT NULL CHECK(quantity>0), net money_amount NOT NULL, tax money_amount NOT NULL, original_cost money_amount NOT NULL, tax_snapshot jsonb NOT NULL', [('return_id','sales_returns',False),('original_line_id','sale_lines',False),('warehouse_id','warehouses',False)])
table('purchase_requests','description text NOT NULL, required_on date', [('warehouse_id','warehouses',False)],source=True)
table('purchase_request_lines','quantity quantity_amount NOT NULL CHECK(quantity>0)', [('request_id','purchase_requests',False),('product_id','products',False)])
table('purchase_orders','expected_on date, payment_terms_snapshot jsonb NOT NULL, net money_amount NOT NULL, tax money_amount NOT NULL, gross money_amount NOT NULL, CHECK(net+tax=gross)', [('supplier_id','suppliers',False),('warehouse_id','warehouses',False),('request_id','purchase_requests',True)],source=True)
table('purchase_order_lines',line,[('order_id','purchase_orders',False),('product_id','products',False),('uom_id','units_of_measure',False)],['UNIQUE(company_id,order_id,line_no)'])
table('grns','delivery_reference text NOT NULL', [('order_id','purchase_orders',False),('supplier_id','suppliers',False),('warehouse_id','warehouses',False)],source=True)
table('grn_lines','accepted_quantity quantity_amount NOT NULL CHECK(accepted_quantity>=0), rejected_quantity quantity_amount NOT NULL DEFAULT 0 CHECK(rejected_quantity>=0), damaged_quantity quantity_amount NOT NULL DEFAULT 0 CHECK(damaged_quantity>=0), provisional_unit_cost unit_amount NOT NULL CHECK(provisional_unit_cost>=0)', [('grn_id','grns',False),('order_line_id','purchase_order_lines',False),('product_id','products',False),('lot_id','inventory_lots',True),('serial_id','inventory_serials',True)])
table('supplier_invoices','supplier_invoice_number text NOT NULL, invoice_date date NOT NULL, due_date date NOT NULL, net money_amount NOT NULL, tax money_amount NOT NULL, gross money_amount NOT NULL, CHECK(net+tax=gross)', [('supplier_id','suppliers',False)],['UNIQUE(company_id,supplier_id,supplier_invoice_number)'],source=True)
table('supplier_invoice_lines',line,[('invoice_id','supplier_invoices',False),('product_id','products',True),('expense_account_id','accounts',True)],['UNIQUE(company_id,invoice_id,line_no)','CHECK(product_id IS NOT NULL OR expense_account_id IS NOT NULL)'])
table('invoice_receipt_allocations','quantity quantity_amount NOT NULL CHECK(quantity>0), matched_value money_amount NOT NULL', [('invoice_line_id','supplier_invoice_lines',False),('grn_line_id','grn_lines',False)])
table('match_tolerances','version integer NOT NULL, quantity_percent rate_amount NOT NULL CHECK(quantity_percent>=0), price_percent rate_amount NOT NULL CHECK(price_percent>=0), tax_amount money_amount NOT NULL CHECK(tax_amount>=0), valid_from date NOT NULL')
table('match_exceptions','variance_type text NOT NULL, expected numeric(20,6) NOT NULL, actual numeric(20,6) NOT NULL, decision text, decided_by uuid REFERENCES users(id), decided_at timestamptz, reason text', [('invoice_id','supplier_invoices',False),('tolerance_id','match_tolerances',False)])
table('purchase_returns','reason text NOT NULL', [('supplier_id','suppliers',False),('grn_id','grns',False)],source=True)
table('purchase_return_lines','quantity quantity_amount NOT NULL CHECK(quantity>0), base_value money_amount NOT NULL', [('return_id','purchase_returns',False),('grn_line_id','grn_lines',False),('warehouse_id','warehouses',False)])
table('partner_notes',"direction text NOT NULL CHECK(direction IN ('CUSTOMER_CREDIT','CUSTOMER_DEBIT','SUPPLIER_CREDIT','SUPPLIER_DEBIT')), net money_amount NOT NULL, tax money_amount NOT NULL, gross money_amount NOT NULL, reason text NOT NULL, CHECK(net+tax=gross), CHECK((customer_id IS NOT NULL)::int+(supplier_id IS NOT NULL)::int=1)",[('customer_id','customers',True),('supplier_id','suppliers',True),('original_source_id','source_documents',False)],source=True)
table('bank_accounts','name text NOT NULL, institution text NOT NULL, account_reference_encrypted text NOT NULL, currency char(3) NOT NULL REFERENCES currencies(code)', [('account_id','accounts',False)])
table('mobile_money_accounts','name text NOT NULL, provider text NOT NULL, merchant_code text NOT NULL, credential_secret_ref text NOT NULL, currency char(3) NOT NULL REFERENCES currencies(code)', [('account_id','accounts',False)])
table('payment_methods',"code text NOT NULL, name text NOT NULL, channel text NOT NULL, requires_verification boolean NOT NULL, active boolean NOT NULL DEFAULT true",[('account_id','accounts',False)],['UNIQUE(company_id,code)'])
table('payments',"direction text NOT NULL CHECK(direction IN ('RECEIPT','DISBURSEMENT')), amount money_amount NOT NULL CHECK(amount>0), currency char(3) NOT NULL REFERENCES currencies(code), exchange_rate rate_amount NOT NULL CHECK(exchange_rate>0), base_amount money_amount NOT NULL CHECK(base_amount>0), reference text, status text NOT NULL CHECK(status IN ('PENDING','SUCCESSFUL','FAILED','CANCELLED','TIMEOUT','REVERSED')), initiated_by uuid REFERENCES users(id), posted_by uuid REFERENCES users(id), posted_at timestamptz, reversed_by uuid REFERENCES users(id), reversed_at timestamptz, verification_evidence jsonb, CHECK(status<>'SUCCESSFUL' OR posted_by IS NOT NULL)",[('method_id','payment_methods',False),('account_id','accounts',False),('customer_id','customers',True),('supplier_id','suppliers',True),('cashier_session_id','cashier_sessions',True)],source=True)
table('payment_attempts','provider text NOT NULL, merchant_code text NOT NULL, checkout_reference text, external_receipt text, state text NOT NULL, request_hash text NOT NULL, response_redacted jsonb, verified_at timestamptz', [('payment_id','payments',False)],['UNIQUE(company_id,provider,merchant_code,checkout_reference)','UNIQUE(company_id,provider,merchant_code,external_receipt)'])
table('integration_inbox','provider text NOT NULL, external_event_key text NOT NULL, payload_hash text NOT NULL, encrypted_payload text NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, failure_reason text',constraints=['UNIQUE(company_id,provider,external_event_key)'])
table('sale_payments','applied_amount money_amount NOT NULL CHECK(applied_amount>0), tendered_amount money_amount NOT NULL CHECK(tendered_amount>=applied_amount)', [('sale_id','sales',False),('payment_id','payments',False)],['UNIQUE(company_id,sale_id,payment_id)'])
for name,partner,acct in [('customer_transactions','customer_id','customers'),('supplier_transactions','supplier_id','suppliers')]:
    table(name,"entry_type text NOT NULL, currency char(3) NOT NULL REFERENCES currencies(code), debit money_amount NOT NULL DEFAULT 0, credit money_amount NOT NULL DEFAULT 0, base_debit money_amount NOT NULL DEFAULT 0, base_credit money_amount NOT NULL DEFAULT 0, due_date date, CHECK((debit>0 AND credit=0) OR (credit>0 AND debit=0))",[(partner,acct,False),('source_id','source_documents',False),('control_account_id','accounts',False),('journal_line_id','journal_lines',False)],['UNIQUE(company_id,journal_line_id)'])
table('payment_allocations','amount money_amount NOT NULL CHECK(amount>0), base_amount money_amount NOT NULL CHECK(base_amount>0)', [('payment_id','payments',False),('invoice_source_id','source_documents',False),('allocation_source_id','source_documents',False)])
out.append('ALTER TABLE payment_allocations ADD reversal_of uuid, ADD FOREIGN KEY(company_id,reversal_of) REFERENCES payment_allocations(company_id,id), ADD UNIQUE(company_id,reversal_of);')
table('settlement_statements','provider text NOT NULL, external_reference text NOT NULL, statement_date date NOT NULL, currency char(3) NOT NULL REFERENCES currencies(code)',constraints=['UNIQUE(company_id,provider,external_reference)'])
table('settlement_lines','external_reference text NOT NULL, amount money_amount NOT NULL, fee money_amount NOT NULL DEFAULT 0, exception_reason text', [('statement_id','settlement_statements',False),('payment_id','payments',True)])
table('cash_movements','signed_amount money_amount NOT NULL CHECK(signed_amount<>0), movement_type text NOT NULL', [('source_id','source_documents',False),('session_id','cashier_sessions',True),('account_id','accounts',False),('journal_line_id','journal_lines',False)],['UNIQUE(company_id,journal_line_id)'])
table('cash_counts','counted_amount money_amount NOT NULL CHECK(counted_amount>=0), denomination_snapshot jsonb NOT NULL, approved_by uuid REFERENCES users(id), approved_at timestamptz, reason text', [('session_id','cashier_sessions',True),('account_id','accounts',False)],source=True)
table('cost_centers','code text NOT NULL, name text NOT NULL',constraints=['UNIQUE(company_id,code)'])
table('expense_categories','name text NOT NULL', [('expense_account_id','accounts',False)])
table('expenses','payee_name text, description text NOT NULL, net money_amount NOT NULL, tax money_amount NOT NULL, gross money_amount NOT NULL, CHECK(net+tax=gross)', [('supplier_id','suppliers',True),('payment_id','payments',True)],source=True)
table('expense_lines',line,[('expense_id','expenses',False),('category_id','expense_categories',False),('account_id','accounts',False),('cost_center_id','cost_centers',True)])
table('tax_transactions','tax_point date NOT NULL, taxable_base money_amount NOT NULL, tax_amount money_amount NOT NULL, base_tax_amount money_amount NOT NULL, rate_snapshot rate_amount NOT NULL, classification_snapshot text NOT NULL, inclusive_snapshot boolean NOT NULL, eligible_fraction_snapshot rate_amount NOT NULL CHECK(eligible_fraction_snapshot BETWEEN 0 AND 1), tax_rule_snapshot jsonb NOT NULL, source_line_id uuid NOT NULL', [('source_id','source_documents',False),('rate_id','tax_rates',False),('account_id','accounts',False),('journal_line_id','journal_lines',True)])
table('fiscal_submissions','adapter text NOT NULL, version integer NOT NULL, payload_snapshot jsonb NOT NULL, payload_hash text NOT NULL, status text NOT NULL, external_reference text, fiscal_receipt jsonb, attempt_count integer NOT NULL DEFAULT 0, last_error text', [('source_id','source_documents',False)],['UNIQUE(company_id,source_id,adapter)','UNIQUE(company_id,adapter,external_reference)'])
table('accounting_rule_sets','event_type text NOT NULL, version integer NOT NULL, valid_from date NOT NULL, valid_to date, priority integer NOT NULL, approved_by uuid REFERENCES users(id), approved_at timestamptz, active boolean NOT NULL DEFAULT false', [('branch_id','branches',True),('warehouse_id','warehouses',True),('product_id','products',True),('category_id','product_categories',True),('tax_category_id','tax_categories',True),('payment_method_id','payment_methods',True)],['UNIQUE(company_id,event_type,version)'])
table('accounting_rule_legs',"leg_code text NOT NULL, side text NOT NULL CHECK(side IN ('DEBIT','CREDIT')), amount_key text NOT NULL", [('rule_set_id','accounting_rule_sets',False),('account_id','accounts',False)],['UNIQUE(company_id,rule_set_id,leg_code)'])
table('approval_policies','event_type text NOT NULL, version integer NOT NULL, threshold_base money_amount NOT NULL CHECK(threshold_base>=0), independent_creator boolean NOT NULL, independent_poster boolean NOT NULL, active boolean NOT NULL DEFAULT false', [('branch_id','branches',True)],['UNIQUE(company_id,event_type,version)'])
table('approval_steps','step_no integer NOT NULL CHECK(step_no>0), required_permission text NOT NULL REFERENCES permissions(code), minimum_approvers integer NOT NULL DEFAULT 1 CHECK(minimum_approvers>0)', [('policy_id','approval_policies',False)],['UNIQUE(company_id,policy_id,step_no)'])
table('approval_decisions',"revision integer NOT NULL, decision text NOT NULL CHECK(decision IN ('APPROVE','REJECT')), comments text NOT NULL", [('source_id','source_documents',False),('step_id','approval_steps',False)],['UNIQUE(company_id,source_id,revision,step_id,created_by)'])
table('attachments','object_key text NOT NULL UNIQUE, original_name text NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes>0), sha256 text NOT NULL, scan_status text NOT NULL CHECK(scan_status IN (\'PENDING\',\'CLEAN\',\'REJECTED\')), retained_until date, legal_hold boolean NOT NULL DEFAULT false', [('source_id','source_documents',False)])
table('exchange_rates','currency char(3) NOT NULL REFERENCES currencies(code), base_currency char(3) NOT NULL REFERENCES currencies(code), effective_at timestamptz NOT NULL, rate rate_amount NOT NULL CHECK(rate>0), provider text NOT NULL',constraints=['UNIQUE(company_id,currency,base_currency,effective_at)'])
table('system_configuration','key text NOT NULL, version integer NOT NULL, value jsonb NOT NULL, approved_by uuid REFERENCES users(id), effective_at timestamptz NOT NULL',constraints=['UNIQUE(company_id,key,version)'])
table('reconciliation_runs','cutoff_at timestamptz NOT NULL, snapshot_watermarks jsonb NOT NULL, status text NOT NULL, completed_at timestamptz')
table('reconciliation_exceptions','check_code text NOT NULL, expected money_amount NOT NULL, actual money_amount NOT NULL, dimensions jsonb NOT NULL, resolution_source_id uuid, resolved_by uuid REFERENCES users(id), resolved_at timestamptz', [('run_id','reconciliation_runs',False),('source_id','source_documents',True)],['FOREIGN KEY(company_id,resolution_source_id) REFERENCES source_documents(company_id,id)'])
table('report_exports','report_type text NOT NULL, filters jsonb NOT NULL, snapshot_at timestamptz NOT NULL, format text NOT NULL CHECK(format IN (\'CSV\',\'XLSX\',\'PDF\')), status text NOT NULL, object_key text, content_hash text, expires_at timestamptz')
for n in names:
    out += [f'ALTER TABLE {n} ENABLE ROW LEVEL SECURITY;',f'CREATE POLICY company_isolation ON {n} USING(company_id=company_uuid()) WITH CHECK(company_id=company_uuid());',f'CREATE INDEX {n}_company_created ON {n}(company_id,created_at);']
for n in ['inventory_movements','customer_transactions','supplier_transactions','payment_allocations','cash_movements','tax_transactions','approval_decisions','cost_layer_allocations']:
    out += [f'CREATE TRIGGER {n}_immutable BEFORE UPDATE OR DELETE ON {n} FOR EACH ROW EXECUTE FUNCTION deny_mutation();']
for n in ['customers','suppliers','products']:
    out += [f'CREATE INDEX {n}_name_search ON {n} USING gin(name gin_trgm_ops);']
out += ['COMMIT;']
Path('db/002-domains.sql').write_text('\n\n'.join(out)+'\n')
Path('docs/table-inventory.txt').write_text('\n'.join(names)+'\n')
print(f'Generated {len(names)} target domain tables')
