// Operator-only recovery tool. Credentials stay in environment, never child arguments or logs.
const fs=require('fs'),fsp=require('fs/promises'),path=require('path'),os=require('os');
const {randomBytes,randomUUID,createHash,createCipheriv,createDecipheriv}=require('crypto');
const {pipeline}=require('stream/promises'),{execFileSync}=require('child_process');const {Pool}=require('pg');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const MAGIC=Buffer.from('ERPBAK01');
function run(cmd,args,env=process.env){try{return execFileSync(cmd,args,{env,stdio:['ignore','pipe','pipe'],encoding:'utf8',maxBuffer:32*1024*1024});}catch{throw Error(cmd+' failed; no credentials/row values were printed. Inspect database availability, permissions and tool versions.');}}
function database(){const text=process.env.BACKUP_DATABASE_URL||process.env.MIGRATION_DATABASE_URL;if(!text)throw Error('BACKUP_DATABASE_URL or MIGRATION_DATABASE_URL is required');const u=new URL(text);if(!['postgres:','postgresql:'].includes(u.protocol))throw Error('PostgreSQL URL required');return {url:u,env:{...process.env,PGHOST:u.hostname,PGPORT:u.port||'5432',PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGDATABASE:decodeURIComponent(u.pathname.slice(1)),...(u.searchParams.has('sslmode')?{PGSSLMODE:u.searchParams.get('sslmode')}:{})}};}
function key(){const v=process.env.BACKUP_ENCRYPTION_KEY;if(!v){if(process.env.NODE_ENV==='production')throw Error('Production backups require BACKUP_ENCRYPTION_KEY (64 hex characters)');return null;}if(!/^[0-9a-fA-F]{64}$/.test(v))throw Error('Invalid BACKUP_ENCRYPTION_KEY');return Buffer.from(v,'hex');}
async function digest(file){const hash=createHash('sha256');for await(const chunk of fs.createReadStream(file))hash.update(chunk);return hash.digest('hex');}
async function seal(source,dest,k){if(!k){await fsp.copyFile(source,dest,fs.constants.COPYFILE_EXCL);return;}const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',k,iv);await fsp.writeFile(dest,Buffer.concat([MAGIC,iv]),{mode:0o600,flag:'wx'});await pipeline(fs.createReadStream(source),cipher,fs.createWriteStream(dest,{flags:'a',mode:0o600}));await fsp.appendFile(dest,cipher.getAuthTag());}
async function unseal(source,dest,k,encrypted){if(!encrypted){await fsp.copyFile(source,dest,fs.constants.COPYFILE_EXCL);return;}if(!k)throw Error('Encrypted backup requires its original encryption key');const size=(await fsp.stat(source)).size;if(size<36)throw Error('Invalid encrypted backup');const handle=await fsp.open(source,'r'),header=Buffer.alloc(20),tag=Buffer.alloc(16);try{await handle.read(header,0,20,0);await handle.read(tag,0,16,size-16);}finally{await handle.close();}if(!header.subarray(0,8).equals(MAGIC))throw Error('Invalid encrypted backup header');const decipher=createDecipheriv('aes-256-gcm',k,header.subarray(8));decipher.setAuthTag(tag);await pipeline(fs.createReadStream(source,{start:20,end:size-17}),decipher,fs.createWriteStream(dest,{flags:'wx',mode:0o600}));}
async function backup(kind,dest){const k=key(),base=path.resolve(process.env.BACKUP_DIRECTORY||'.runtime/backups');await fsp.mkdir(base,{recursive:true,mode:0o700});dest=path.resolve(dest||path.join(base,kind+'-'+new Date().toISOString().replace(/[:.]/g,'-')+'-'+randomUUID()+'.erpbackup'));if(fs.existsSync(dest)||fs.existsSync(dest+'.manifest.json'))throw Error('Backup destination already exists');await fsp.mkdir(path.dirname(dest),{recursive:true,mode:0o700});const tmp=await fsp.mkdtemp(path.join(os.tmpdir(),'erp-backup-'));await fsp.chmod(tmp,0o700);const pending=dest+'.partial-'+randomUUID();try{let databaseCounts;const raw=path.join(tmp,'data');if(kind==='database'){const db=database(),pool=new Pool({connectionString:db.url.toString(),connectionTimeoutMillis:3000}),client=await pool.connect();try{await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const snapshot=(await client.query('SELECT pg_export_snapshot() AS id')).rows[0].id;databaseCounts=(await client.query('SELECT (SELECT count(*) FROM source_documents) AS sources,(SELECT count(*) FROM journal_entries) AS journals,(SELECT count(*) FROM journal_lines) AS lines,(SELECT count(*) FROM audit_logs) AS audit_events')).rows[0];run('pg_dump',['--format=custom','--snapshot',snapshot,'--file',raw],db.env);}finally{await client.query('ROLLBACK');client.release();await pool.end();}}else{const root=process.env.FILE_STORAGE_ROOT;if(!root)throw Error('FILE_STORAGE_ROOT is required');run('python3',[path.join(__dirname,'file-archive.py'),'pack',raw,path.resolve(root)]);}await seal(raw,pending,k);await fsp.chmod(pending,0o600);const manifest={format:1,kind,...(databaseCounts?{databaseCounts}:{}),createdAt:new Date().toISOString(),encrypted:!!k,cipher:k?'AES-256-GCM':null,sha256:await digest(pending),bytes:(await fsp.stat(pending)).size};await fsp.link(pending,dest);await fsp.unlink(pending);await fsp.writeFile(dest+'.manifest.json',JSON.stringify(manifest,null,2)+'\n',{flag:'wx',mode:0o600});return {backup:dest,manifest};}finally{await fsp.rm(tmp,{recursive:true,force:true});await fsp.rm(pending,{force:true});}}
async function restore(kind,file,target,confirm){if(confirm!=='--confirm-restore')throw Error('Explicit --confirm-restore is required');file=path.resolve(file);const m=JSON.parse(await fsp.readFile(file+'.manifest.json','utf8'));if(m.format!==1||m.kind!==kind||typeof m.encrypted!=='boolean'||m.sha256!==await digest(file)||m.bytes!==(await fsp.stat(file)).size)throw Error('Backup manifest or checksum mismatch');const k=key(),tmp=await fsp.mkdtemp(path.join(os.tmpdir(),'erp-restore-'));await fsp.chmod(tmp,0o700);try{const raw=path.join(tmp,'data');await unseal(file,raw,k,m.encrypted);if(kind==='files'){if(!target)throw Error('New file restore directory required');run('python3',[path.join(__dirname,'file-archive.py'),'restore',raw,path.resolve(target)]);return {restored:true,kind,target};}
 if(!/^erp_restore_[a-z0-9_]{1,45}$/.test(target||''))throw Error('Restore database name must start erp_restore_ and contain only lowercase letters, digits or underscores');
 const db=database(),adminUrl=new URL(db.url);adminUrl.pathname='/postgres';const admin=new Pool({connectionString:adminUrl.toString()});try{if((await admin.query('SELECT 1 FROM pg_database WHERE datname=$1',[target])).rowCount)throw Error('Restore target already exists; refusing overwrite');
 // Known restricted runtime roles must exist on a fresh recovery host before restoring ACLs.
 await admin.query("DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='erp_runtime') THEN CREATE ROLE erp_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF; IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='erp_auth_worker') THEN CREATE ROLE erp_auth_worker LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF; END $$");
 await admin.query('CREATE DATABASE '+target);run('pg_restore',['--exit-on-error','--single-transaction','--no-owner','--dbname',target,raw],{...db.env,PGDATABASE:target});
 }finally{await admin.end();}const u=new URL(db.url);u.pathname='/'+target;const pool=new Pool({connectionString:u.toString()});try{if((await pool.query("SELECT to_regclass('public.service_heartbeats') AS relation")).rows[0].relation)await pool.query("UPDATE service_heartbeats SET last_seen_at='epoch'");const exceptions=(await pool.query("SELECT j.id FROM journal_entries j LEFT JOIN journal_lines l ON l.journal_id=j.id GROUP BY j.id HAVING count(l.id)<2 OR sum(l.debit-l.credit)<>0 OR sum(l.base_debit-l.base_credit)<>0")).rowCount;if(exceptions)throw Error('Restored journal arithmetic integrity check failed');const counts=(await pool.query('SELECT (SELECT count(*) FROM source_documents) AS sources,(SELECT count(*) FROM journal_entries) AS journals,(SELECT count(*) FROM journal_lines) AS lines,(SELECT count(*) FROM audit_logs) AS audit_events')).rows[0];if(m.databaseCounts&&JSON.stringify(counts)!==JSON.stringify(m.databaseCounts))throw Error('Restored row counts differ from exported backup snapshot');return {restored:true,kind,target,counts,journalArithmetic:'PASS',operationalReconciliations:'NOT_IMPLEMENTED'};}finally{await pool.end();}
 }finally{await fsp.rm(tmp,{recursive:true,force:true});}}
async function main(){const [op,a,b,c]=process.argv.slice(2);let result;if(op==='backup-db')result=await backup('database',a);else if(op==='backup-files')result=await backup('files',a);else if(op==='restore-db')result=await restore('database',a,b,c);else if(op==='restore-files')result=await restore('files',a,b,c);else throw Error('Expected backup-db, restore-db, backup-files or restore-files');console.log(JSON.stringify(result,null,2));}
if(require.main===module)main().catch(e=>{console.error('Recovery operation refused/failed:',e.message);process.exitCode=1;});
module.exports={backup,restore,digest};
