"""Generate requirement-level live ledgers from an explicit, editable catalog."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
catalog=root/'docs/implementation-requirements.json'
if not catalog.exists():
 groups=[
 ('Foundation','Repository structure|Monorepo|TypeScript|Next.js|NestJS|PostgreSQL|Docker|Environment configuration|Logging|Error handling|API architecture|Database migrations|Shared types|Validation|Testing infrastructure','schema_migrations','apps/api/src/main.ts; apps/web','No financial effect','No stock effect','No tax effect'),
 ('Security','Authentication|Sessions|Users|Roles|Permissions|RBAC middleware|Password management|Session expiration|Logout|Account activation/deactivation|Audit logging|Permission enforcement|MFA/step-up|Breached password screening','users; sessions; memberships; roles; role_permissions; user_roles; security_events; audit_logs','/api/v1/auth/*; /api/v1/admin/users; /api/v1/admin/roles','Protects every financial command','Protects movement commands','Protects tax configuration'),
 ('Organization','Companies|Branches|Warehouses|POS terminals|Financial periods|Currencies|Document sequences|Multi-branch scoping|Multi-warehouse scoping','companies; branches; warehouses; pos_terminals; financial_periods; currencies; document_sequences','/api/v1/admin/company; /api/v1/admin/branches; /api/v1/admin/warehouses; /api/v1/periods','Periods and source numbering; no editable balances','Warehouse ownership and scope','Company tax identity'),
 ('Accounting','Chart of Accounts|Account hierarchy|Journal entries|Journal lines|Posting engine|Reversal engine|General Ledger|Accounting rules|Accounting validation|Reconciliation framework|Trial Balance|Profit and Loss|Balance Sheet|Cash Flow|AR reconciliation|AP reconciliation|Inventory reconciliation|Tax reconciliation|Cash reconciliation','accounts; account_change_requests; source_documents; journal_entries; journal_lines; accounting_rule_sets','/api/v1/admin/account-changes; /api/v1/journals/*; /api/v1/reports/*','Balanced, attributed double-entry; immutable posted data','Movement valuation must equal stock control','Tax ledger must equal tax control'),
 ('Tax','Tax types|Tax rates|Tax categories|Inclusive tax|Exclusive tax|Zero-rated|Exempt|Non-taxable|Effective dates|Tax accounts|Product tax configuration|Tax transaction records|Immutable tax snapshots|eTIMS integration','taxes; tax_rates; tax_categories; product_taxes; tax_transactions','Not implemented','Input/output tax control entries','Nonrecoverable tax capitalized under policy','Configurable effective dated calculations and original snapshots'),
 ('Inventory','Product master|Categories|Brands|Units|Barcodes|Pricing|Product taxes|Inventory balances|Inventory movements|Stock transfers|Stock counts|Stock adjustments|Inventory valuation|Weighted average valuation|Batches|Serials|Expiry|Reservations|Concurrent stock operations','products; categories; brands; units; product_barcodes; inventory_movements; inventory_balances; stock_transfers; stock_counts','Not implemented','Stock/GRNI/COGS/variance accounts through central posting','Authoritative movements; no direct balance edits','Historical product tax snapshots'),
 ('Customers and AR','Customers|Walk-in customer|Customer accounts|Credit limits|Payment terms|Customer ledger|AR|Customer statements|Aging|Customer payments|Payment allocations|Customer credit notes|Customer debit notes','customers; ar_transactions; payment_allocations; sales','Not implemented','AR control reconciles to customer subledger','Linked sales/return effects','Invoice and credit-note tax linkage'),
 ('Suppliers and AP','Suppliers|Supplier accounts|Supplier ledger|AP|Supplier statements|Aging|Supplier payments|Payment allocations|Supplier credit notes|Supplier debit notes','suppliers; ap_transactions; payment_allocations; supplier_invoices','Not implemented','AP control reconciles to supplier subledger','Linked procurement/return effects','Recoverable input tax and adjustments'),
 ('Purchasing','Purchase requests|Purchase orders|PO approvals|GRNs|Supplier invoices|Three-way matching|Partial orders|Partial receipts|Partial invoicing|Rejected quantities|Damaged quantities|Price variances|Quantity variances|Tax differences|Duplicate invoice detection','purchase_requests; purchase_orders; grns; supplier_invoices; source_documents','Not implemented','GRNI at receipt; invoice clears GRNI and posts AP/tax/variance','Receipt movements into accepted/quarantine locations','Frozen supplier invoice tax, matched to document'),
 ('POS','Barcode scanning|Manual barcode entry|Product search|Customer search|Walk-in cash sale|Registered customer sale|Credit sale|Sale cancellation|Discounts|Multiple payments|Split payments|Receipt printing|Receipt reprinting|Hold/resume sale|Fast cashier keyboard flow','sales; sale_lines; payments; source_documents','Not implemented','Dr cash/clearing/AR; Cr revenue/output tax; Dr COGS Cr stock','Atomic stock depletion at original valuation','Inclusive/exclusive calculation snapshots'),
 ('Cashiers','Cashier sessions|Opening float|Cashier sales attribution|Cashier payments|Cashier refunds|Cash movements|Closing|Expected versus actual cash|Cashier reconciliation|Variance approval','cashier_sessions; cash_movements; cash_counts','Not implemented','Cash/drawer/variance control with approval','Linked sales and returns only','Sales/refund tax linkage'),
 ('Payments','Cash payments|Bank payments|Card payments|Cheques|EFT|Mobile money|Configurable payment methods|Full payment|Partial payment|Split payment|Advance payment|Unallocated payment|Payment allocation|Payment reversal|Payment idempotency','payment_methods; payments; payment_allocations; payment_attempts','Not implemented','Clearing/bank/cash versus AR/AP/deposits; linked reversal','No direct stock adjustment','Tax only at applicable source/tax-point workflow'),
 ('M-Pesa','Provider abstraction|M-Pesa STK Push|Pending payment|Callback validation|Transaction matching|Payment posting|Settlement reconciliation|Duplicate callbacks|Timeout|Failure|Cancellation|Reversal|Network errors|Mock provider|Production provider activation','payment_attempts; integration_callbacks; payments','Not implemented','Only independently verified success posts payment and journal','No callback-driven duplicate stock effect','Reference original sale tax; no duplicate tax'),
 ('Sales returns','Full return|Partial return|Original invoice reference|Stock return|Customer credit|Cash refund|Payment reversal|Tax reversal|Accounting reversal','sales_returns; sales_return_lines; source_documents','Not implemented','Original-value COGS/tax/revenue/AR or refund reversals','Return at original cost; cumulative limits','Original tax snapshot proportional reversal'),
 ('Supplier returns','Supplier return|Original purchase/GRN/invoice linkage|Inventory reduction|Supplier credit/debit note|AP adjustment|Tax adjustment|Accounting reversal','purchase_returns; purchase_return_lines; source_documents','Not implemented','Dr AP/claim Cr inventory/input tax as policy','Return approved quantities with original cost linkage','Original input tax adjustment'),
 ('Expenses and cash','Business expenses|Expense categories|Expense approval|Expense payments|Expense tax treatment|Petty cash|Cash replenishment|Cash reconciliation','expenses; petty_cash_funds; cash_movements','Not implemented','Expense/input tax versus AP/cash; separate payment posting','Only inventory-relevant expenses affect capitalization','Recoverability policy and source snapshot'),
 ('Reporting','Sales summary|Sales by product|Sales by category|Sales by customer|Sales by cashier|Sales by user|Sales by branch|Sales by payment method|Returns report|Discount report|Sales tax report|Gross profit|Stock balance|Stock movement|Stock valuation|Stock aging|Stock count variance|Low stock|Inventory profitability|Customer statement|Customer ledger|Customer aging|Outstanding customer invoices|Customer payments report|Supplier statement|Supplier ledger|Supplier aging|Outstanding supplier invoices|Supplier payments report|Cashier session report|Cashier reconciliation report|Cashier payment summary|Cashier variance|Journal report|AR report|AP report|Tax report|Audit report|Export','Authoritative source, movement, payment, subledger, tax and journal tables','Core journal/trial-balance/audit routes only','Derived reports; discrepancies visible, never auto-adjusted','Derived movement/valuation reports','Derived tax register'),
 ('Traceability','Source-to-business-transaction drilldown|Source-to-payment drilldown|Source-to-inventory drilldown|Source-to-customer/supplier-ledger drilldown|Source-to-tax drilldown|Source-to-journal drilldown|Source-to-audit drilldown|Created attribution|Updated attribution|Approved attribution|Posted attribution|Cancelled attribution|Reversed attribution|System/integration initiator retention','source_documents; document_links; document_events; audit_logs','/api/v1/documents/:id (core journals only)','Permanent source/journal/reversal links','Permanent movement source links','Permanent tax source/snapshot links'),
 ('UX','Searchable customers|Searchable suppliers|Searchable products|Searchable barcodes|Searchable accounts|Searchable users|Searchable branches|Searchable warehouses|Searchable tax types|Searchable payment methods|Searchable documents|Responsive UI|Mobile UX|Dark mode|Form validation|Error states|Loading states|Success states|Empty states|Action confirmations|POS usability','Not applicable','Existing React screens; operational screens pending','UI never chooses posting accounts or trusted actor','UI never edits authoritative stock','UI never hard-codes tax rates'),
 ('Testing','Tax unit tests|Accounting unit tests|Pricing unit tests|Discount unit tests|Inventory unit tests|Allocation unit tests|Aging unit tests|Reconciliation unit tests|Sales integration|Purchasing integration|Payments integration|Inventory integration|Accounting integration|Customer integration|Supplier integration|M-Pesa integration|RBAC integration|Full operational E2E|Concurrency tests|Idempotency tests|Security tests|Upload attack tests|Privilege escalation tests|Database integrity tests|Financial rollback tests|Full-system reconciliation scenario','Disposable PostgreSQL databases and browser fixtures','apps/api/test; scripts/browser-*.cjs','Prove every financial side effect, balance and rollback','Prove locking, duplicate suppression and valuation','Prove exact calculations and original snapshots'),
 ('Deployment','Production Dockerfile|docker-compose.yml|docker-compose.prod.yml|PostgreSQL persistence|Worker|Health live|Health ready|Health database|Health storage|Health worker|Ubuntu installation|Ubuntu deployment|Ubuntu migration|Ubuntu rollback|Ubuntu logs|Ubuntu restart|Server reboot survival|Container recreation survival|Cloudflare Tunnel|Private infrastructure network|Database backup|Database restore|File backup|File restore|Backup retention|Disaster recovery drill|Redis where required|MinIO where required','Deployment metadata; existing database; local file/mail storage','Scripts/configuration and /api/health/* pending','No deployment may fabricate financial data','Restore stock authority with journal/subledger data','Restore tax snapshots and adapter references'),
 ('Documentation','Architecture documentation|Accounting documentation|Workflow documentation|Database documentation|API documentation|Security documentation|Deployment documentation|Backup documentation|Troubleshooting|User guide|Requirements matrix|Implementation status|Safe comprehensive demo seed|Production readiness review','Source documentation and migrations','docs/; scripts/; .env.example','Explicit boundaries and accounting rules','Movement and valuation contracts','Policy/legal/provider activation requirements')]
 rows=[]
 for phase,(module,names,tables,api,accounting,inventory,tax) in enumerate(groups,1):
  for index,title in enumerate(names.split('|'),1):
   rows.append(dict(id=f'{phase:02d}.{index:02d}',requirement=title,module=module,tables=tables,api=api,frontend='Existing core screens only; module UI pending',accounting=accounting,inventory=inventory,tax=tax,permissions='Explicit backend grants required; operational grants pending',audit='Attribution + append-only audit required; core only implemented',tests='No complete module evidence yet',status='NOT_STARTED'))
 verified={'Repository structure','Monorepo','TypeScript','NestJS','PostgreSQL','Authentication','Sessions','Session expiration','Logout','Password management','Accounting validation'}
 partial_modules={'Foundation','Security','Organization','Accounting','Traceability','UX','Testing','Documentation','Deployment'}
 for r in rows:
  if r['module'] in partial_modules:r['status']='IN_PROGRESS'
  if r['requirement'] in verified:
   r['status']='VERIFIED';r['tests']='v0.5: docs/test-results.txt (76 tests); docs/browser-*-result.json. Verification is confined to the named core capability.'
  if r['module']=='Documentation' and r['requirement'] in ['Implementation status','Requirements matrix']:r['status']='IMPLEMENTED';r['tests']='Generated by scripts/sync-implementation-status.py; completeness review pending.'
  if r['requirement'] in ['Production provider activation','eTIMS integration']:
   r['status']='BLOCKED';r['tests']='Provider contracts/current specifications, sandbox/production credentials and external acceptance required; local adapter work remains unfinished.'
  if r['requirement'] in ['Redis where required','MinIO where required']:
   r['tests']='Not justified by implemented modules yet; evaluate before adding infrastructure. Local storage currently contains development auth mail only.'
 catalog.write_text(json.dumps(rows,indent=2)+'\n')
rows=json.loads(catalog.read_text())
allowed={'NOT_STARTED','IN_PROGRESS','IMPLEMENTED','TESTING','VERIFIED','BLOCKED'}
assert all(r['status'] in allowed for r in rows)
checkpoint=root/'docs/EXECUTION_CHECKPOINT.md'
if not checkpoint.exists():checkpoint.write_text('Current task: adapt the existing React workspace to the newly required Next.js host without replacing business screens. Then complete health/recovery validation and resume accounting configuration.\n')
counts={s:sum(r['status']==s for r in rows) for s in sorted(allowed)}
text='# Live implementation status\n\n**NOT COMPLETE — production readiness is not claimed.**\n\nStatuses: NOT_STARTED / IN_PROGRESS / IMPLEMENTED / TESTING / VERIFIED / BLOCKED. VERIFIED is evidence-scoped; a verified core capability does not verify an unreleased operational module. Design tables alone do not count as implementation.\n\n## Current execution checkpoint\n\n'+checkpoint.read_text()+'\n\n## Requirement coverage\n\n'+', '.join(f'{k}: {v}' for k,v in counts.items())+'\n\n| ID | Requirement | Module | Status | Evidence / remaining work |\n|---|---|---|---|---|\n'
for r in rows:text+='| '+' | '.join([r['id'],r['requirement'],r['module'],r['status'],r['tests']])+' |\n'
(root/'docs/IMPLEMENTATION_STATUS.md').write_text(text)
columns=['id','requirement','module','tables','api','frontend','accounting','inventory','tax','permissions','audit','tests','status']
text='# Requirements traceability matrix\n\nCore evidence and future effects are explicitly distinguished by status. Planned API/table descriptions are not released endpoints. The original 89-item master mapping remains in requirements.csv; this matrix expands the continuous-execution requirements.\n\n| '+' | '.join(c.title() for c in columns)+' |\n|'+'---|'*len(columns)+'\n'
for r in rows:text+='| '+' | '.join(str(r[c]).replace('|',' / ').replace('\n',' ') for c in columns)+' |\n'
(root/'docs/REQUIREMENTS_MATRIX.md').write_text(text)
print(f'Generated both ledgers for {len(rows)} individually tracked requirements')
